<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Notes for 431 - 7&nbsp; Summarizing Quantities</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-summarizing_categories.html" rel="next">
<link href="./06-nhanes_cc.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partBhold.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Rest of Part B coming soon</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partChold.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Part C coming soon.</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">7.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#working-with-the-nh_750-data" id="toc-working-with-the-nh_750-data" class="nav-link" data-scroll-target="#working-with-the-nh_750-data"> <span class="header-section-number">7.2</span> Working with the <code>nh_750</code> data</a></li>
  <li><a href="#the-summary-function-for-quantitative-data" id="toc-the-summary-function-for-quantitative-data" class="nav-link" data-scroll-target="#the-summary-function-for-quantitative-data"> <span class="header-section-number">7.3</span> The <code>summary</code> function for Quantitative data</a></li>
  <li><a href="#measuring-the-center-of-a-distribution" id="toc-measuring-the-center-of-a-distribution" class="nav-link" data-scroll-target="#measuring-the-center-of-a-distribution"> <span class="header-section-number">7.4</span> Measuring the Center of a Distribution</a>
  <ul class="collapse">
  <li><a href="#the-mean-and-the-median" id="toc-the-mean-and-the-median" class="nav-link" data-scroll-target="#the-mean-and-the-median"> <span class="header-section-number">7.4.1</span> The Mean and The Median</a></li>
  <li><a href="#dealing-with-missingness" id="toc-dealing-with-missingness" class="nav-link" data-scroll-target="#dealing-with-missingness"> <span class="header-section-number">7.4.2</span> Dealing with Missingness</a></li>
  <li><a href="#the-mode-of-a-quantitative-variable" id="toc-the-mode-of-a-quantitative-variable" class="nav-link" data-scroll-target="#the-mode-of-a-quantitative-variable"> <span class="header-section-number">7.4.3</span> The Mode of a Quantitative Variable</a></li>
  </ul></li>
  <li><a href="#measuring-the-spread-of-a-distribution" id="toc-measuring-the-spread-of-a-distribution" class="nav-link" data-scroll-target="#measuring-the-spread-of-a-distribution"> <span class="header-section-number">7.5</span> Measuring the Spread of a Distribution</a>
  <ul class="collapse">
  <li><a href="#rangeandiqr" id="toc-rangeandiqr" class="nav-link" data-scroll-target="#rangeandiqr"> <span class="header-section-number">7.5.1</span> The Range and the Interquartile Range (IQR)</a></li>
  <li><a href="#the-variance-and-the-standard-deviation" id="toc-the-variance-and-the-standard-deviation" class="nav-link" data-scroll-target="#the-variance-and-the-standard-deviation"> <span class="header-section-number">7.5.2</span> The Variance and the Standard Deviation</a></li>
  <li><a href="#obtaining-the-variance-and-standard-deviation-in-r" id="toc-obtaining-the-variance-and-standard-deviation-in-r" class="nav-link" data-scroll-target="#obtaining-the-variance-and-standard-deviation-in-r"> <span class="header-section-number">7.5.3</span> Obtaining the Variance and Standard Deviation in R</a></li>
  <li><a href="#defining-the-variance-and-standard-deviation" id="toc-defining-the-variance-and-standard-deviation" class="nav-link" data-scroll-target="#defining-the-variance-and-standard-deviation"> <span class="header-section-number">7.5.4</span> Defining the Variance and Standard Deviation</a></li>
  <li><a href="#interpreting-the-sd-when-the-data-are-normally-distributed" id="toc-interpreting-the-sd-when-the-data-are-normally-distributed" class="nav-link" data-scroll-target="#interpreting-the-sd-when-the-data-are-normally-distributed"> <span class="header-section-number">7.5.5</span> Interpreting the SD when the data are Normally distributed</a></li>
  <li><a href="#chebyshevs-inequality-one-interpretation-of-the-standard-deviation" id="toc-chebyshevs-inequality-one-interpretation-of-the-standard-deviation" class="nav-link" data-scroll-target="#chebyshevs-inequality-one-interpretation-of-the-standard-deviation"> <span class="header-section-number">7.5.6</span> Chebyshev’s Inequality: One Interpretation of the Standard Deviation</a></li>
  </ul></li>
  <li><a href="#measuring-the-shape-of-a-distribution" id="toc-measuring-the-shape-of-a-distribution" class="nav-link" data-scroll-target="#measuring-the-shape-of-a-distribution"> <span class="header-section-number">7.6</span> Measuring the Shape of a Distribution</a>
  <ul class="collapse">
  <li><a href="#multimodal-vs.-unimodal-distributions" id="toc-multimodal-vs.-unimodal-distributions" class="nav-link" data-scroll-target="#multimodal-vs.-unimodal-distributions"> <span class="header-section-number">7.6.1</span> Multimodal vs.&nbsp;Unimodal distributions</a></li>
  <li><a href="#skew" id="toc-skew" class="nav-link" data-scroll-target="#skew"> <span class="header-section-number">7.6.2</span> Skew</a></li>
  <li><a href="#kurtosis" id="toc-kurtosis" class="nav-link" data-scroll-target="#kurtosis"> <span class="header-section-number">7.6.3</span> Kurtosis</a></li>
  </ul></li>
  <li><a href="#multiple-summaries-at-once" id="toc-multiple-summaries-at-once" class="nav-link" data-scroll-target="#multiple-summaries-at-once"> <span class="header-section-number">7.7</span> Multiple Summaries at once</a>
  <ul class="collapse">
  <li><a href="#favstats-from-the-mosaic-package" id="toc-favstats-from-the-mosaic-package" class="nav-link" data-scroll-target="#favstats-from-the-mosaic-package"> <span class="header-section-number">7.7.1</span> <code>favstats()</code> from the mosaic package</a></li>
  <li><a href="#using-descr-from-summarytools" id="toc-using-descr-from-summarytools" class="nav-link" data-scroll-target="#using-descr-from-summarytools"> <span class="header-section-number">7.7.2</span> Using <code>descr()</code> from <code>summarytools</code></a></li>
  <li><a href="#describe-in-the-psych-package" id="toc-describe-in-the-psych-package" class="nav-link" data-scroll-target="#describe-in-the-psych-package"> <span class="header-section-number">7.7.3</span> <code>describe</code> in the <code>psych</code> package</a></li>
  <li><a href="#the-hmisc-packages-version-of-describe" id="toc-the-hmisc-packages-version-of-describe" class="nav-link" data-scroll-target="#the-hmisc-packages-version-of-describe"> <span class="header-section-number">7.7.4</span> The <code>Hmisc</code> package’s version of <code>describe</code></a></li>
  <li><a href="#using-tbl_summary-from-gtsummary" id="toc-using-tbl_summary-from-gtsummary" class="nav-link" data-scroll-target="#using-tbl_summary-from-gtsummary"> <span class="header-section-number">7.7.5</span> Using tbl_summary() from <code>gtsummary</code></a></li>
  <li><a href="#some-other-options" id="toc-some-other-options" class="nav-link" data-scroll-target="#some-other-options"> <span class="header-section-number">7.7.6</span> Some Other Options</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-summ_quant" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Most numerical summaries that might be new to you are applied most appropriately to quantitative variables. The measures that will interest us relate to:</p>
<ul>
<li>the <strong>center</strong> of our distribution,</li>
<li>the <strong>spread</strong> of our distribution, and</li>
<li>the <strong>shape</strong> of our distribution.</li>
</ul>
<section id="setup-packages-used-here" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">7.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This chapter also requires that the <code>Hmisc</code>, <code>mosaic</code>, and <code>psych</code> packages are loaded on your machine, but these packages are not loaded with <code>library()</code> above.</p>
</section>
<section id="working-with-the-nh_750-data" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="working-with-the-nh_750-data"><span class="header-section-number">7.2</span> Working with the <code>nh_750</code> data</h2>
<p>To demonstrate key ideas in this Chapter, we will consider our sample of 750 adults ages 21-64 from NHANES 2011-12 which includes some missing values. We’ll load into the <code>nh_750</code> data frame the information from the <code>nh_adult750.Rds</code> file we created in <a href="04-nhanes.html#sec-nh750"><span>Section&nbsp;4.3.2</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nh_adult750.Rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-summary-function-for-quantitative-data" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="the-summary-function-for-quantitative-data"><span class="header-section-number">7.3</span> The <code>summary</code> function for Quantitative data</h2>
<p>R provides a small sampling of numerical summaries with the <code>summary</code> function, for instance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age             BMI             SBP             DBP        
 Min.   :21.00   Min.   :16.70   Min.   : 83.0   Min.   :  0.00  
 1st Qu.:30.00   1st Qu.:24.20   1st Qu.:108.0   1st Qu.: 66.00  
 Median :40.00   Median :27.90   Median :118.0   Median : 73.00  
 Mean   :40.82   Mean   :29.08   Mean   :118.8   Mean   : 72.69  
 3rd Qu.:51.00   3rd Qu.:32.10   3rd Qu.:127.0   3rd Qu.: 80.00  
 Max.   :64.00   Max.   :80.60   Max.   :209.0   Max.   :108.00  
                 NA's   :5       NA's   :33      NA's   :33      
     Pulse       
 Min.   : 40.00  
 1st Qu.: 66.00  
 Median : 72.00  
 Mean   : 73.53  
 3rd Qu.: 80.00  
 Max.   :124.00  
 NA's   :32      </code></pre>
</div>
</div>
<p>This basic summary includes a set of five <strong>quantiles</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, plus the sample’s <strong>mean</strong>.</p>
<ul>
<li><code>Min.</code> = the <strong>minimum</strong> value for each variable, so, for example, the youngest subject’s Age was 21.</li>
<li><code>1st Qu.</code> = the <strong>first quartile</strong> (25<sup>th</sup> percentile) for each variable - for example, 25% of the subjects were Age 30 or younger.</li>
<li><code>Median</code> = the <strong>median</strong> (50<sup>th</sup> percentile) - half of the subjects were Age 40 or younger.</li>
<li><code>Mean</code> = the <strong>mean</strong>, usually what one means by an <em>average</em> - the sum of the Ages divided by 750 is 40.8,</li>
<li><code>3rd Qu.</code> = the <strong>third quartile</strong> (75<sup>th</sup> percentile) - 25% of the subjects were Age 51 or older.</li>
<li><code>Max.</code> = the <strong>maximum</strong> value for each variable, so the oldest subject was Age 64.</li>
</ul>
<p>The summary also specifies the number of missing values for each variable. Here, we are missing 5 of the BMI values, for example.</p>
</section>
<section id="measuring-the-center-of-a-distribution" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="measuring-the-center-of-a-distribution"><span class="header-section-number">7.4</span> Measuring the Center of a Distribution</h2>
<section id="the-mean-and-the-median" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="the-mean-and-the-median"><span class="header-section-number">7.4.1</span> The Mean and The Median</h3>
<p>The <strong>mean</strong> and <strong>median</strong> are the most commonly used measures of the center of a distribution for a quantitative variable. The median is the more generally useful value, as it is relevant even if the data have a shape that is not symmetric. We might also collect the <strong>sum</strong> of the observations, and the <strong>count</strong> of the number of observations, usually symbolized with <em>n</em>.</p>
<p>For variables without missing values, like <code>Age</code>, this is pretty straightforward.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">Mean =</span> <span class="fu">mean</span>(Age), <span class="at">Median =</span> <span class="fu">median</span>(Age), <span class="at">Sum =</span> <span class="fu">sum</span>(Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
      n  Mean Median   Sum
  &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1   750  40.8     40 30616</code></pre>
</div>
</div>
<p>And again, the Mean is just the Sum (30616), divided by the number of non-missing values of Age (750), or 40.8213333.</p>
<p>The Median is the middle value when the data are sorted in order. When we have an odd number of values, this is sufficient. When we have an even number, as in this case, we take the mean of the two middle values. We could sort and list all 500 Ages, if we wanted to do so.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span> <span class="fu">select</span>(Age) <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 750 × 1
     Age
   &lt;int&gt;
 1    21
 2    21
 3    21
 4    21
 5    21
 6    21
 7    21
 8    21
 9    21
10    21
# … with 740 more rows</code></pre>
</div>
</div>
<p>But this data set figures we don’t want to output more than 10 observations to a table like this.</p>
<p>If we really want to see all of the data, we can use <code>View(nh_750)</code> to get a spreadsheet-style presentation, or use the <code>sort</code> command…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(nh_750<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 22 22 22
 [26] 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 23 23 23 23 23 23
 [51] 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24 24
 [76] 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25
[101] 25 25 25 26 26 26 26 26 26 26 26 26 26 26 26 26 26 27 27 27 27 27 27 27 27
[126] 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28
[151] 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 29 30 30 30 30 30
[176] 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31
[201] 31 31 31 31 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 32 32
[226] 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 33 33 33 33 33 33 33 33 33
[251] 33 33 33 33 33 33 33 33 33 33 33 33 33 33 33 34 34 34 34 34 34 34 34 34 34
[276] 34 34 34 34 35 35 35 35 35 35 35 35 35 35 35 36 36 36 36 36 36 36 36 36 36
[301] 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37
[326] 37 37 37 37 37 37 37 37 37 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38 38
[351] 39 39 39 39 39 39 39 39 39 39 39 39 39 39 39 39 39 39 39 40 40 40 40 40 40
[376] 40 40 40 40 40 40 40 40 40 40 40 40 41 41 41 41 41 41 41 41 41 41 41 41 41
[401] 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 43 43 43 43 43 43
[426] 43 43 43 43 43 43 43 43 43 43 43 43 44 44 44 44 44 44 44 44 44 44 44 44 44
[451] 44 44 44 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 45 46 46 46 46 46
[476] 46 46 46 46 46 46 46 46 46 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47 47
[501] 47 48 48 48 48 48 48 48 48 48 48 48 49 49 49 49 49 49 49 49 49 49 49 49 49
[526] 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
[551] 50 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 51 52 52 52 52
[576] 52 52 52 52 52 52 52 52 53 53 53 53 53 53 53 53 53 53 53 53 53 53 53 54 54
[601] 54 54 54 54 54 54 54 54 54 54 54 54 54 54 55 55 55 55 55 55 55 55 55 55 56
[626] 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 57 57 57 57 57 57 57
[651] 57 57 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 58 59 59 59 59 59
[676] 59 59 59 59 59 59 59 59 60 60 60 60 60 60 60 60 60 60 60 60 60 61 61 61 61
[701] 61 61 61 61 61 61 61 61 61 61 62 62 62 62 62 62 62 62 62 62 62 62 62 63 63
[726] 63 63 63 63 63 63 63 63 63 63 63 64 64 64 64 64 64 64 64 64 64 64 64 64 64</code></pre>
</div>
</div>
<p>Again, to find the median, we would take the mean of the middle two observations in this sorted data set. That would be the 250<sup>th</sup> and 251<sup>st</sup> largest Ages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(nh_750<span class="sc">$</span>Age)[<span class="dv">250</span><span class="sc">:</span><span class="dv">251</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33 33</code></pre>
</div>
</div>
</section>
<section id="dealing-with-missingness" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="dealing-with-missingness"><span class="header-section-number">7.4.2</span> Dealing with Missingness</h3>
<p>When calculating a mean, you may be tempted to try something like this…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">mean</span>(Pulse), <span class="fu">median</span>(Pulse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `mean(Pulse)` `median(Pulse)`
          &lt;dbl&gt;           &lt;int&gt;
1            NA              NA</code></pre>
</div>
</div>
<p>This fails because we have some missing values in the Pulse data. We can address this by either omitting the data with missing values before we run the <code>summarise()</code> function, or tell the mean and median summary functions to remove missing values<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(Pulse)) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="fu">mean</span>(Pulse), <span class="fu">median</span>(Pulse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  count `mean(Pulse)` `median(Pulse)`
  &lt;int&gt;         &lt;dbl&gt;           &lt;dbl&gt;
1   718          73.5              72</code></pre>
</div>
</div>
<p>Or, we could tell the summary functions themselves to remove NA values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">mean</span>(Pulse, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="fu">median</span>(Pulse, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `mean(Pulse, na.rm = TRUE)` `median(Pulse, na.rm = TRUE)`
                        &lt;dbl&gt;                         &lt;dbl&gt;
1                        73.5                            72</code></pre>
</div>
</div>
<p>In <a href="09-missing_data.html"><span>Chapter&nbsp;9</span></a>, we will discuss various assumptions we can make about missing data, and the importance of <strong>imputation</strong> when dealing with it in modeling or making inferences. For now, we will limit our descriptive summaries to observed values, in what are called complete case or available case analyses.</p>
</section>
<section id="the-mode-of-a-quantitative-variable" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="the-mode-of-a-quantitative-variable"><span class="header-section-number">7.4.3</span> The Mode of a Quantitative Variable</h3>
<p>One other less common measure of the center of a quantitative variable’s distribution is its most frequently observed value, referred to as the <strong>mode</strong>. This measure is only appropriate for discrete variables, be they quantitative or categorical. To find the mode, we usually tabulate the data, and then sort by the counts of the numbers of observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Age) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(count)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 44 × 2
     Age count
   &lt;int&gt; &lt;int&gt;
 1    32    28
 2    36    26
 3    50    26
 4    30    24
 5    33    24
 6    24    23
 7    21    22
 8    22    22
 9    23    22
10    28    20
# … with 34 more rows</code></pre>
</div>
</div>
<p>The mode is just the most common Age observed in the data.</p>
<p>Note the use of three different “verbs” in our function there - for more explanation of this strategy, visit <span class="citation" data-cites="R4DS">Wickham and Grolemund (<a href="references.html#ref-R4DS" role="doc-biblioref">2022</a>)</span>. The <code>group_by</code> function here is very useful. It converts the nh_750 data frame into a new grouped tibble where operations are performed on the groups. Here, this means that it groups the data by Age before counting observations, and then sorting the groups (the Ages) by their frequencies.</p>
<p>As an alternative, the <code>modeest</code> package’s <code>mlv</code> function calculates the sample mode (or most frequent value) <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
</section>
</section>
<section id="measuring-the-spread-of-a-distribution" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="measuring-the-spread-of-a-distribution"><span class="header-section-number">7.5</span> Measuring the Spread of a Distribution</h2>
<p>Statistics is all about variation, so spread or dispersion is an important fundamental concept in statistics. Measures of spread like the inter-quartile range and range (maximum - minimum) can help us understand and compare data sets. If the values in the data are close to the center, the spread will be small. If many of the values in the data are scattered far away from the center, the spread will be large.</p>
<section id="rangeandiqr" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="rangeandiqr"><span class="header-section-number">7.5.1</span> The Range and the Interquartile Range (IQR)</h3>
<p>The <strong>range</strong> of a quantitative variable is sometimes interpreted as the difference between the maximum and the minimum, even though R presents the actual minimum and maximum values when you ask for a range…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Age) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">range</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21 64</code></pre>
</div>
</div>
<p>And, for a variable with missing values, we can use…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(BMI) <span class="sc">|&gt;</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(BMI)) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">range</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.7 80.6</code></pre>
</div>
</div>
<p>A more interesting and useful statistic is the <strong>inter-quartile range</strong>, or IQR, which is the range of the middle half of the distribution, calculated by subtracting the 25<sup>th</sup> percentile value from the 75<sup>th</sup> percentile value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">IQR</span>(Age), <span class="fu">quantile</span>(Age, <span class="fl">0.25</span>), <span class="fu">quantile</span>(Age, <span class="fl">0.75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  `IQR(Age)` `quantile(Age, 0.25)` `quantile(Age, 0.75)`
       &lt;dbl&gt;                 &lt;dbl&gt;                 &lt;dbl&gt;
1         21                    30                    51</code></pre>
</div>
</div>
<p>We can calculate the range and IQR nicely from the summary information on quantiles, of course:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Age             BMI             SBP             DBP        
 Min.   :21.00   Min.   :16.70   Min.   : 83.0   Min.   :  0.00  
 1st Qu.:30.00   1st Qu.:24.20   1st Qu.:108.0   1st Qu.: 66.00  
 Median :40.00   Median :27.90   Median :118.0   Median : 73.00  
 Mean   :40.82   Mean   :29.08   Mean   :118.8   Mean   : 72.69  
 3rd Qu.:51.00   3rd Qu.:32.10   3rd Qu.:127.0   3rd Qu.: 80.00  
 Max.   :64.00   Max.   :80.60   Max.   :209.0   Max.   :108.00  
                 NA's   :5       NA's   :33      NA's   :33      
     Pulse       
 Min.   : 40.00  
 1st Qu.: 66.00  
 Median : 72.00  
 Mean   : 73.53  
 3rd Qu.: 80.00  
 Max.   :124.00  
 NA's   :32      </code></pre>
</div>
</div>
</section>
<section id="the-variance-and-the-standard-deviation" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="the-variance-and-the-standard-deviation"><span class="header-section-number">7.5.2</span> The Variance and the Standard Deviation</h3>
<p>The IQR is always a reasonable summary of spread, just as the median is always a reasonable summary of the center of a distribution. Yet, most people are inclined to summarize a batch of data using two numbers: the <strong>mean</strong> and the <strong>standard deviation</strong>. This is really only a sensible thing to do if you are willing to assume the data follow a Normal distribution: a bell-shaped, symmetric distribution without substantial outliers.</p>
<p>But <strong>most data do not (even approximately) follow a Normal distribution</strong>. Summarizing by the median and quartiles (25th and 75th percentiles) is much more robust, explaining R’s emphasis on them.</p>
</section>
<section id="obtaining-the-variance-and-standard-deviation-in-r" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="obtaining-the-variance-and-standard-deviation-in-r"><span class="header-section-number">7.5.3</span> Obtaining the Variance and Standard Deviation in R</h3>
<p>Here are the variances of the quantitative variables in the <code>nh_750</code> data. Note the need to include <code>na.rm = TRUE</code> to deal with the missing values in some variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise_all</span>(var, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    Age   BMI   SBP   DBP Pulse
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  157.  52.4  229.  128.  136.</code></pre>
</div>
</div>
<p>And here are the standard deviations of those same variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise_all</span>(sd, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    Age   BMI   SBP   DBP Pulse
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  12.5  7.24  15.1  11.3  11.6</code></pre>
</div>
</div>
</section>
<section id="defining-the-variance-and-standard-deviation" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="defining-the-variance-and-standard-deviation"><span class="header-section-number">7.5.4</span> Defining the Variance and Standard Deviation</h3>
<p><span class="citation" data-cites="BockVD">Bock, Velleman, and De Veaux (<a href="references.html#ref-BockVD" role="doc-biblioref">2004</a>)</span> have lots of useful thoughts here, which are lightly edited here.</p>
<p>In thinking about spread, we might consider how far each data value is from the mean. Such a difference is called a <em>deviation</em>. We could just average the deviations, but the positive and negative differences always cancel out, leaving an average deviation of zero, so that’s not helpful. Instead, we <em>square</em> each deviation to obtain non-negative values, and to emphasize larger differences. When we add up these squared deviations and find their mean (almost), this yields the <strong>variance</strong>.</p>
<p><span class="math display">\[
\mbox{Variance} = s^2 = \frac{\Sigma (y - \bar{y})^2}{n-1}
\]</span></p>
<p>Why almost? It would be the mean of the squared deviations only if we divided the sum by <span class="math inline">\(n\)</span>, but instead we divide by <span class="math inline">\(n-1\)</span> because doing so produces an estimate of the true (population) variance that is unbiased<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. If you’re looking for a more intuitive explanation, <a href="http://stats.stackexchange.com/questions/3931/intuitive-explanation-for-dividing-by-n-1-when-calculating-standard-deviation">this Stack Exchange link</a> awaits your attention.</p>
<ul>
<li>To return to the original units of measurement, we take the square root of <span class="math inline">\(s^2\)</span>, and instead work with <span class="math inline">\(s\)</span>, the <strong>standard deviation</strong>, also abbreviated SD.</li>
</ul>
<p><span class="math display">\[
\mbox{Standard Deviation} = s = \sqrt{\frac{\Sigma (y - \bar{y})^2}{n-1}}
\]</span></p>
</section>
<section id="interpreting-the-sd-when-the-data-are-normally-distributed" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="interpreting-the-sd-when-the-data-are-normally-distributed"><span class="header-section-number">7.5.5</span> Interpreting the SD when the data are Normally distributed</h3>
<p>For a set of measurements that follow a Normal distribution, the interval:</p>
<ul>
<li>Mean <span class="math inline">\(\pm\)</span> Standard Deviation contains approximately 68% of the measurements;</li>
<li>Mean <span class="math inline">\(\pm\)</span> 2(Standard Deviation) contains approximately 95% of the measurements;</li>
<li>Mean <span class="math inline">\(\pm\)</span> 3(Standard Deviation) contains approximately all (99.7%) of the measurements.</li>
</ul>
<p>We often refer to the population or process mean of a distribution with <span class="math inline">\(\mu\)</span> and the standard deviation with <span class="math inline">\(\sigma\)</span>, leading to the Figure below.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Empirical_Rule.PNG" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">The Normal Distribution and the Empirical Rule</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>But if the data are not from an approximately Normal distribution, then this Empirical Rule is less helpful.</p>
</section>
<section id="chebyshevs-inequality-one-interpretation-of-the-standard-deviation" class="level3" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="chebyshevs-inequality-one-interpretation-of-the-standard-deviation"><span class="header-section-number">7.5.6</span> Chebyshev’s Inequality: One Interpretation of the Standard Deviation</h3>
<p>Chebyshev’s Inequality tells us that for any distribution, regardless of its relationship to a Normal distribution, no more than 1/k<sup>2</sup> of the distribution’s values can lie more than k standard deviations from the mean. This implies, for instance, that for <strong>any</strong> distribution, at least 75% of the values must lie within two standard deviations of the mean, and at least 89% must lie within three standard deviations of the mean.</p>
<p>Again, most data sets do not follow a Normal distribution. We’ll return to this notion soon. But first, let’s try to draw some pictures that let us get a better understanding of the distribution of our data.</p>
</section>
</section>
<section id="measuring-the-shape-of-a-distribution" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="measuring-the-shape-of-a-distribution"><span class="header-section-number">7.6</span> Measuring the Shape of a Distribution</h2>
<p>When considering the shape of a distribution, one is often interested in three key points.</p>
<ul>
<li>The number of modes in the distribution, which I always assess through plotting the data.</li>
<li>The <strong>skewness</strong>, or symmetry that is present, which I typically assess by looking at a plot of the distribution of the data, but if required to, will summarize with a non-parametric measure of <strong>skewness</strong>, that we will discuss in <a href="10-nnyfs_foundations.html#sec-skew"><span>Section&nbsp;10.13</span></a>.</li>
<li>The <strong>kurtosis</strong>, or heavy-tailedness (outlier-proneness) that is present, usually in comparison to a Normal distribution. Again, this is something I nearly inevitably assess graphically, but there are measures.</li>
</ul>
<p>A Normal distribution has a single mode, is symmetric and, naturally, is neither heavy-tailed nor light-tailed as compared to a Normal distribution (we call this mesokurtic).</p>
<section id="multimodal-vs.-unimodal-distributions" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="multimodal-vs.-unimodal-distributions"><span class="header-section-number">7.6.1</span> Multimodal vs.&nbsp;Unimodal distributions</h3>
<p>A unimodal distribution, on some level, is straightforward. It is a distribution with a single mode, or “peak” in the distribution. Such a distribution may be skewed or symmetric, light-tailed or heavy-tailed. We usually describe as multimodal distributions like the two on the right below, which have multiple local maxima, even though they have just a single global maximum peak.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/modality.PNG" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption class="figure-caption">Unimodal and Multimodal Sketches</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Truly multimodal distributions are usually described that way in terms of shape. For unimodal distributions, skewness and kurtosis become useful ideas.</p>
</section>
<section id="skew" class="level3" data-number="7.6.2">
<h3 data-number="7.6.2" class="anchored" data-anchor-id="skew"><span class="header-section-number">7.6.2</span> Skew</h3>
<p>Whether or not a distribution is approximately symmetric is an important consideration in describing its shape. Graphical assessments are always most useful in this setting, particularly for unimodal data. My favorite measure of skew, or skewness if the data have a single mode, is:</p>
<p><span class="math display">\[
skew_1 = \frac{\mbox{mean} - \mbox{median}}{\mbox{standard deviation}}
\]</span></p>
<ul>
<li>Symmetric distributions generally show values of <span class="math inline">\(skew_1\)</span> near zero. If the distribution is actually symmetric, the mean should be equal to the median.</li>
<li>Distributions with <span class="math inline">\(skew_1\)</span> values above 0.2 in absolute value generally indicate meaningful skew.</li>
<li>Positive skew (mean &gt; median if the data are unimodal) is also referred to as <em>right skew</em>.</li>
<li>Negative skew (mean &lt; median if the data are unimodal) is referred to as <em>left skew</em>.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/negandposskew.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Negative (Left) Skew and Positive (Right) Skew</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="kurtosis" class="level3" data-number="7.6.3">
<h3 data-number="7.6.3" class="anchored" data-anchor-id="kurtosis"><span class="header-section-number">7.6.3</span> Kurtosis</h3>
<p>When we have a unimodal distribution that is symmetric, we will often be interested in the behavior of the tails of the distribution, as compared to a Normal distribution with the same mean and standard deviation. High values of kurtosis measures (and there are several) indicate data which has extreme outliers, or is heavy-tailed.</p>
<ul>
<li>A mesokurtic distribution has similar tail behavior to what we would expect from a Normal distribution.</li>
<li>A leptokurtic distribution is a thinner, more slender distribution, with heavier tails than we’d expect from a Normal distribution. One example is the t distribution.</li>
<li>A platykurtic distribution is a broader, flatter distribution, with thinner tails than we’d expect from a Normal distribution. One example is a uniform distribution.</li>
</ul>
<p>The visualization below (shown after the code) displays these three types of distributions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">431</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sims_kurt <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">meso =</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">300</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">lepto =</span> <span class="fu">rt</span>(<span class="at">n =</span> <span class="dv">300</span>, <span class="at">df =</span> <span class="dv">4</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">platy =</span> <span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">300</span>, <span class="at">min =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">max =</span> <span class="dv">2</span>))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> meso)) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(density)), </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"royalblue"</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sims_kurt<span class="sc">$</span>meso), </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fu">sd</span>(sims_kurt<span class="sc">$</span>meso)),</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal (mesokurtic)"</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>p1a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> meso, <span class="at">y =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"royalblue"</span>, <span class="at">outlier.color =</span> <span class="st">"royalblue"</span>, <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">""</span>, <span class="at">x =</span> <span class="st">"Normal (mesokurtic)"</span>)</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> lepto)) <span class="sc">+</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(density)), </span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"tomato"</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, </span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sims_kurt<span class="sc">$</span>lepto), </span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fu">sd</span>(sims_kurt<span class="sc">$</span>lepto)),</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"royalblue"</span>) <span class="sc">+</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"t (leptokurtic)"</span>)</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>p2a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> lepto, <span class="at">y =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"tomato"</span>, <span class="at">outlier.color =</span> <span class="st">"tomato"</span>, <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">""</span>, <span class="at">x =</span> <span class="st">"t (slender with heavy tails)"</span>)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> platy)) <span class="sc">+</span></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(density)), </span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">25</span>, <span class="at">fill =</span> <span class="st">"yellow"</span>, <span class="at">col =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, </span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(sims_kurt<span class="sc">$</span>platy), </span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fu">sd</span>(sims_kurt<span class="sc">$</span>platy)),</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"royalblue"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Uniform (platykurtic)"</span>)</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a>p3a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sims_kurt, <span class="fu">aes</span>(<span class="at">x =</span> platy, <span class="at">y =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"yellow"</span>, <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">""</span>, <span class="at">x =</span> <span class="st">"Uniform (broad with thin tails)"</span>)</span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-50"><a href="#cb33-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-51"><a href="#cb33-51" aria-hidden="true" tabindex="-1"></a>(p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3) <span class="sc">/</span> (p1a <span class="sc">+</span> p2a <span class="sc">+</span> p3a) <span class="sc">+</span> </span>
<span id="cb33-52"><a href="#cb33-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_layout</span>(<span class="at">heights =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-summarizing_quantities_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Graphical tools are in most cases the best way to identify issues related to kurtosis, and we usually only focus on kurtosis if we are willing to assume symmetry (or at least lack of meaningful skew) in our data.</p>
</section>
</section>
<section id="multiple-summaries-at-once" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="multiple-summaries-at-once"><span class="header-section-number">7.7</span> Multiple Summaries at once</h2>
<section id="favstats-from-the-mosaic-package" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="favstats-from-the-mosaic-package"><span class="header-section-number">7.7.1</span> <code>favstats()</code> from the mosaic package</h3>
<p>The <code>favstats</code> function adds the standard deviation, and counts of overall and missing observations to our usual <code>summary</code> for a continuous variable. Let’s look at systolic blood pressure, because we haven’t yet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(<span class="sc">~</span> SBP, <span class="at">data =</span> nh_750)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min  Q1 median  Q3 max     mean       sd   n missing
  83 108    118 127 209 118.7908 15.14329 717      33</code></pre>
</div>
</div>
<p>We could, of course, duplicate these results with several <code>summarise()</code> pieces…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(SBP)) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">min =</span> <span class="fu">min</span>(SBP), <span class="at">Q1 =</span> <span class="fu">quantile</span>(SBP, <span class="fl">0.25</span>), </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">median =</span> <span class="fu">median</span>(SBP), <span class="at">Q3 =</span> <span class="fu">quantile</span>(SBP, <span class="fl">0.75</span>), </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">max =</span> <span class="fu">max</span>(SBP),  <span class="at">mean =</span> <span class="fu">mean</span>(SBP), </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd =</span> <span class="fu">sd</span>(SBP), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">miss =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(SBP))) <span class="sc">|&gt;</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> Q1 </th>
   <th style="text-align:right;"> median </th>
   <th style="text-align:right;"> Q3 </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> miss </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 83 </td>
   <td style="text-align:right;"> 108 </td>
   <td style="text-align:right;"> 118 </td>
   <td style="text-align:right;"> 127 </td>
   <td style="text-align:right;"> 209 </td>
   <td style="text-align:right;"> 118.79 </td>
   <td style="text-align:right;"> 15.14 </td>
   <td style="text-align:right;"> 717 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The somewhat unusual structure of <code>favstats</code> (complete with an easy to forget <code>~</code>) is actually helpful. It allows you to look at some interesting grouping approaches, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(SBP <span class="sc">~</span> Education, <span class="at">data =</span> nh_750)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Education min     Q1 median     Q3 max     mean       sd   n missing
1      8th Grade  96 110.25  119.5 129.75 167 122.4565 16.34993  46       4
2 9 - 11th Grade  85 107.75  116.0 127.00 191 118.8026 15.79453  76       0
3    High School  84 111.50  120.5 129.00 209 121.0882 16.52853 136       7
4   Some College  85 108.00  117.0 126.00 186 118.6293 14.32736 232       9
5   College Grad  83 107.00  117.0 125.00 171 116.8326 14.41202 227      13</code></pre>
</div>
</div>
<p>Of course, we could accomplish the same comparison with <code>dplyr</code> commands, too, but the <code>favstats</code> approach has much to offer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(SBP, Education)) <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Education) <span class="sc">|&gt;</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">min =</span> <span class="fu">min</span>(SBP), <span class="at">Q1 =</span> <span class="fu">quantile</span>(SBP, <span class="fl">0.25</span>), </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">median =</span> <span class="fu">median</span>(SBP), <span class="at">Q3 =</span> <span class="fu">quantile</span>(SBP, <span class="fl">0.75</span>), </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">max =</span> <span class="fu">max</span>(SBP), <span class="at">mean =</span> <span class="fu">mean</span>(SBP), </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd =</span> <span class="fu">sd</span>(SBP), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">miss =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(SBP))) <span class="sc">|&gt;</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Education </th>
   <th style="text-align:right;"> min </th>
   <th style="text-align:right;"> Q1 </th>
   <th style="text-align:right;"> median </th>
   <th style="text-align:right;"> Q3 </th>
   <th style="text-align:right;"> max </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> miss </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 8th Grade </td>
   <td style="text-align:right;"> 96 </td>
   <td style="text-align:right;"> 110.25 </td>
   <td style="text-align:right;"> 119.5 </td>
   <td style="text-align:right;"> 129.75 </td>
   <td style="text-align:right;"> 167 </td>
   <td style="text-align:right;"> 122.46 </td>
   <td style="text-align:right;"> 16.35 </td>
   <td style="text-align:right;"> 46 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 - 11th Grade </td>
   <td style="text-align:right;"> 85 </td>
   <td style="text-align:right;"> 107.75 </td>
   <td style="text-align:right;"> 116.0 </td>
   <td style="text-align:right;"> 127.00 </td>
   <td style="text-align:right;"> 191 </td>
   <td style="text-align:right;"> 118.80 </td>
   <td style="text-align:right;"> 15.79 </td>
   <td style="text-align:right;"> 76 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> High School </td>
   <td style="text-align:right;"> 84 </td>
   <td style="text-align:right;"> 111.50 </td>
   <td style="text-align:right;"> 120.5 </td>
   <td style="text-align:right;"> 129.00 </td>
   <td style="text-align:right;"> 209 </td>
   <td style="text-align:right;"> 121.09 </td>
   <td style="text-align:right;"> 16.53 </td>
   <td style="text-align:right;"> 136 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Some College </td>
   <td style="text-align:right;"> 85 </td>
   <td style="text-align:right;"> 108.00 </td>
   <td style="text-align:right;"> 117.0 </td>
   <td style="text-align:right;"> 126.00 </td>
   <td style="text-align:right;"> 186 </td>
   <td style="text-align:right;"> 118.63 </td>
   <td style="text-align:right;"> 14.33 </td>
   <td style="text-align:right;"> 232 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> College Grad </td>
   <td style="text-align:right;"> 83 </td>
   <td style="text-align:right;"> 107.00 </td>
   <td style="text-align:right;"> 117.0 </td>
   <td style="text-align:right;"> 125.00 </td>
   <td style="text-align:right;"> 171 </td>
   <td style="text-align:right;"> 116.83 </td>
   <td style="text-align:right;"> 14.41 </td>
   <td style="text-align:right;"> 227 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="using-descr-from-summarytools" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="using-descr-from-summarytools"><span class="header-section-number">7.7.2</span> Using <code>descr()</code> from <code>summarytools</code></h3>
<p>The <code>descr()</code> function from the <code>summarytools</code> package produces numerous numerical summaries for quantities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">descr</span>() <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Age </th>
   <th style="text-align:right;"> BMI </th>
   <th style="text-align:right;"> DBP </th>
   <th style="text-align:right;"> Pulse </th>
   <th style="text-align:right;"> SBP </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mean </td>
   <td style="text-align:right;"> 40.82 </td>
   <td style="text-align:right;"> 29.08 </td>
   <td style="text-align:right;"> 72.69 </td>
   <td style="text-align:right;"> 73.53 </td>
   <td style="text-align:right;"> 118.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Std.Dev </td>
   <td style="text-align:right;"> 12.54 </td>
   <td style="text-align:right;"> 7.24 </td>
   <td style="text-align:right;"> 11.34 </td>
   <td style="text-align:right;"> 11.65 </td>
   <td style="text-align:right;"> 15.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Min </td>
   <td style="text-align:right;"> 21.00 </td>
   <td style="text-align:right;"> 16.70 </td>
   <td style="text-align:right;"> 0.00 </td>
   <td style="text-align:right;"> 40.00 </td>
   <td style="text-align:right;"> 83.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Q1 </td>
   <td style="text-align:right;"> 30.00 </td>
   <td style="text-align:right;"> 24.20 </td>
   <td style="text-align:right;"> 66.00 </td>
   <td style="text-align:right;"> 66.00 </td>
   <td style="text-align:right;"> 108.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Median </td>
   <td style="text-align:right;"> 40.00 </td>
   <td style="text-align:right;"> 27.90 </td>
   <td style="text-align:right;"> 73.00 </td>
   <td style="text-align:right;"> 72.00 </td>
   <td style="text-align:right;"> 118.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Q3 </td>
   <td style="text-align:right;"> 51.00 </td>
   <td style="text-align:right;"> 32.10 </td>
   <td style="text-align:right;"> 80.00 </td>
   <td style="text-align:right;"> 80.00 </td>
   <td style="text-align:right;"> 127.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Max </td>
   <td style="text-align:right;"> 64.00 </td>
   <td style="text-align:right;"> 80.60 </td>
   <td style="text-align:right;"> 108.00 </td>
   <td style="text-align:right;"> 124.00 </td>
   <td style="text-align:right;"> 209.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MAD </td>
   <td style="text-align:right;"> 14.83 </td>
   <td style="text-align:right;"> 5.93 </td>
   <td style="text-align:right;"> 10.38 </td>
   <td style="text-align:right;"> 11.86 </td>
   <td style="text-align:right;"> 13.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQR </td>
   <td style="text-align:right;"> 21.00 </td>
   <td style="text-align:right;"> 7.90 </td>
   <td style="text-align:right;"> 14.00 </td>
   <td style="text-align:right;"> 14.00 </td>
   <td style="text-align:right;"> 19.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> CV </td>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:right;"> 0.25 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Skewness </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 1.72 </td>
   <td style="text-align:right;"> -0.28 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SE.Skewness </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.09 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Kurtosis </td>
   <td style="text-align:right;"> -1.15 </td>
   <td style="text-align:right;"> 6.16 </td>
   <td style="text-align:right;"> 2.59 </td>
   <td style="text-align:right;"> 0.73 </td>
   <td style="text-align:right;"> 3.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> N.Valid </td>
   <td style="text-align:right;"> 750.00 </td>
   <td style="text-align:right;"> 745.00 </td>
   <td style="text-align:right;"> 717.00 </td>
   <td style="text-align:right;"> 718.00 </td>
   <td style="text-align:right;"> 717.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Pct.Valid </td>
   <td style="text-align:right;"> 100.00 </td>
   <td style="text-align:right;"> 99.33 </td>
   <td style="text-align:right;"> 95.60 </td>
   <td style="text-align:right;"> 95.73 </td>
   <td style="text-align:right;"> 95.60 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The additional statistics presented here are:</p>
<ul>
<li><code>MAD</code> = the median absolute deviation (from the median), which can be used in a manner similar to the standard deviation or IQR to measure spread.
<ul>
<li>If the data are <span class="math inline">\(Y_1, Y_2, ..., Y_n\)</span>, then the <code>MAD</code> is defined as <span class="math inline">\(median(|Y_i - median(Y_i)|)\)</span>.</li>
<li>To find the <code>MAD</code> for a set of numbers, find the median, subtract the median from each value and find the absolute value of that difference, and then find the median of those absolute differences.</li>
<li>For non-normal data with a skewed shape but tails well approximated by the Normal, the <code>MAD</code> is likely to be a better (more robust) estimate of the spread than is the standard deviation.</li>
</ul></li>
<li><code>CV</code> = the coefficient of variation, or the standard deviation divided by the mean</li>
<li>a measure of <code>Skewness</code> and its standard error. This Skewness measure refers to how much asymmetry is present in the shape of the distribution. The measure is not the same as the <em>nonparametric skew</em> measure that we will usually prefer and that we discuss further in <a href="10-nnyfs_foundations.html#sec-skew"><span>Section&nbsp;10.13</span></a>.</li>
<li>Our nonparametric skew measure is just the difference between the mean and the median, divided by the standard deviation.</li>
<li>The <a href="https://en.wikipedia.org/wiki/Skewness">Wikipedia page on skewness</a> is very detailed.</li>
<li>a measure of <code>Kurtosis</code>, which refers to how outlier-prone, or heavy-tailed the shape of the distribution is, as compared to a Normal distribution.</li>
<li>the number of valid (non-missing) observations in each variable.</li>
</ul>
<p>Recall that in <a href="03-penguins2.html"><span>Chapter&nbsp;3</span></a>, we saw the use of an adjustment to show only “common” summaries. We can pick and choose from the entire list of available summaries. See the <a href="https://cran.r-project.org/web/packages/summarytools/vignettes/introduction.html">summarytools package vignette</a> for more details.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">descr</span>(<span class="at">stats =</span> <span class="st">"common"</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Age </th>
   <th style="text-align:right;"> BMI </th>
   <th style="text-align:right;"> DBP </th>
   <th style="text-align:right;"> Pulse </th>
   <th style="text-align:right;"> SBP </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mean </td>
   <td style="text-align:right;"> 40.82 </td>
   <td style="text-align:right;"> 29.08 </td>
   <td style="text-align:right;"> 72.69 </td>
   <td style="text-align:right;"> 73.53 </td>
   <td style="text-align:right;"> 118.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Std.Dev </td>
   <td style="text-align:right;"> 12.54 </td>
   <td style="text-align:right;"> 7.24 </td>
   <td style="text-align:right;"> 11.34 </td>
   <td style="text-align:right;"> 11.65 </td>
   <td style="text-align:right;"> 15.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Min </td>
   <td style="text-align:right;"> 21.00 </td>
   <td style="text-align:right;"> 16.70 </td>
   <td style="text-align:right;"> 0.00 </td>
   <td style="text-align:right;"> 40.00 </td>
   <td style="text-align:right;"> 83.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Median </td>
   <td style="text-align:right;"> 40.00 </td>
   <td style="text-align:right;"> 27.90 </td>
   <td style="text-align:right;"> 73.00 </td>
   <td style="text-align:right;"> 72.00 </td>
   <td style="text-align:right;"> 118.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Max </td>
   <td style="text-align:right;"> 64.00 </td>
   <td style="text-align:right;"> 80.60 </td>
   <td style="text-align:right;"> 108.00 </td>
   <td style="text-align:right;"> 124.00 </td>
   <td style="text-align:right;"> 209.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> N.Valid </td>
   <td style="text-align:right;"> 750.00 </td>
   <td style="text-align:right;"> 745.00 </td>
   <td style="text-align:right;"> 717.00 </td>
   <td style="text-align:right;"> 718.00 </td>
   <td style="text-align:right;"> 717.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Pct.Valid </td>
   <td style="text-align:right;"> 100.00 </td>
   <td style="text-align:right;"> 99.33 </td>
   <td style="text-align:right;"> 95.60 </td>
   <td style="text-align:right;"> 95.73 </td>
   <td style="text-align:right;"> 95.60 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="describe-in-the-psych-package" class="level3" data-number="7.7.3">
<h3 data-number="7.7.3" class="anchored" data-anchor-id="describe-in-the-psych-package"><span class="header-section-number">7.7.3</span> <code>describe</code> in the <code>psych</code> package</h3>
<p>The <code>psych</code> package has an even more detailed list of numerical summaries for quantitative variables that lets us look at a group of observations at once.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(nh_750 <span class="sc">|&gt;</span> <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      vars   n   mean    sd median trimmed   mad  min   max range  skew
Age      1 750  40.82 12.54   40.0   40.53 14.83 21.0  64.0  43.0  0.16
BMI      2 745  29.08  7.24   27.9   28.31  5.93 16.7  80.6  63.9  1.72
SBP      3 717 118.79 15.14  118.0  117.88 13.34 83.0 209.0 126.0  0.96
DBP      4 717  72.69 11.34   73.0   72.65 10.38  0.0 108.0 108.0 -0.28
Pulse    5 718  73.53 11.65   72.0   73.11 11.86 40.0 124.0  84.0  0.48
      kurtosis   se
Age      -1.15 0.46
BMI       6.16 0.27
SBP       3.10 0.57
DBP       2.59 0.42
Pulse     0.73 0.43</code></pre>
</div>
</div>
<p>The additional statistics presented here, beyond those discussed previously, are:</p>
<ul>
<li><code>trimmed</code> = a trimmed mean (by default in this function, this removes the top and bottom 10% from the data, then computes the mean of the remaining values - the middle 80% of the full data set.)</li>
<li><code>se</code> = the standard error of the sample mean, equal to the sample sd divided by the square root of the sample size.</li>
</ul>
</section>
<section id="the-hmisc-packages-version-of-describe" class="level3" data-number="7.7.4">
<h3 data-number="7.7.4" class="anchored" data-anchor-id="the-hmisc-packages-version-of-describe"><span class="header-section-number">7.7.4</span> The <code>Hmisc</code> package’s version of <code>describe</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(nh_750 <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>select(nh_750, Age, BMI, SBP, DBP, Pulse) 

 5  Variables      750  Observations
--------------------------------------------------------------------------------
Age 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     750        0       44    0.999    40.82    14.46       22       24 
     .25      .50      .75      .90      .95 
      30       40       51       59       62 

lowest : 21 22 23 24 25, highest: 60 61 62 63 64
--------------------------------------------------------------------------------
BMI 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     745        5      250        1    29.08    7.538    20.22    21.30 
     .25      .50      .75      .90      .95 
   24.20    27.90    32.10    37.60    41.28 

lowest : 16.7 17.6 17.8 17.9 18.0, highest: 59.1 62.8 63.3 69.0 80.6
--------------------------------------------------------------------------------
SBP 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     717       33       81    0.999    118.8    16.36     98.0    102.0 
     .25      .50      .75      .90      .95 
   108.0    118.0    127.0    137.0    144.2 

lowest :  83  84  85  86  89, highest: 171 179 186 191 209
--------------------------------------------------------------------------------
DBP 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     717       33       66    0.999    72.69    12.43       55       59 
     .25      .50      .75      .90      .95 
      66       73       80       86       91 

lowest :   0  25  41  42  44, highest: 104 105 106 107 108
--------------------------------------------------------------------------------
Pulse 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
     718       32       37    0.997    73.53    12.95       56       60 
     .25      .50      .75      .90      .95 
      66       72       80       88       94 

lowest :  40  44  46  48  50, highest: 108 112 114 118 124
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>The <code>Hmisc</code> package’s version of <code>describe</code> for a distribution of data presents three new ideas, in addition to a more comprehensive list of quartiles (the 5<sup>th</sup>, 10<sup>th</sup>, 25<sup>th</sup>, 50<sup>th</sup>, 75<sup>th</sup>, 90<sup>th</sup> and 95<sup>th</sup> are shown) and the lowest and highest few observations. These are:</p>
<ul>
<li><code>distinct</code> - the number of different values observed in the data.</li>
<li><code>Info</code> - a measure of how “continuous” the variable is, related to how many “ties” there are in the data, with Info taking a higher value (closer to its maximum of one) if the data are more continuous.</li>
<li><code>Gmd</code> - the Gini mean difference - a robust measure of spread that is calculated as the mean absolute difference between any pairs of observations. Larger values of Gmd indicate more spread-out distributions. (Gini is usually pronounced as “Genie”.)</li>
</ul>
</section>
<section id="using-tbl_summary-from-gtsummary" class="level3" data-number="7.7.5">
<h3 data-number="7.7.5" class="anchored" data-anchor-id="using-tbl_summary-from-gtsummary"><span class="header-section-number">7.7.5</span> Using tbl_summary() from <code>gtsummary</code></h3>
<p>If you want to produce results which look like you might expect to see in a published paper, the <code>tbl_summary()</code> function from the <code>gtsummary</code> package has many nice features. Here, we’ll just show the medians, and 25th and 75th percentiles. Recall that we looked at some other options for this tool back in <a href="03-penguins2.html"><span>Chapter&nbsp;3</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>nh_750 <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Age, BMI, SBP, DBP, Pulse) <span class="sc">|&gt;</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="gxrlqtrvxj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#gxrlqtrvxj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gxrlqtrvxj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gxrlqtrvxj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gxrlqtrvxj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gxrlqtrvxj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gxrlqtrvxj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gxrlqtrvxj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gxrlqtrvxj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gxrlqtrvxj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gxrlqtrvxj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gxrlqtrvxj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gxrlqtrvxj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#gxrlqtrvxj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gxrlqtrvxj .gt_from_md > :first-child {
  margin-top: 0;
}

#gxrlqtrvxj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gxrlqtrvxj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gxrlqtrvxj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#gxrlqtrvxj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#gxrlqtrvxj .gt_row_group_first td {
  border-top-width: 2px;
}

#gxrlqtrvxj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gxrlqtrvxj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#gxrlqtrvxj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#gxrlqtrvxj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gxrlqtrvxj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gxrlqtrvxj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gxrlqtrvxj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gxrlqtrvxj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gxrlqtrvxj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gxrlqtrvxj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gxrlqtrvxj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gxrlqtrvxj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#gxrlqtrvxj .gt_left {
  text-align: left;
}

#gxrlqtrvxj .gt_center {
  text-align: center;
}

#gxrlqtrvxj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gxrlqtrvxj .gt_font_normal {
  font-weight: normal;
}

#gxrlqtrvxj .gt_font_bold {
  font-weight: bold;
}

#gxrlqtrvxj .gt_font_italic {
  font-style: italic;
}

#gxrlqtrvxj .gt_super {
  font-size: 65%;
}

#gxrlqtrvxj .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#gxrlqtrvxj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#gxrlqtrvxj .gt_indent_1 {
  text-indent: 5px;
}

#gxrlqtrvxj .gt_indent_2 {
  text-indent: 10px;
}

#gxrlqtrvxj .gt_indent_3 {
  text-indent: 15px;
}

#gxrlqtrvxj .gt_indent_4 {
  text-indent: 20px;
}

#gxrlqtrvxj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>N = 750</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Age</td>
<td class="gt_row gt_center">40 (30, 51)</td></tr>
    <tr><td class="gt_row gt_left">BMI</td>
<td class="gt_row gt_center">28 (24, 32)</td></tr>
    <tr><td class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center">5</td></tr>
    <tr><td class="gt_row gt_left">SBP</td>
<td class="gt_row gt_center">118 (108, 127)</td></tr>
    <tr><td class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center">33</td></tr>
    <tr><td class="gt_row gt_left">DBP</td>
<td class="gt_row gt_center">73 (66, 80)</td></tr>
    <tr><td class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center">33</td></tr>
    <tr><td class="gt_row gt_left">Pulse</td>
<td class="gt_row gt_center">72 (66, 80)</td></tr>
    <tr><td class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td class="gt_row gt_center">32</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><sup class="gt_footnote_marks">1</sup> Median (IQR)</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</section>
<section id="some-other-options" class="level3" data-number="7.7.6">
<h3 data-number="7.7.6" class="anchored" data-anchor-id="some-other-options"><span class="header-section-number">7.7.6</span> Some Other Options</h3>
<p>You’ll recall that in our discussion of the Palmer Penguins, back in <a href="03-penguins2.html"><span>Chapter&nbsp;3</span></a>, we used several other strategies to develop graphical and numerical summaries of quantities, and all of those approaches could be used here, too.</p>
<ul>
<li>The <a href="https://boxuancui.github.io/DataExplorer/"><code>DataExplorer</code></a> package can be used for more automated exploratory data analyses.</li>
<li>Some people also like <a href="https://github.com/ropensci/skimr"><code>skimr</code></a> which has some similar goals.</li>
</ul>
<p>Next, we’ll focus on a few tools for summarizing categorical information.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-BockVD" class="csl-entry" role="doc-biblioentry">
Bock, David E., Paul F. Velleman, and Richard D. De Veaux. 2004. <em>Stats: Modelling the World</em>. Boston <span>MA</span>: Pearson Addison-Wesley.
</div>
<div id="ref-R4DS" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, and Garrett Grolemund. 2022. <em>R for Data Science</em>. Second. O’Reilly. <a href="https://r4ds.hadley.nz/">https://r4ds.hadley.nz/</a>.
</div>
</div>
</section>
</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1" role="doc-endnote"><p>The quantiles (sometimes referred to as percentiles) can also be summarized with a boxplot.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>We could also use <code>!is.na</code> in place of <code>complete.cases</code> to accomplish the same thing.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>See the documentation for the <code>modeest</code> package’s <code>mlv</code> function to look at other definitions of the mode.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>When we divide by n-1 as we calculate the sample variance, the average of the sample variances for all possible samples is equal to the population variance. If we instead divided by n, the average sample variance across all possible samples would be a little smaller than the population variance.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-nhanes_cc.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-summarizing_categories.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>