<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notes for 431 - 14&nbsp; Dehydration Recovery</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-wcgs.html" rel="next">
<link href="./13-crabs.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">NHANES: A First Look</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Structures, Variable Types &amp; Sampling NHANES</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Visualizing NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assessingnormality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-hydrate.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-regr_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-prediction_wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">14.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"> <span class="header-section-number">14.2</span> The Data</a></li>
  <li><a href="#a-scatterplot-matrix" id="toc-a-scatterplot-matrix" class="nav-link" data-scroll-target="#a-scatterplot-matrix"> <span class="header-section-number">14.3</span> A Scatterplot Matrix</a></li>
  <li><a href="#are-the-recovery-scores-well-described-by-a-normal-model" id="toc-are-the-recovery-scores-well-described-by-a-normal-model" class="nav-link" data-scroll-target="#are-the-recovery-scores-well-described-by-a-normal-model"> <span class="header-section-number">14.4</span> Are the recovery scores well described by a Normal model?</a></li>
  <li><a href="#simple-regression-using-dose-to-predict-recovery" id="toc-simple-regression-using-dose-to-predict-recovery" class="nav-link" data-scroll-target="#simple-regression-using-dose-to-predict-recovery"> <span class="header-section-number">14.5</span> Simple Regression: Using Dose to predict Recovery</a></li>
  <li><a href="#the-scatterplot-with-fitted-linear-model" id="toc-the-scatterplot-with-fitted-linear-model" class="nav-link" data-scroll-target="#the-scatterplot-with-fitted-linear-model"> <span class="header-section-number">14.6</span> The Scatterplot, with fitted Linear Model</a></li>
  <li><a href="#the-fitted-linear-model" id="toc-the-fitted-linear-model" class="nav-link" data-scroll-target="#the-fitted-linear-model"> <span class="header-section-number">14.7</span> The Fitted Linear Model</a>
  <ul class="collapse">
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"> <span class="header-section-number">14.7.1</span> Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#coefficient-plots" id="toc-coefficient-plots" class="nav-link" data-scroll-target="#coefficient-plots"> <span class="header-section-number">14.8</span> Coefficient Plots</a></li>
  <li><a href="#the-summary-output" id="toc-the-summary-output" class="nav-link" data-scroll-target="#the-summary-output"> <span class="header-section-number">14.9</span> The Summary Output</a>
  <ul class="collapse">
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification"> <span class="header-section-number">14.9.1</span> Model Specification</a></li>
  <li><a href="#residual-summary" id="toc-residual-summary" class="nav-link" data-scroll-target="#residual-summary"> <span class="header-section-number">14.9.2</span> Residual Summary</a></li>
  <li><a href="#coefficients-output" id="toc-coefficients-output" class="nav-link" data-scroll-target="#coefficients-output"> <span class="header-section-number">14.9.3</span> Coefficients Output</a></li>
  <li><a href="#correlation-and-slope" id="toc-correlation-and-slope" class="nav-link" data-scroll-target="#correlation-and-slope"> <span class="header-section-number">14.9.4</span> Correlation and Slope</a></li>
  <li><a href="#coefficient-testing" id="toc-coefficient-testing" class="nav-link" data-scroll-target="#coefficient-testing"> <span class="header-section-number">14.9.5</span> Coefficient Testing</a></li>
  <li><a href="#summarizing-the-quality-of-fit" id="toc-summarizing-the-quality-of-fit" class="nav-link" data-scroll-target="#summarizing-the-quality-of-fit"> <span class="header-section-number">14.9.6</span> Summarizing the Quality of Fit</a></li>
  <li><a href="#anova-f-test" id="toc-anova-f-test" class="nav-link" data-scroll-target="#anova-f-test"> <span class="header-section-number">14.9.7</span> ANOVA F test</a></li>
  </ul></li>
  <li><a href="#viewing-the-complete-anova-table" id="toc-viewing-the-complete-anova-table" class="nav-link" data-scroll-target="#viewing-the-complete-anova-table"> <span class="header-section-number">14.10</span> Viewing the complete ANOVA table</a></li>
  <li><a href="#using-glance-to-summarize-the-models-fit" id="toc-using-glance-to-summarize-the-models-fit" class="nav-link" data-scroll-target="#using-glance-to-summarize-the-models-fit"> <span class="header-section-number">14.11</span> Using <code>glance</code> to summarize the model’s fit</a></li>
  <li><a href="#plotting-residuals-vs.-fitted-values" id="toc-plotting-residuals-vs.-fitted-values" class="nav-link" data-scroll-target="#plotting-residuals-vs.-fitted-values"> <span class="header-section-number">14.12</span> Plotting Residuals vs.&nbsp;Fitted Values</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="Hydrate-Study" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="setup-packages-used-here" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">14.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will also use the <code>ggpairs</code> function from the <code>GGally</code> package, and the <code>favstats</code> function from the <code>mosaic</code> package.</p>
</section>
<section id="the-data" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">14.2</span> The Data</h2>
<p>The <code>hydrate</code> data describe the degree of recovery that takes place 90 minutes following treatment of moderate to severe dehydration, for 36 children diagnosed at a hospital’s main pediatric clinic.</p>
<p>Upon diagnosis and study entry, patients were treated with an electrolytic solution at one of seven <code>dose</code> levels (0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0 mEq/l) in a frozen, flavored, ice popsicle. The degree of rehydration was determined using a subjective scale based on physical examination and parental input, converted to a 0 to 100 point scale, representing the percent of recovery (<code>recov.score</code>). Each child’s <code>age</code> (in years) and <code>weight</code> (in pounds) are also available.</p>
<p>First, we’ll check ranges (and for missing data) in the <code>hydrate</code> file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hydrate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/hydrate.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hydrate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id         recov.score          dose            age        
 Min.   : 1.00   Min.   : 44.00   Min.   :0.000   Min.   : 3.000  
 1st Qu.: 9.75   1st Qu.: 61.50   1st Qu.:1.000   1st Qu.: 5.000  
 Median :18.50   Median : 71.50   Median :1.500   Median : 6.500  
 Mean   :18.50   Mean   : 71.56   Mean   :1.569   Mean   : 6.667  
 3rd Qu.:27.25   3rd Qu.: 80.00   3rd Qu.:2.500   3rd Qu.: 8.000  
 Max.   :36.00   Max.   :100.00   Max.   :3.000   Max.   :11.000  
     weight     
 Min.   :22.00  
 1st Qu.:34.50  
 Median :47.50  
 Mean   :46.89  
 3rd Qu.:57.25  
 Max.   :76.00  </code></pre>
</div>
</div>
<p>There are no missing values, and all of the ranges make sense. There are no especially egregious problems to report.</p>
</section>
<section id="a-scatterplot-matrix" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="a-scatterplot-matrix"><span class="header-section-number">14.3</span> A Scatterplot Matrix</h2>
<p>Next, we’ll use a scatterplot matrix to summarize relationships between the outcome <code>recov.score</code> and the key predictor <code>dose</code> as well as the ancillary predictors <code>age</code> and <code>weight</code>, which are of less interest, but are expected to be related to our outcome. The one below uses the <code>ggpairs</code> function in the <code>GGally</code> package, as introduced in Part A of the Notes. We place the outcome in the bottom row, and the key predictor immediately above it, with <code>age</code> and <code>weight</code> in the top rows, using the <code>select</code> function within the `<code>ggpairs</code> call.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(hydrate, age, weight, dose, recov.score), </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">title =</span> <span class="st">"Scatterplot Matrix for hydrate data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What can we conclude here?</p>
<ul>
<li>It looks like <code>recov.score</code> has a moderately strong negative relationship with both <code>age</code> and <code>weight</code> (with correlations in each case around -0.5), but a positive relationship with <code>dose</code> (correlation = 0.36).</li>
<li>The distribution of <code>recov.score</code> looks to be pretty close to Normal. No potential predictors (<code>age</code>, <code>weight</code> and <code>dose</code>) show substantial non-Normality.</li>
<li><code>age</code> and <code>weight</code>, as we’d expect, show a very strong and positive linear relationship, with <em>r</em> = 0.94</li>
<li>Neither <code>age</code> nor <code>weight</code> shows a meaningful relationship with <code>dose</code>. (<em>r</em> = 0.16)</li>
</ul>
</section>
<section id="are-the-recovery-scores-well-described-by-a-normal-model" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="are-the-recovery-scores-well-described-by-a-normal-model"><span class="header-section-number">14.4</span> Are the recovery scores well described by a Normal model?</h2>
<p>Next, we’ll do a more thorough graphical summary of our outcome, recovery score.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(hydrate, <span class="fu">aes</span>(<span class="at">sample =</span> recov.score)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>(<span class="at">col =</span> <span class="st">'#440154'</span>) <span class="sc">+</span> <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Q-Q plot: hydrate"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(hydrate, <span class="fu">aes</span>(<span class="at">x =</span> recov.score)) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(density)), </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">'#440154'</span>, <span class="at">col =</span> <span class="st">'#FDE725'</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(hydrate<span class="sc">$</span>recov.score), </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="fu">sd</span>(hydrate<span class="sc">$</span>recov.score)),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Function: hydrate"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(hydrate, <span class="fu">aes</span>(<span class="at">x =</span> recov.score, <span class="at">y =</span> <span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">'#440154'</span>, <span class="at">outlier.color =</span> <span class="st">'#440154'</span>) <span class="sc">+</span> </span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot: hydrate"</span>, <span class="at">y =</span> <span class="st">""</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> (p2 <span class="sc">/</span> p3 <span class="sc">+</span> <span class="fu">plot_layout</span>(<span class="at">heights =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">1</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(<span class="sc">~</span> recov.score, <span class="at">data =</span> hydrate) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">61.5</td>
<td style="text-align: right;">71.5</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">71.6</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>I see no serious problems with assuming Normality for these recovery scores. Our outcome variable doesn’t in any way <em>need</em> to follow a Normal distribution, but it’s nice when it does, because summaries involving means and standard deviations make sense.</p>
</section>
<section id="simple-regression-using-dose-to-predict-recovery" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="simple-regression-using-dose-to-predict-recovery"><span class="header-section-number">14.5</span> Simple Regression: Using Dose to predict Recovery</h2>
<p>To start, consider a simple (one predictor) regression model using <code>dose</code> alone to predict the % Recovery (<code>recov.score</code>). Ignoring the <code>age</code> and <code>weight</code> covariates, what can we conclude about this relationship?</p>
</section>
<section id="the-scatterplot-with-fitted-linear-model" class="level2" data-number="14.6">
<h2 data-number="14.6" class="anchored" data-anchor-id="the-scatterplot-with-fitted-linear-model"><span class="header-section-number">14.6</span> The Scatterplot, with fitted Linear Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hydrate, <span class="fu">aes</span>(<span class="at">x =</span> dose, <span class="at">y =</span> recov.score)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Simple Regression model for the hydrate data"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Dose (mEq/l)"</span>, <span class="at">y =</span> <span class="st">"Recovery Score (points)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="the-fitted-linear-model" class="level2" data-number="14.7">
<h2 data-number="14.7" class="anchored" data-anchor-id="the-fitted-linear-model"><span class="header-section-number">14.7</span> The Fitted Linear Model</h2>
<p>To obtain the fitted linear regression model, we use the <code>lm</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(recov.score <span class="sc">~</span> dose, <span class="at">data =</span> hydrate)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m1) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">63.90</td>
<td style="text-align: right;">3.97</td>
<td style="text-align: right;">16.09</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">0.03</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>So, our fitted regression model (prediction model) is <code>recov.score</code> = 63.9 + 4.88 <code>dose</code>.</p>
<section id="confidence-intervals" class="level3" data-number="14.7.1">
<h3 data-number="14.7.1" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">14.7.1</span> Confidence Intervals</h3>
<p>We can obtain confidence intervals around the coefficients of our fitted model with <code>tidy</code>, too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">63.90</td>
<td style="text-align: right;">3.97</td>
<td style="text-align: right;">16.09</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">57.18</td>
<td style="text-align: right;">70.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">1.21</td>
<td style="text-align: right;">8.55</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>So, our 90% confidence interval for the slope of <code>dose</code> ranges from 1.21 to 8.55.</p>
</section>
</section>
<section id="coefficient-plots" class="level2" data-number="14.8">
<h2 data-number="14.8" class="anchored" data-anchor-id="coefficient-plots"><span class="header-section-number">14.8</span> Coefficient Plots</h2>
<p>The <code>tidy</code> method makes it easy to construct coefficient plots using <code>ggplot2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(td, <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> term, <span class="at">col =</span> term)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_crossbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high)) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Estimates with 90% confidence intervals from m1 in hydrate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Another option would be to use <code>geom_errorbarh</code> in this setting, perhaps with a different color scheme…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>td <span class="ot">&lt;-</span> <span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(td, <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> term, <span class="at">col =</span> term)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high)) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">end =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">col =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Estimates with 90% confidence intervals from m1 in hydrate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk70-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="the-summary-output" class="level2" data-number="14.9">
<h2 data-number="14.9" class="anchored" data-anchor-id="the-summary-output"><span class="header-section-number">14.9</span> The Summary Output</h2>
<p>To get a more complete understanding of the fitted model, we’ll summarize it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(recov.score <span class="sc">~</span> dose, <span class="at">data =</span> hydrate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recov.score ~ dose, data = hydrate)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.3360  -7.2763   0.0632   8.4233  23.9028 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   63.896      3.970  16.093   &lt;2e-16 ***
dose           4.881      2.172   2.247   0.0313 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.21 on 34 degrees of freedom
Multiple R-squared:  0.1293,    Adjusted R-squared:  0.1037 
F-statistic: 5.047 on 1 and 34 DF,  p-value: 0.03127</code></pre>
</div>
</div>
<section id="model-specification" class="level3" data-number="14.9.1">
<h3 data-number="14.9.1" class="anchored" data-anchor-id="model-specification"><span class="header-section-number">14.9.1</span> Model Specification</h3>
<ol type="1">
<li>The first part of the output specifies the model that has been fit.
<ul>
<li>Here, we have a simple regression model that predicts <code>recov.score</code> on the basis of <code>dose</code>.</li>
<li>Notice that we’re treating <code>dose</code> here as a quantitative variable. If we wanted <code>dose</code> to be treated as a factor, we’d have specified that in the model.</li>
</ul></li>
</ol>
</section>
<section id="residual-summary" class="level3" data-number="14.9.2">
<h3 data-number="14.9.2" class="anchored" data-anchor-id="residual-summary"><span class="header-section-number">14.9.2</span> Residual Summary</h3>
<ol start="2" type="1">
<li>The second part of the output summarizes the regression <strong>residuals</strong> across the subjects involved in fitting the model.
<ul>
<li>The <strong>residual</strong> is defined as the Actual value of our outcome minus the predicted value of that outcome fitted by the model.</li>
<li>In our case, the residual for a given child is their actual <code>recov.score</code> minus the predicted <code>recov.score</code> according to our model, for that child.</li>
<li>The residual summary gives us a sense of how “incorrect” our predictions are for the <code>hydrate</code> observations.
<ul>
<li>A positive residual means that the observed value was higher than the predicted value from the linear regression model, so the prediction was too low.</li>
<li>A negative residual means that the observed value was lower than the predicted value from the linear regression model, so the prediction was too high.</li>
<li>The residuals will center near 0 (the ordinary least squares model fitting process is designed so the mean of the residuals will always be zero)</li>
<li>We hope to see the median of the residuals also be near zero, generally. In this case, the median prediction is 0.06 point too low.</li>
<li>The minimum and maximum show us the largest prediction errors, made in the subjects used to fit this model.</li>
<li>Here, we predicted a recovery score that was 22.3 points too high for one patient, and another of our predicted recovery scores was 23.9 points too low.</li>
<li>The middle half of our predictions were between 8.4 points too low and 7.3 points too high.</li>
</ul></li>
</ul></li>
</ol>
</section>
<section id="coefficients-output" class="level3" data-number="14.9.3">
<h3 data-number="14.9.3" class="anchored" data-anchor-id="coefficients-output"><span class="header-section-number">14.9.3</span> Coefficients Output</h3>
<ol start="3" type="1">
<li>The <strong>Coefficients</strong> output begins with a table of the estimated coefficients from the regression equation.
<ul>
<li>Generally, we write a simple regression model as <span class="math inline">\(y = \beta_0 + \beta_1 x\)</span>.</li>
<li>In the <code>hydrate</code> model, we have <code>recov.score</code> = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span> <code>dose</code>.</li>
<li>The first column of the table gives the estimated <span class="math inline">\(\beta\)</span> coefficients for our model
<ul>
<li>Here the estimated intercept <span class="math inline">\(\hat{\beta_0} = 63.9\)</span></li>
<li>The estimated slope of dose <span class="math inline">\(\hat{\beta_1} = 4.88\)</span></li>
<li>Thus, our model is <code>recov.score</code>= 63.9 + 4.88 <code>dose</code></li>
</ul></li>
</ul></li>
</ol>
<p>We interpret these coefficients as follows:</p>
<ul>
<li>The intercept (63.9) is the predicted <code>recov.score</code> for a patient receiving a <code>dose</code> of 0 mEq/l of the electrolytic solution.</li>
<li>The slope (4.88) of the <code>dose</code> is the predicted <em>change</em> in <code>recov.score</code> associated with a 1 mEq/l increase in the dose of electrolytic solution.
<ul>
<li>Essentially, if we have two children like the ones studied here, and we give Roger a popsicle with dose X and Sarah a popsicle with dose X + 1, then this model predicts that Sarah will have a recovery score that is 4.88 points higher than will Roger.</li>
<li>From the confidence interval output we saw previously with the function <code>confint(lm(recov.score ~ dose))</code>, we are 95% confident that the true slope for <code>dose</code> is between (0.47, 9.30) mEq/l. We are also 95% confident that the true intercept is between (55.8, 72.0).</li>
</ul></li>
</ul>
</section>
<section id="correlation-and-slope" class="level3" data-number="14.9.4">
<h3 data-number="14.9.4" class="anchored" data-anchor-id="correlation-and-slope"><span class="header-section-number">14.9.4</span> Correlation and Slope</h3>
<p>If we like, we can use the <code>cor</code> function to specify the Pearson correlation of <code>recov.score</code> and <code>dose</code>, which turns out to be 0.36. - Note that the <strong>slope</strong> in a simple regression model will follow the sign of the Pearson correlation coefficient, in this case, both will be positive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>hydrate <span class="sc">|&gt;</span> <span class="fu">select</span>(recov.score, dose) <span class="sc">|&gt;</span> <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            recov.score     dose
recov.score    1.000000 0.359528
dose           0.359528 1.000000</code></pre>
</div>
</div>
</section>
<section id="coefficient-testing" class="level3" data-number="14.9.5">
<h3 data-number="14.9.5" class="anchored" data-anchor-id="coefficient-testing"><span class="header-section-number">14.9.5</span> Coefficient Testing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(recov.score <span class="sc">~</span> dose, <span class="at">data =</span> hydrate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = recov.score ~ dose, data = hydrate)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.3360  -7.2763   0.0632   8.4233  23.9028 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   63.896      3.970  16.093   &lt;2e-16 ***
dose           4.881      2.172   2.247   0.0313 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.21 on 34 degrees of freedom
Multiple R-squared:  0.1293,    Adjusted R-squared:  0.1037 
F-statistic: 5.047 on 1 and 34 DF,  p-value: 0.03127</code></pre>
</div>
</div>
<p>Next to each coefficient in the summary regression table is its estimated standard error, followed by the coefficient’s t value (the coefficient value divided by the standard error), and the associated two-tailed <em>p</em> value for the test of:</p>
<ul>
<li>H0: This coefficient’s <span class="math inline">\(\beta\)</span> value = 0 vs.&nbsp;</li>
<li>HA: This coefficient’s <span class="math inline">\(\beta\)</span> value <span class="math inline">\(\neq\)</span> 0.</li>
</ul>
<p>For the slope coefficient, we can interpret this choice as:</p>
<ul>
<li>H0: This predictor adds no predictive value to the model vs.&nbsp;</li>
<li>HA: This predictor adds some predictive value to the model.</li>
</ul>
<p>In the <code>hydrate</code> simple regression model, by running either <code>tidy</code> with or just the <code>confint</code> function shown below, we can establish a confidence interval for each of the estimated regression coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(m1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">63.90</td>
<td style="text-align: right;">3.97</td>
<td style="text-align: right;">16.09</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">55.83</td>
<td style="text-align: right;">71.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">9.30</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1, <span class="at">level =</span> .<span class="dv">95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 55.826922 71.964589
dose         0.465695  9.295466</code></pre>
</div>
</div>
<p>If the slope of dose was in fact zero, then this would mean that knowing the dose information would be of no additional value in predicting the outcome over just guessing the mean of <code>recov.score</code> for every subject.</p>
<p>So, since the confidence interval for the slope of dose does not include zero, it appears that there is at least some evidence that the model <code>m1</code> is more effective than a model that ignores the <code>dose</code> information (and simply predicts the mean of <code>recov.score</code> for each subject.) That’s not saying much, actually.</p>
</section>
<section id="summarizing-the-quality-of-fit" class="level3" data-number="14.9.6">
<h3 data-number="14.9.6" class="anchored" data-anchor-id="summarizing-the-quality-of-fit"><span class="header-section-number">14.9.6</span> Summarizing the Quality of Fit</h3>
<ol start="4" type="1">
<li>The next part of the regression summary output is a summary of fit quality.</li>
</ol>
<p>The <strong>residual standard error</strong> estimates the standard deviation of the prediction errors made by the model.</p>
<ul>
<li>If assumptions hold, the model will produce residuals that follow a Normal distribution with mean 0 and standard deviation equal to this residual standard error.
<ul>
<li>So we’d expect roughly 95% of our residuals to fall between -2(12.21) and +2(12.21), or roughly -24.4 to +24.4 and that we’d see virtually no residuals outside the range of -3(12.21) to +3(12.21), or roughly -36.6 to +36.6.</li>
<li>The output at the top of the summary tells us about the observed regression residuals, and that they actually range from -22 to +24.</li>
<li>In context, it’s hard to know whether or not we should be happy about this. On a scale from 0 to 100, rarely missing by more than 24 seems OK to me, but not terrific.</li>
</ul></li>
<li>The <strong>degrees of freedom</strong> here are the same as the denominator degrees of freedom in the ANOVA to follow. The calculation is <span class="math inline">\(n - k\)</span>, where <span class="math inline">\(n\)</span> = the number of observations and <span class="math inline">\(k\)</span> is the number of coefficients estimated by the regression (including the intercept and any slopes).
<ul>
<li>Here, there are 36 observations in the model, and we fit <em>k</em> = 2 coefficients; the slope and the intercept, as in any simple regression model, so df = 36 - 2 = 34.</li>
</ul></li>
</ul>
<p>The multiple R-squared value is usually just referred to as R-squared.</p>
<ul>
<li>This is interpreted as the proportion of variation in the outcome variable that has been accounted for by our regression model.
<ul>
<li>Here, we’ve accounted for just under 13% of the variation in % Recovery using Dose.</li>
</ul></li>
<li>The R in multiple R-squared is the Pearson correlation of <code>recov.score</code> and <code>dose</code>, which in this case is 0.3595.
<ul>
<li>Squaring this value gives the R-squared for this simple regression.</li>
<li>(0.3595)^2 = 0.129</li>
</ul></li>
</ul>
<p>R-squared is greedy.</p>
<ul>
<li>R-squared will always suggest that we make our models as big as possible, often including variables of dubious predictive value.</li>
<li>As a result, there are various methods for adjusting or penalizing R-squared so that we wind up with smaller models.</li>
<li>The <strong>adjusted R-squared</strong> is often a useful way to compare multiple models for the same response.
<ul>
<li><span class="math inline">\(R^2_{adj} = 1 - \frac{(1-R^2)(n - 1)}{n - k}\)</span>, where <span class="math inline">\(n\)</span> = the number of observations and <span class="math inline">\(k\)</span> is the number of coefficients estimated by the regression (including the intercept and any slopes).</li>
<li>So, in this case, <span class="math inline">\(R^2_{adj} = 1 - \frac{(1 - 0.1293)(35)}{34} = 0.1037\)</span></li>
<li>The adjusted R-squared value is not, technically, a proportion of anything, but it is comparable across models for the same outcome.</li>
<li>The adjusted R-squared will always be less than the (unadjusted) R-squared.</li>
</ul></li>
</ul>
</section>
<section id="anova-f-test" class="level3" data-number="14.9.7">
<h3 data-number="14.9.7" class="anchored" data-anchor-id="anova-f-test"><span class="header-section-number">14.9.7</span> ANOVA F test</h3>
<ol start="5" type="1">
<li>The last part of the standard summary of a regression model is the overall ANOVA F test.</li>
</ol>
<p>The hypotheses for this test are:</p>
<ul>
<li>H0: Each of the coefficients in the model (other than the intercept) has <span class="math inline">\(\beta\)</span> = 0 vs.</li>
<li>HA: At least one regression slope has <span class="math inline">\(\beta \neq\)</span> 0</li>
</ul>
<p>Since we are doing a simple regression with just one predictor, the ANOVA F test hypotheses are exactly the same as the t test for dose:</p>
<ul>
<li>H0: The slope for <code>dose</code> has <span class="math inline">\(\beta\)</span> = 0 vs.</li>
<li>HA: The slope for <code>dose</code> has <span class="math inline">\(\beta \neq\)</span> 0</li>
</ul>
<p>In this case, we have an F statistic of 5.05 on 1 and 34 degrees of freedom, yielding <em>p</em> = 0.03</p>
<p>This provides some evidence that “something” in our model (here, <code>dose</code> is the only predictor) predicts the outcome to a degree beyond that easily attributed to chance alone. This is not actually surprising, nor is it especially interesting. The confidence interval for the slope is definitely more interesting than this.</p>
<ul>
<li>In <em>simple regression</em> (regression with only one predictor), the t test for the slope (<code>dose</code>) always provides the same p value as the ANOVA F test.
<ul>
<li>The F test statistic in a <em>simple regression</em> is always by definition just the square of the slope’s t test statistic.</li>
<li>Here, F = 5.047, and this is the square of t = 2.247 from the Coefficients output</li>
</ul></li>
</ul>
<p>This test is basically just a combination of the R-squared value (13%) and the sample size. We don’t learn much from it that’s practically interesting or useful.</p>
</section>
</section>
<section id="viewing-the-complete-anova-table" class="level2" data-number="14.10">
<h2 data-number="14.10" class="anchored" data-anchor-id="viewing-the-complete-anova-table"><span class="header-section-number">14.10</span> Viewing the complete ANOVA table</h2>
<p>We can obtain the complete ANOVA table associated with this particular model, and the details behind this F test using the <code>anova</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(recov.score <span class="sc">~</span> dose, <span class="at">data =</span> hydrate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: recov.score
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
dose       1  752.2  752.15  5.0473 0.03127 *
Residuals 34 5066.7  149.02                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>The R-squared for our regression model is equal to the <span class="math inline">\(\eta^2\)</span> for this ANOVA model.
<ul>
<li>If we divide SS(dose) = 752.2 by the total sum of squares (752.2 + 5066.7), we’ll get the multiple R-squared [0.1293]</li>
</ul></li>
<li>Note that this is <em>not</em> the same ANOVA model we would get if we treated <code>dose</code> as a factor with seven levels, rather than as a quantitative variable.</li>
</ul>
</section>
<section id="using-glance-to-summarize-the-models-fit" class="level2" data-number="14.11">
<h2 data-number="14.11" class="anchored" data-anchor-id="using-glance-to-summarize-the-models-fit"><span class="header-section-number">14.11</span> Using <code>glance</code> to summarize the model’s fit</h2>
<p>When applied to a linear model, the <code>glance</code> function from the <code>broom</code> package summarizes 12 characteristics of the model’s fit.</p>
<p>Let’s look at the eight of these that we’ve already addressed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m1) <span class="sc">|&gt;</span> <span class="fu">select</span>(r.squared<span class="sc">:</span>df, df.residual, nobs) <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 17%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">12.2</td>
<td style="text-align: right;">5.05</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>We’ve discussed the R-square value, shown in <code>r.squared</code>.</li>
<li>We’ve also discussed the adjusted R-square value, in <code>adj.r.squared</code></li>
<li><code>sigma</code> is the residual standard error.</li>
<li><code>statistic</code> is the ANOVA F statistic.</li>
<li><code>p.value</code> is the <em>p</em> value associated with the ANOVA F statistic.</li>
<li><code>df</code> is the numerator degrees of freedom (here, the <code>df</code> associated with <code>dose</code>) for the ANOVA test associated with this model.</li>
<li><code>df.residual</code> is the denominator degrees of freedom (here the <code>df</code> associated with <code>residual</code>) for that same ANOVA test.</li>
<li>Remember that the F-statistic at the bottom of the summary output provides these last four statistics, as well.</li>
<li><code>nobs</code> is the number of observations (rows) used to fit the model.</li>
</ul>
<p>Now, let’s look at the remaining four summaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(m1) <span class="sc">|&gt;</span> <span class="fu">select</span>(logLik<span class="sc">:</span>deviance) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-140.1</td>
<td style="text-align: right;">286.3</td>
<td style="text-align: right;">291</td>
<td style="text-align: right;">5066.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><code>logLik</code> is the log-likelihood value for the model, and is most commonly used for a model (like the ordinary least squares model fit by <code>lm</code> that is fit using the method of maximum likelihood). Thus, the log-likelihood value will be maximized in this fit.</li>
<li><code>AIC</code> is the Akaike Information Criterion for the model. When comparing models fitted by maximum likelihood to the same outcome variable (using the same transformation, for example), the smaller the AIC, the better the fit.</li>
<li><code>BIC</code> is the Bayes Information Criterion for the model. When comparing models fitted by maximum likelihood to the same outcome variable (using the same transformation, for example), the smaller the BIC, the better the fit. BIC often prefers models with fewer coefficients to estimate than does AIC.
<ul>
<li><code>AIC</code> and <code>BIC</code> can be estimated using several different approaches in R, but we’ll need to use the same one across multiple models if we’re comparing the results, because the concepts are only defined up to a constant.</li>
</ul></li>
<li><code>deviance</code> is the fitted model’s deviance, a measure of lack of fit. It is a generalization of the residual sum of squares seen in the ANOVA table, and takes the same value in the case of a simple linear regression model fit with <code>lm</code> as we have here. For some generalized linear models, we’ll use this for hypothesis testing, just as the ANOVA table does in the linear model case.</li>
</ul>
</section>
<section id="plotting-residuals-vs.-fitted-values" class="level2" data-number="14.12">
<h2 data-number="14.12" class="anchored" data-anchor-id="plotting-residuals-vs.-fitted-values"><span class="header-section-number">14.12</span> Plotting Residuals vs.&nbsp;Fitted Values</h2>
<p>To save the residuals and predicted (fitted) values from this simple regression model, we can use the <code>resid</code> and <code>fitted</code> commands, respectively, or we can use the <code>augment</code> function in the <code>broom</code> package to obtain a tidy data set containing these objects and others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(m1) <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> F, <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs. Fitted values for Model m1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk160-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also obtain a plot of residuals vs.&nbsp;fitted values for <code>m1</code> using the following code from base R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="14-hydrate_files/figure-html/c14_chunk170-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We hope in this plot to see a generally random scatter of points, perhaps looking like a “fuzzy football”. Since we only have seven possible <code>dose</code> values, we obtain only seven distinct predicted values, which explains the seven vertical lines in the plot. Here, the smooth red line indicates a gentle curve, but no evidence of a strong curve, or any other regular pattern in this residual plot.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-crabs.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-wcgs.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The WCGS</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>