<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notes for 431 - 20&nbsp; Two Examples Comparing Means</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./21-one_proportion.html" rel="next">
<link href="./19-samplesize.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">NHANES: A First Look</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Structures, Variable Types &amp; Sampling NHANES</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Visualizing NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assessingnormality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-examples_2means.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">20.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#a-study-of-battery-life" id="toc-a-study-of-battery-life" class="nav-link" data-scroll-target="#a-study-of-battery-life"> <span class="header-section-number">20.2</span> A Study of Battery Life</a>
  <ul class="collapse">
  <li><a href="#question-1.-what-is-the-outcome-under-study" id="toc-question-1.-what-is-the-outcome-under-study" class="nav-link" data-scroll-target="#question-1.-what-is-the-outcome-under-study"> <span class="header-section-number">20.2.1</span> Question 1. What is the outcome under study?</a></li>
  <li><a href="#question-2.-what-are-the-treatmentexposure-groups" id="toc-question-2.-what-are-the-treatmentexposure-groups" class="nav-link" data-scroll-target="#question-2.-what-are-the-treatmentexposure-groups"> <span class="header-section-number">20.2.2</span> Question 2. What are the treatment/exposure groups?</a></li>
  <li><a href="#question-3.-are-the-data-collected-using-paired-or-independent-samples" id="toc-question-3.-are-the-data-collected-using-paired-or-independent-samples" class="nav-link" data-scroll-target="#question-3.-are-the-data-collected-using-paired-or-independent-samples"> <span class="header-section-number">20.2.3</span> Question 3. Are the data collected using paired or independent samples?</a></li>
  <li><a href="#question-4.-are-the-data-a-random-sample-from-the-population-of-interest" id="toc-question-4.-are-the-data-a-random-sample-from-the-population-of-interest" class="nav-link" data-scroll-target="#question-4.-are-the-data-a-random-sample-from-the-population-of-interest"> <span class="header-section-number">20.2.4</span> Question 4. Are the data a random sample from the population of interest?</a></li>
  <li><a href="#question-5.-what-significance-level-will-we-use" id="toc-question-5.-what-significance-level-will-we-use" class="nav-link" data-scroll-target="#question-5.-what-significance-level-will-we-use"> <span class="header-section-number">20.2.5</span> Question 5. What significance level will we use?</a></li>
  <li><a href="#question-6.-are-we-using-a-one-sided-or-two-sided-comparison" id="toc-question-6.-are-we-using-a-one-sided-or-two-sided-comparison" class="nav-link" data-scroll-target="#question-6.-are-we-using-a-one-sided-or-two-sided-comparison"> <span class="header-section-number">20.2.6</span> Question 6. Are we using a one-sided or two-sided comparison?</a></li>
  <li><a href="#question-9.-what-does-the-distribution-of-outcomes-in-each-group-tell-us" id="toc-question-9.-what-does-the-distribution-of-outcomes-in-each-group-tell-us" class="nav-link" data-scroll-target="#question-9.-what-does-the-distribution-of-outcomes-in-each-group-tell-us"> <span class="header-section-number">20.2.7</span> Question 9. What does the distribution of outcomes in each group tell us?</a></li>
  <li><a href="#inferential-results-for-the-battery-study" id="toc-inferential-results-for-the-battery-study" class="nav-link" data-scroll-target="#inferential-results-for-the-battery-study"> <span class="header-section-number">20.2.8</span> Inferential Results for the Battery Study</a></li>
  <li><a href="#paired-samples-approaches" id="toc-paired-samples-approaches" class="nav-link" data-scroll-target="#paired-samples-approaches"> <span class="header-section-number">20.2.9</span> Paired Samples Approaches</a></li>
  <li><a href="#independent-samples-approaches" id="toc-independent-samples-approaches" class="nav-link" data-scroll-target="#independent-samples-approaches"> <span class="header-section-number">20.2.10</span> Independent Samples Approaches</a></li>
  </ul></li>
  <li><a href="#the-breakfast-study-does-oat-bran-cereal-lower-serum-ldl-cholesterol" id="toc-the-breakfast-study-does-oat-bran-cereal-lower-serum-ldl-cholesterol" class="nav-link" data-scroll-target="#the-breakfast-study-does-oat-bran-cereal-lower-serum-ldl-cholesterol"> <span class="header-section-number">20.3</span> The Breakfast Study: Does Oat Bran Cereal Lower Serum LDL Cholesterol?</a>
  <ul class="collapse">
  <li><a href="#question-1.-what-is-the-outcome-under-study-1" id="toc-question-1.-what-is-the-outcome-under-study-1" class="nav-link" data-scroll-target="#question-1.-what-is-the-outcome-under-study-1"> <span class="header-section-number">20.3.1</span> Question 1. What is the outcome under study?</a></li>
  <li><a href="#question-2.-what-are-the-treatmentexposure-groups-1" id="toc-question-2.-what-are-the-treatmentexposure-groups-1" class="nav-link" data-scroll-target="#question-2.-what-are-the-treatmentexposure-groups-1"> <span class="header-section-number">20.3.2</span> Question 2. What are the treatment/exposure groups?</a></li>
  <li><a href="#question-3.-are-the-data-collected-using-paired-or-independent-samples-1" id="toc-question-3.-are-the-data-collected-using-paired-or-independent-samples-1" class="nav-link" data-scroll-target="#question-3.-are-the-data-collected-using-paired-or-independent-samples-1"> <span class="header-section-number">20.3.3</span> Question 3. Are the data collected using paired or independent samples?</a></li>
  <li><a href="#question-4.-are-the-data-a-random-sample-from-the-population-of-interest-1" id="toc-question-4.-are-the-data-a-random-sample-from-the-population-of-interest-1" class="nav-link" data-scroll-target="#question-4.-are-the-data-a-random-sample-from-the-population-of-interest-1"> <span class="header-section-number">20.3.4</span> Question 4. Are the data a random sample from the population of interest?</a></li>
  <li><a href="#question-5.-what-significance-level-will-we-use-1" id="toc-question-5.-what-significance-level-will-we-use-1" class="nav-link" data-scroll-target="#question-5.-what-significance-level-will-we-use-1"> <span class="header-section-number">20.3.5</span> Question 5. What significance level will we use?</a></li>
  <li><a href="#question-6.-are-we-using-a-one-sided-or-two-sided-comparison-1" id="toc-question-6.-are-we-using-a-one-sided-or-two-sided-comparison-1" class="nav-link" data-scroll-target="#question-6.-are-we-using-a-one-sided-or-two-sided-comparison-1"> <span class="header-section-number">20.3.6</span> Question 6. Are we using a one-sided or two-sided comparison?</a></li>
  <li><a href="#question-7.-did-pairing-help-reduce-nuisance-variation" id="toc-question-7.-did-pairing-help-reduce-nuisance-variation" class="nav-link" data-scroll-target="#question-7.-did-pairing-help-reduce-nuisance-variation"> <span class="header-section-number">20.3.7</span> Question 7. Did pairing help reduce nuisance variation?</a></li>
  <li><a href="#question-8.-what-does-the-distribution-of-paired-differences-tell-us" id="toc-question-8.-what-does-the-distribution-of-paired-differences-tell-us" class="nav-link" data-scroll-target="#question-8.-what-does-the-distribution-of-paired-differences-tell-us"> <span class="header-section-number">20.3.8</span> Question 8. What does the distribution of paired differences tell us?</a></li>
  </ul></li>
  <li><a href="#power-sample-size-and-the-breakfast-study" id="toc-power-sample-size-and-the-breakfast-study" class="nav-link" data-scroll-target="#power-sample-size-and-the-breakfast-study"> <span class="header-section-number">20.4</span> Power, Sample Size and the Breakfast Study</a>
  <ul class="collapse">
  <li><a href="#the-setup" id="toc-the-setup" class="nav-link" data-scroll-target="#the-setup"> <span class="header-section-number">20.4.1</span> The Setup</a></li>
  <li><a href="#the-r-calculations" id="toc-the-r-calculations" class="nav-link" data-scroll-target="#the-r-calculations"> <span class="header-section-number">20.4.2</span> The R Calculations</a></li>
  <li><a href="#independent-samples-instead-of-paired-samples" id="toc-independent-samples-instead-of-paired-samples" class="nav-link" data-scroll-target="#independent-samples-instead-of-paired-samples"> <span class="header-section-number">20.4.3</span> Independent samples, instead of paired samples?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="setup-packages-used-here" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">20.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"data/Love-boost.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In addition to the <code>Love-boost.R</code> script, we will also use the <code>favstats</code> function from the <code>mosaic</code> package.</p>
</section>
<section id="a-study-of-battery-life" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="a-study-of-battery-life"><span class="header-section-number">20.2</span> A Study of Battery Life</h2>
<p>Should you buy generic rather than brand-name batteries? <span class="citation" data-cites="BockVD">Bock, Velleman, and De Veaux (<a href="references.html#ref-BockVD" role="doc-biblioref">2004</a>)</span> descibe a designed experiment to test battery life. A (male) student obtained six pairs of AA alkaline batteries from two major battery manufacturers; a well-known brand name and a generic brand, so that battery brand was the factor of interest.</p>
<p>To estimate the difference in mean lifetimes across the two manufacturers, the student kept a battery-powered CD player with the same CD running continuously, with the volume control fixed at 5, and measured the time until no more music was heard through the headphones. (He ran an initial trial to find out approximately how long that would take, so he didn’t have to spend the first 3 hours of each run listening to the same CD.) The outcome was the time in minutes until the sound stopped. To account for changes in the CD player’s performance over time, he randomized the run order by choosing pairs of batteries (the CD-player required two batteries to run) at random.</p>
<p>Here are the results for the 6 brand name and 6 generic tests, in minutes, found in the <code>battery.csv</code> data file, where <code>run</code> indicates the order in which the tests were run…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>battery <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/battery.csv"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>battery</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
     run  test type        time
   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
 1     1     1 brand name  191.
 2     2     2 brand name  206.
 3     6     3 brand name  199.
 4     8     4 brand name  172.
 5     9     5 brand name  184 
 6    12     6 brand name  170.
 7     3     1 generic     194 
 8     4     2 generic     204.
 9     5     3 generic     204.
10     7     4 generic     206.
11    10     5 generic     222.
12    11     6 generic     209.</code></pre>
</div>
</div>
<section id="question-1.-what-is-the-outcome-under-study" class="level3" data-number="20.2.1">
<h3 data-number="20.2.1" class="anchored" data-anchor-id="question-1.-what-is-the-outcome-under-study"><span class="header-section-number">20.2.1</span> Question 1. What is the outcome under study?</h3>
<p>We are studying battery lifetimes (time until the sound stopped) in minutes.</p>
</section>
<section id="question-2.-what-are-the-treatmentexposure-groups" class="level3" data-number="20.2.2">
<h3 data-number="20.2.2" class="anchored" data-anchor-id="question-2.-what-are-the-treatmentexposure-groups"><span class="header-section-number">20.2.2</span> Question 2. What are the treatment/exposure groups?</h3>
<p>We are comparing the two brands of batteries: the well-known vs.&nbsp;the generic.</p>
</section>
<section id="question-3.-are-the-data-collected-using-paired-or-independent-samples" class="level3" data-number="20.2.3">
<h3 data-number="20.2.3" class="anchored" data-anchor-id="question-3.-are-the-data-collected-using-paired-or-independent-samples"><span class="header-section-number">20.2.3</span> Question 3. Are the data collected using paired or independent samples?</h3>
<p>Of course, if we had different numbers of samples in the two groups, then we’d know without further thought that independent samples were required. Since we have 6 observations in the brand name group, and also have 6 observations in the generic group, i.e.&nbsp;a balanced design, we need to pause now to decide whether paired or independent samples testing is appropriate in this setting.</p>
<p>Two samples are paired if each data point in one sample is naturally linked to a specific data point in the other sample. So, do we have paired or independent samples?</p>
<ul>
<li>Despite the way I’ve set up the data table, there is no particular reason to pair, say, run #1 (a brand name run) with any particular experimental run in the generic group. So the samples are independent. This is not a matched-pairs design.</li>
<li>In each trial, the student either used two of the well-known batteries, or two of the generic batteries.</li>
<li>Any of the tests/confidence intervals for the independent samples methods suggests a statistically significant (at the 5% level) difference between the generic and brand name batteries.</li>
</ul>
</section>
<section id="question-4.-are-the-data-a-random-sample-from-the-population-of-interest" class="level3" data-number="20.2.4">
<h3 data-number="20.2.4" class="anchored" data-anchor-id="question-4.-are-the-data-a-random-sample-from-the-population-of-interest"><span class="header-section-number">20.2.4</span> Question 4. Are the data a random sample from the population of interest?</h3>
<p>Probably not. The data are likely to come from a convenient sample of batteries. I don’t know how this might bias the study, though. It seems unlikely that there would be a particular bias unless, for example, the well-known batteries were substantially older or younger than the generic.</p>
</section>
<section id="question-5.-what-significance-level-will-we-use" class="level3" data-number="20.2.5">
<h3 data-number="20.2.5" class="anchored" data-anchor-id="question-5.-what-significance-level-will-we-use"><span class="header-section-number">20.2.5</span> Question 5. What significance level will we use?</h3>
<p>We have no reason not to use a 95% confidence level.</p>
</section>
<section id="question-6.-are-we-using-a-one-sided-or-two-sided-comparison" class="level3" data-number="20.2.6">
<h3 data-number="20.2.6" class="anchored" data-anchor-id="question-6.-are-we-using-a-one-sided-or-two-sided-comparison"><span class="header-section-number">20.2.6</span> Question 6. Are we using a one-sided or two-sided comparison?</h3>
<p>We could argue for a one-sided comparison, but I’ll be safe and use the two-sided version.</p>
</section>
<section id="question-9.-what-does-the-distribution-of-outcomes-in-each-group-tell-us" class="level3" data-number="20.2.7">
<h3 data-number="20.2.7" class="anchored" data-anchor-id="question-9.-what-does-the-distribution-of-outcomes-in-each-group-tell-us"><span class="header-section-number">20.2.7</span> Question 9. What does the distribution of outcomes in each group tell us?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(battery, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> time, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> type), <span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">width =</span> <span class="fl">0.125</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>, <span class="at">col =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Battery Running Time, by Manufacturer"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Running Time (minutes)"</span>, <span class="at">x =</span> <span class="st">"Manufacturer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-examples_2means_files/figure-html/battery1-fig-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can generate histograms, too, but that’s an issue, because we have so few observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(battery, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">fill =</span> type)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">6</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> type) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Battery Running Time, by Manufacturer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-examples_2means_files/figure-html/histogram-battery-fig-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(time <span class="sc">~</span> type, <span class="at">data =</span> battery)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        type   min    Q1 median      Q3   max     mean        sd n missing
1 brand name 169.5 175.3 187.35 197.075 205.5 186.8833 14.374341 6       0
2    generic 194.0 203.5 205.00 208.675 222.5 206.5667  9.366251 6       0</code></pre>
</div>
</div>
<p>It sure looks like the generic batteries lasted longer. And they also look like they were more consistent. The sample means are 206.6 for the generic group, 186.9 minutes for brand name, so the point estimate of the difference is 19.7 minutes.</p>
<p>The question is: can we be confident that the difference we observe here is more than just random fluctuation, at a 5% significance level?</p>
</section>
<section id="inferential-results-for-the-battery-study" class="level3" data-number="20.2.8">
<h3 data-number="20.2.8" class="anchored" data-anchor-id="inferential-results-for-the-battery-study"><span class="header-section-number">20.2.8</span> Inferential Results for the Battery Study</h3>
<p>In the table below, I have summarized the two-sided testing results for most of the ways in which we have looked at a two sample comparison so far, with 95% confidence intervals. If the samples really are paired, then we must choose from the paired samples comparisons described in the table. If the samples really are independent, then we must choose from the independent samples comparisons.</p>
</section>
<section id="paired-samples-approaches" class="level3" data-number="20.2.9">
<h3 data-number="20.2.9" class="anchored" data-anchor-id="paired-samples-approaches"><span class="header-section-number">20.2.9</span> Paired Samples Approaches</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Method</th>
<th style="text-align: right;"><em>p</em> Value</th>
<th style="text-align: center;">95% CI for Generic - Brand Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Paired t</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: center;">-1.0, 40.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">Wilcoxon signed rank</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: center;">-2.0, 39.9</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Bootstrap via <code>smean.cl.boot</code></td>
<td style="text-align: right;">–</td>
<td style="text-align: center;">6.7, 33.0</td>
</tr>
</tbody>
</table>
</section>
<section id="independent-samples-approaches" class="level3" data-number="20.2.10">
<h3 data-number="20.2.10" class="anchored" data-anchor-id="independent-samples-approaches"><span class="header-section-number">20.2.10</span> Independent Samples Approaches</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Method</th>
<th style="text-align: right;"><em>p</em> Value</th>
<th style="text-align: center;">95% CI for Generic - Brand Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Pooled t</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: center;">4.1, 35.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">Welch’s t</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: center;">3.7, 35.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Wilcoxon Mann Whitney rank sum</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: center;">3.3, 37.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">Bootstrap via <code>bootdif</code></td>
<td style="text-align: right;">–</td>
<td style="text-align: center;">7.7, 32.2</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="the-breakfast-study-does-oat-bran-cereal-lower-serum-ldl-cholesterol" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="the-breakfast-study-does-oat-bran-cereal-lower-serum-ldl-cholesterol"><span class="header-section-number">20.3</span> The Breakfast Study: Does Oat Bran Cereal Lower Serum LDL Cholesterol?</h2>
<p><span class="citation" data-cites="Norman-Streiner">Norman and Streiner (<a href="references.html#ref-Norman-Streiner" role="doc-biblioref">2014</a>)</span> describe a crossover study that was conducted to investigate whether oat bran cereal helps to lower serum cholesterol levels in hypercholesterolemic males. Fourteen such individuals were randomly placed on a diet that included either oat bran or corn flakes; after two weeks, their low-density lipoprotein (LDL) cholesterol levels, in mmol/l were recorded. Each subject was then switched to the alternative diet. After a second two-week period, the LDL cholesterol level of each subject was again recorded.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>breakfast <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/breakfast.csv"</span>,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>breakfast</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 3
   subject cornflakes oatbran
     &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
 1       1       4.61    3.84
 2       2       6.42    5.57
 3       3       5.4     5.85
 4       4       4.54    4.8 
 5       5       3.98    3.68
 6       6       3.82    2.96
 7       7       5.01    4.41
 8       8       4.34    3.72
 9       9       3.8     3.49
10      10       4.56    3.84
11      11       5.35    5.26
12      12       3.89    3.73
13      13       2.25    1.84
14      14       4.24    4.14</code></pre>
</div>
</div>
<section id="question-1.-what-is-the-outcome-under-study-1" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="question-1.-what-is-the-outcome-under-study-1"><span class="header-section-number">20.3.1</span> Question 1. What is the outcome under study?</h3>
<p>We are studying levels of LDL cholesterol, in mmol/l. Note that if we wanted to convert to a more familiar scale, specifically mg/dl, we would multiply the mmol/l by 18, as it turns out.</p>
</section>
<section id="question-2.-what-are-the-treatmentexposure-groups-1" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="question-2.-what-are-the-treatmentexposure-groups-1"><span class="header-section-number">20.3.2</span> Question 2. What are the treatment/exposure groups?</h3>
<p>We are comparing subjects after two weeks of eating corn flakes to the same subjects after two weeks of eating oat bran.</p>
</section>
<section id="question-3.-are-the-data-collected-using-paired-or-independent-samples-1" class="level3" data-number="20.3.3">
<h3 data-number="20.3.3" class="anchored" data-anchor-id="question-3.-are-the-data-collected-using-paired-or-independent-samples-1"><span class="header-section-number">20.3.3</span> Question 3. Are the data collected using paired or independent samples?</h3>
<p>These are matched pairs, paired by subject. Each subject produced an oat bran result and a corn flakes result.</p>
</section>
<section id="question-4.-are-the-data-a-random-sample-from-the-population-of-interest-1" class="level3" data-number="20.3.4">
<h3 data-number="20.3.4" class="anchored" data-anchor-id="question-4.-are-the-data-a-random-sample-from-the-population-of-interest-1"><span class="header-section-number">20.3.4</span> Question 4. Are the data a random sample from the population of interest?</h3>
<p>Probably not. The data are likely to come from a convenient sample of 14 individuals but they were randomly assigned to cornflakes first or to oat bran first, then crossed over.</p>
</section>
<section id="question-5.-what-significance-level-will-we-use-1" class="level3" data-number="20.3.5">
<h3 data-number="20.3.5" class="anchored" data-anchor-id="question-5.-what-significance-level-will-we-use-1"><span class="header-section-number">20.3.5</span> Question 5. What significance level will we use?</h3>
<p>We have no reason not to use our usual 95% confidence level, so <code>alpha</code> = 0.05</p>
</section>
<section id="question-6.-are-we-using-a-one-sided-or-two-sided-comparison-1" class="level3" data-number="20.3.6">
<h3 data-number="20.3.6" class="anchored" data-anchor-id="question-6.-are-we-using-a-one-sided-or-two-sided-comparison-1"><span class="header-section-number">20.3.6</span> Question 6. Are we using a one-sided or two-sided comparison?</h3>
<p>We could argue for a one-sided comparison, but I’ll be safe and use the two-sided version.</p>
</section>
<section id="question-7.-did-pairing-help-reduce-nuisance-variation" class="level3" data-number="20.3.7">
<h3 data-number="20.3.7" class="anchored" data-anchor-id="question-7.-did-pairing-help-reduce-nuisance-variation"><span class="header-section-number">20.3.7</span> Question 7. Did pairing help reduce nuisance variation?</h3>
<p>After we drop the <code>breakfast.csv</code> file into the <code>breakfast</code> data frame, we look at the correlation of cornflakes and oatbran results across our 14 subjects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(breakfast<span class="sc">$</span>cornflakes, breakfast<span class="sc">$</span>oatbran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9233247</code></pre>
</div>
</div>
<p>The sample Pearson correlation coefficient is very strong and positive at 0.92, so the paired samples approach will use these data far more effectively than the (incorrect) independent samples approach.</p>
</section>
<section id="question-8.-what-does-the-distribution-of-paired-differences-tell-us" class="level3" data-number="20.3.8">
<h3 data-number="20.3.8" class="anchored" data-anchor-id="question-8.-what-does-the-distribution-of-paired-differences-tell-us"><span class="header-section-number">20.3.8</span> Question 8. What does the distribution of paired differences tell us?</h3>
<p>We summarize the distribution of the paired differences (cornflakes - oatbran) below.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="20-examples_2means_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Normal distribution doesn’t look too ridiculous in this case for the paired (cornflakes-oatbran) differences. Suppose we assume Normality and run the paired t test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(breakfast<span class="sc">$</span>cornflakes <span class="sc">-</span> breakfast<span class="sc">$</span>oatbran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  breakfast$cornflakes - breakfast$oatbran
t = 3.3444, df = 13, p-value = 0.005278
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 0.1284606 0.5972537
sample estimates:
mean of x 
0.3628571 </code></pre>
</div>
</div>
<p>Based on this sample of 14 subjects in the crossover study, we observe a 95% confidence interval for the difference between the LDL cholesterol levels after eating corn flakes and eating oat bran that is entirely positive, suggesting that LDL levels were detectably higher (according to this t test procedure) after eating corn flakes than after eating oat bran.</p>
</section>
</section>
<section id="power-sample-size-and-the-breakfast-study" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="power-sample-size-and-the-breakfast-study"><span class="header-section-number">20.4</span> Power, Sample Size and the Breakfast Study</h2>
<p>As a preview of what’s next to come, let’s investigate these promising results a bit further. Suppose that in a new study, you wish to be able to detect a difference in LDL cholesterol between two exposures: subjects who eat cornflakes (as in the original study) and subjects who continue to eat cornflakes but also take a supplemental dosage of what you believe to be the crucial ingredient in oatbran.</p>
<p>Suppose you believe that the effect of taking the new supplement will be about half the size of the effect you observed in the original breakfast study on hypercholesterolemic males, but that males generally may be more likely to take your supplement regularly than switch from cornflakes to a less appetizing breakfast choice, making your supplement attractive.</p>
<p>What sample size will be required to yield 90% power to detect an effect half the size of the effect we observed in the breakfast study, in a new paired samples study using a two-tailed 5% significance level? What if we only required 80% power?</p>
<section id="the-setup" class="level3" data-number="20.4.1">
<h3 data-number="20.4.1" class="anchored" data-anchor-id="the-setup"><span class="header-section-number">20.4.1</span> The Setup</h3>
<p>We want to know <em>n</em>, the minimum required sample size for the new study, and we have:</p>
<ul>
<li>A specified effect size of half of what we saw in the breakfast study, where the sample mean difference between cornflakes and oatbran was 0.36 mmol/l, so our effect size is assumed to be <code>delta</code> = 0.18 mmol/l.</li>
<li>An assumed standard deviation equal to the standard deviation of the differences in the pilot breakfast study, which turns out to have been s = 0.41 mmol/l.</li>
<li>We also have a pre-specified <code>alpha</code> = 0.05 using a two-tailed test.</li>
<li>We also want the power to be at least 90% for our new study.</li>
</ul>
</section>
<section id="the-r-calculations" class="level3" data-number="20.4.2">
<h3 data-number="20.4.2" class="anchored" data-anchor-id="the-r-calculations"><span class="header-section-number">20.4.2</span> The R Calculations</h3>
<p><strong>Question 1.</strong> What sample size will be required to yield 90% power to detect an effect half the size of the effect we observed in the breakfast study, in a new paired samples study using a two-tailed 5% significance level?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="fl">0.18</span>, <span class="at">sd =</span> <span class="fl">0.41</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">power =</span> <span class="fl">0.9</span>, <span class="at">type=</span><span class="st">"paired"</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Paired t test power calculation 

              n = 56.47119
          delta = 0.18
             sd = 0.41
      sig.level = 0.05
          power = 0.9
    alternative = two.sided

NOTE: n is number of *pairs*, sd is std.dev. of *differences* within pairs</code></pre>
</div>
</div>
<p>And so our new study will require at least <strong>57 subjects</strong> (each measured in two circumstances, so 114 total measurements) in order to achieve at least 90% power to detect the difference of 0.18 mmol/l while meeting these specifications.</p>
<p><strong>Question 2.</strong> What if we were willing to accept only 80% power?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="fl">0.18</span>, <span class="at">sd =</span> <span class="fl">0.41</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">power =</span> <span class="fl">0.8</span>, <span class="at">type=</span><span class="st">"paired"</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Paired t test power calculation 

              n = 42.68269
          delta = 0.18
             sd = 0.41
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number of *pairs*, sd is std.dev. of *differences* within pairs</code></pre>
</div>
</div>
<p>It turns out that this would require at least <strong>43 subjects</strong>.</p>
</section>
<section id="independent-samples-instead-of-paired-samples" class="level3" data-number="20.4.3">
<h3 data-number="20.4.3" class="anchored" data-anchor-id="independent-samples-instead-of-paired-samples"><span class="header-section-number">20.4.3</span> Independent samples, instead of paired samples?</h3>
<p>What would happen if, instead of doing a paired samples study, we did one using independent samples? Assuming we used a balanced design, and assigned the same number of different people at random to either the oatbran supplement or regular cornflakes alone, we could do such a study, but it would require many more people to obtain similar power to the paired samples study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta =</span> <span class="fl">0.18</span>, <span class="at">sd =</span> <span class="fl">0.41</span>, <span class="at">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">power =</span> <span class="fl">0.9</span>, <span class="at">type=</span><span class="st">"two.sample"</span>, <span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 110
          delta = 0.18
             sd = 0.41
      sig.level = 0.05
          power = 0.9
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>In all, <strong>220 people</strong> would be required in the independent samples study (110 in each exposure group), as compared to only <strong>57 people</strong> (each measured twice) in the paired study.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-BockVD" class="csl-entry" role="doc-biblioentry">
Bock, David E., Paul F. Velleman, and Richard D. De Veaux. 2004. <em>Stats: Modelling the World</em>. Boston <span>MA</span>: Pearson Addison-Wesley.
</div>
<div id="ref-Norman-Streiner" class="csl-entry" role="doc-biblioentry">
Norman, Geoffrey R., and David L. Streiner. 2014. <em>Biostatistics: The Bare Essentials</em>. Fourth. People’s Medical Publishing House.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./19-samplesize.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./21-one_proportion.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>