<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Notes for 431 - 20&nbsp; Ibuprofen in Sepsis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./21-pairedsamples.html" rel="next">
<link href="./19-ci_for_mean.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-testing_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size and Power for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-regr_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-prediction_wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partChold.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Rest of Part C coming soon.</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">20.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#the-trial" id="toc-the-trial" class="nav-link" data-scroll-target="#the-trial"> <span class="header-section-number">20.2</span> The Trial</a></li>
  <li><a href="#comparing-two-groups" id="toc-comparing-two-groups" class="nav-link" data-scroll-target="#comparing-two-groups"> <span class="header-section-number">20.3</span> Comparing Two Groups</a>
  <ul class="collapse">
  <li><a href="#model-based-comparisons-and-anovaregression" id="toc-model-based-comparisons-and-anovaregression" class="nav-link" data-scroll-target="#model-based-comparisons-and-anovaregression"> <span class="header-section-number">20.3.1</span> Model-Based Comparisons and ANOVA/Regression</a></li>
  </ul></li>
  <li><a href="#key-questions-for-comparing-with-independent-samples" id="toc-key-questions-for-comparing-with-independent-samples" class="nav-link" data-scroll-target="#key-questions-for-comparing-with-independent-samples"> <span class="header-section-number">20.4</span> Key Questions for Comparing with Independent Samples</a>
  <ul class="collapse">
  <li><a href="#what-is-the-population-under-study" id="toc-what-is-the-population-under-study" class="nav-link" data-scroll-target="#what-is-the-population-under-study"> <span class="header-section-number">20.4.1</span> What is the <strong>population</strong> under study?</a></li>
  <li><a href="#what-is-the-sample-is-it-representative-of-the-population" id="toc-what-is-the-sample-is-it-representative-of-the-population" class="nav-link" data-scroll-target="#what-is-the-sample-is-it-representative-of-the-population"> <span class="header-section-number">20.4.2</span> What is the <strong>sample</strong>? Is it representative of the population?</a></li>
  <li><a href="#who-are-the-subjects-individuals-within-the-sample" id="toc-who-are-the-subjects-individuals-within-the-sample" class="nav-link" data-scroll-target="#who-are-the-subjects-individuals-within-the-sample"> <span class="header-section-number">20.4.3</span> Who are the subjects / <strong>individuals</strong> within the sample?</a></li>
  <li><a href="#what-data-are-available-on-each-individual" id="toc-what-data-are-available-on-each-individual" class="nav-link" data-scroll-target="#what-data-are-available-on-each-individual"> <span class="header-section-number">20.4.4</span> What <strong>data</strong> are available on each individual?</a></li>
  <li><a href="#rct-caveats" id="toc-rct-caveats" class="nav-link" data-scroll-target="#rct-caveats"> <span class="header-section-number">20.4.5</span> RCT Caveats</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"> <span class="header-section-number">20.5</span> Exploratory Data Analysis</a></li>
  <li><a href="#estimating-the-difference-in-population-means" id="toc-estimating-the-difference-in-population-means" class="nav-link" data-scroll-target="#estimating-the-difference-in-population-means"> <span class="header-section-number">20.6</span> Estimating the Difference in Population Means</a></li>
  <li><a href="#t-based-ci-for-population-mean1---mean2-difference" id="toc-t-based-ci-for-population-mean1---mean2-difference" class="nav-link" data-scroll-target="#t-based-ci-for-population-mean1---mean2-difference"> <span class="header-section-number">20.7</span> t-based CI for population mean1 - mean2 difference</a>
  <ul class="collapse">
  <li><a href="#the-pooled-t-procedure" id="toc-the-pooled-t-procedure" class="nav-link" data-scroll-target="#the-pooled-t-procedure"> <span class="header-section-number">20.7.1</span> The Pooled t procedure</a></li>
  <li><a href="#using-linear-regression-to-obtain-a-pooled-t-confidence-interval" id="toc-using-linear-regression-to-obtain-a-pooled-t-confidence-interval" class="nav-link" data-scroll-target="#using-linear-regression-to-obtain-a-pooled-t-confidence-interval"> <span class="header-section-number">20.7.2</span> Using linear regression to obtain a pooled t confidence interval</a></li>
  <li><a href="#the-welch-t-procedure" id="toc-the-welch-t-procedure" class="nav-link" data-scroll-target="#the-welch-t-procedure"> <span class="header-section-number">20.7.3</span> The Welch t procedure</a></li>
  </ul></li>
  <li><a href="#wilcoxon-mann-whitney-rank-sum-ci" id="toc-wilcoxon-mann-whitney-rank-sum-ci" class="nav-link" data-scroll-target="#wilcoxon-mann-whitney-rank-sum-ci"> <span class="header-section-number">20.8</span> Wilcoxon-Mann-Whitney “Rank Sum” CI</a></li>
  <li><a href="#bootstrapping-a-more-robust-approach" id="toc-bootstrapping-a-more-robust-approach" class="nav-link" data-scroll-target="#bootstrapping-a-more-robust-approach"> <span class="header-section-number">20.9</span> Bootstrapping: A More Robust Approach</a>
  <ul class="collapse">
  <li><a href="#bootstrap-ci-for-the-sepsis-study" id="toc-bootstrap-ci-for-the-sepsis-study" class="nav-link" data-scroll-target="#bootstrap-ci-for-the-sepsis-study"> <span class="header-section-number">20.9.1</span> Bootstrap CI for the Sepsis study</a></li>
  </ul></li>
  <li><a href="#summary-specifying-a-two-sample-study-design" id="toc-summary-specifying-a-two-sample-study-design" class="nav-link" data-scroll-target="#summary-specifying-a-two-sample-study-design"> <span class="header-section-number">20.10</span> Summary: Specifying A Two-Sample Study Design</a></li>
  <li><a href="#results-for-the-sepsis-study" id="toc-results-for-the-sepsis-study" class="nav-link" data-scroll-target="#results-for-the-sepsis-study"> <span class="header-section-number">20.11</span> Results for the <code>sepsis</code> study</a>
  <ul class="collapse">
  <li><a href="#sepsis-estimation-results" id="toc-sepsis-estimation-results" class="nav-link" data-scroll-target="#sepsis-estimation-results"> <span class="header-section-number">20.11.1</span> Sepsis Estimation Results</a></li>
  </ul></li>
  <li><a href="#categorizing-the-outcome-and-comparing-rates" id="toc-categorizing-the-outcome-and-comparing-rates" class="nav-link" data-scroll-target="#categorizing-the-outcome-and-comparing-rates"> <span class="header-section-number">20.12</span> Categorizing the Outcome and Comparing Rates</a></li>
  <li><a href="#estimating-the-difference-in-proportions" id="toc-estimating-the-difference-in-proportions" class="nav-link" data-scroll-target="#estimating-the-difference-in-proportions"> <span class="header-section-number">20.13</span> Estimating the Difference in Proportions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-ibusepsis" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="setup-packages-used-here" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">20.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"data/Love-boost.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Epi)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In addition to the <code>Love-boost.R</code> script, we will also use the <code>favstats</code> function from the <code>mosaic</code> package.</p>
</section>
<section id="the-trial" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="the-trial"><span class="header-section-number">20.2</span> The Trial</h2>
<p>Our next study is a randomized controlled trial comparing ibuprofen vs.&nbsp;placebo in patients with sepsis, which uses an <em>independent samples</em> design to compare two samples of quantitative data. We will be working with a sample from the Ibuprofen in Sepsis study, which is also studied in <span class="citation" data-cites="Dupont">Dupont (<a href="references.html#ref-Dupont" role="doc-biblioref">2002</a>)</span>. Quoting the abstract from <span class="citation" data-cites="Bernard1997">Bernard et al. (<a href="references.html#ref-Bernard1997" role="doc-biblioref">1997</a>)</span>:</p>
<blockquote class="blockquote">
<p>Ibuprofen has been shown to have effects on sepsis in humans, but because of their small samples (fewer than 30 patients), previous studies have been inadequate to assess effects on mortality. We sought to determine whether ibuprofen can alter rates of organ failure and mortality in patients with the sepsis syndrome, how the drug affects the increased metabolic demand in sepsis (e.g., fever, tachypnea, tachycardia, hypoxemia, and lactic acidosis), and what potential adverse effects the drug has in the sepsis syndrome.</p>
</blockquote>
<p>In this study, patients meeting specific criteria (including elevated temperature) for a diagnosis of sepsis were recruited if they fulfilled an additional set of study criteria in the intensive care unit at one of seven participating centers.</p>
<p>The full trial involved 455 patients, of which our sample includes 300. 150 of our patients were randomly assigned to the Ibuprofen group and 150 to the Placebo group<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. I picked the <code>sepsis</code> sample we will work with excluding patients with missing values for our outcome of interest, and then selected a random sample of 150 Ibuprofen and 150 Placebo patients from the rest of the group, and converted the temperatures and changes from Fahrenheit to Celsius. The data are gathered in the <code>sepsis</code> data file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sepsis <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/sepsis.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the moment, we focus on two variables:</p>
<ul>
<li><strong>treat</strong>, which specifies the treatment group (intravenous Ibuprofen or intravenous Placebo), which was assigned via randomization to each patient, and</li>
<li><strong>temp_drop</strong>, the outcome of interest, measured as the change from baseline to 2 hours later in degrees Celsius. Positive values indicate improvement, that is, a <em>drop</em> in temperature over the 2 hours following the baseline measurement.</li>
</ul>
<p>The <code>sepsis.csv</code> file also contains each subject’s</p>
<ul>
<li><em>id</em>, which is just a code</li>
<li><em>race</em> (three levels: White, AfricanA or Other)</li>
<li><em>apache</em> = baseline APACHE II score, a severity of disease score ranging from 0 to 71 with higher scores indicating more severe disease and a higher mortality risk</li>
<li><em>temp_0</em> = baseline temperature, degrees Celsius.</li>
</ul>
<p>but for the moment, we won’t worry about those.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sepsis <span class="ot">&lt;-</span> sepsis <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">treat =</span> <span class="fu">factor</span>(treat),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">race =</span> <span class="fu">factor</span>(race))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sepsis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id                  treat           race         apache    
 Length:300         Ibuprofen:150   AfricanA: 80   Min.   : 0.0  
 Class :character   Placebo  :150   Other   : 23   1st Qu.:10.0  
 Mode  :character                   White   :197   Median :14.0  
                                                   Mean   :15.4  
                                                   3rd Qu.:20.0  
                                                   Max.   :35.0  
     temp_0        temp_drop      
 Min.   :33.10   Min.   :-2.7000  
 1st Qu.:37.48   1st Qu.:-0.1000  
 Median :38.20   Median : 0.3000  
 Mean   :38.00   Mean   : 0.3083  
 3rd Qu.:38.70   3rd Qu.: 0.7000  
 Max.   :41.70   Max.   : 3.1000  </code></pre>
</div>
</div>
</section>
<section id="comparing-two-groups" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="comparing-two-groups"><span class="header-section-number">20.3</span> Comparing Two Groups</h2>
<p>In making a choice between two alternatives, questions such as the following become paramount.</p>
<ul>
<li>Is there a status quo?</li>
<li>Is there a standard approach?</li>
<li>What are the costs of incorrect decisions?</li>
<li>Are such costs balanced?</li>
</ul>
<p>The process of comparing the means/medians/proportions/rates of the populations represented by two independently obtained samples can be challenging, and such an approach is not always the best choice. Often, specially designed experiments can be more informative at lower cost (i.e.&nbsp;smaller sample size). As one might expect, using these more sophisticated procedures introduces trade-offs, but the costs are typically small relative to the gain in information.</p>
<p>When faced with such a comparison of two alternatives, a test based on <strong>paired</strong> data is often much better than a test based on two distinct, independent samples. Why? If we have done our experiment properly, the pairing lets us eliminate background variation that otherwise hides meaningful differences.</p>
<section id="model-based-comparisons-and-anovaregression" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="model-based-comparisons-and-anovaregression"><span class="header-section-number">20.3.1</span> Model-Based Comparisons and ANOVA/Regression</h3>
<p>Comparisons based on independent samples of quantitative variables are also frequently accomplished through other equivalent methods, including the analysis of variance approach and dummy variable regression, both of which produce identical confidence intervals to the pooled variance t test for the same comparison.</p>
<p>We will also discuss some of the main ideas in developing, designing and analyzing statistical experiments, specifically in terms of making comparisons. The ideas we will present in this section allow for the comparison of more than two populations in terms of their population means. The statistical techniques employed analyze the sample variance in order to test and estimate the population means and for this reason the method is called the analysis of variance (ANOVA), and we will discuss this approach alone, and within the context of a linear regression model using dummy or indicator variables.</p>
</section>
</section>
<section id="key-questions-for-comparing-with-independent-samples" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="key-questions-for-comparing-with-independent-samples"><span class="header-section-number">20.4</span> Key Questions for Comparing with Independent Samples</h2>
<section id="what-is-the-population-under-study" class="level3" data-number="20.4.1">
<h3 data-number="20.4.1" class="anchored" data-anchor-id="what-is-the-population-under-study"><span class="header-section-number">20.4.1</span> What is the <strong>population</strong> under study?</h3>
<ul>
<li>All patients in the intensive care unit with sepsis who meet the inclusion and exclusion criteria of the study, at the entire population of health centers like the ones included in the trial.</li>
</ul>
</section>
<section id="what-is-the-sample-is-it-representative-of-the-population" class="level3" data-number="20.4.2">
<h3 data-number="20.4.2" class="anchored" data-anchor-id="what-is-the-sample-is-it-representative-of-the-population"><span class="header-section-number">20.4.2</span> What is the <strong>sample</strong>? Is it representative of the population?</h3>
<ul>
<li>The sample consists of 300 patients. It is a convenient sample from the population under study.</li>
<li>This is a randomized clinical trial. 150 of the patients were assigned to Ibuprofen, and the rest to Placebo. It is this treatment assignment that is randomized, not the selection of the sample as a whole.</li>
<li>In expectation, randomization of individuals to treatments, as in this study, should be expected to eliminate treatment selection bias.</li>
</ul>
</section>
<section id="who-are-the-subjects-individuals-within-the-sample" class="level3" data-number="20.4.3">
<h3 data-number="20.4.3" class="anchored" data-anchor-id="who-are-the-subjects-individuals-within-the-sample"><span class="header-section-number">20.4.3</span> Who are the subjects / <strong>individuals</strong> within the sample?</h3>
<ul>
<li>150 patients who received Ibuprofen and a completely different set of 150 patients who received Placebo.</li>
<li>There is no match or link between the patients. They are best thought of as independent samples.</li>
</ul>
</section>
<section id="what-data-are-available-on-each-individual" class="level3" data-number="20.4.4">
<h3 data-number="20.4.4" class="anchored" data-anchor-id="what-data-are-available-on-each-individual"><span class="header-section-number">20.4.4</span> What <strong>data</strong> are available on each individual?</h3>
<ul>
<li>The key variables are the treatment indicator (Ibuprofen or Placebo) and the outcome (drop in temperature in the 2 hours following administration of the randomly assigned treatment.)</li>
</ul>
</section>
<section id="rct-caveats" class="level3" data-number="20.4.5">
<h3 data-number="20.4.5" class="anchored" data-anchor-id="rct-caveats"><span class="header-section-number">20.4.5</span> RCT Caveats</h3>
<p>The placebo-controlled, double-blind randomized clinical trial, especially if pre-registered, is often considered the best feasible study for assessing the effectiveness of a treatment. While that’s not always true, it is a very solid design. The primary caveat is that the patients who are included in such trials are rarely excellent representations of the population of potentially affected patients as a whole.</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">20.5</span> Exploratory Data Analysis</h2>
<p>Consider the following boxplot with violin of the <code>temp_drop</code> data within each <code>treat</code> group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">x =</span> treat, <span class="at">y =</span> temp_drop, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Temperature Drop in Sepsis Patients"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Drop in Temperature (degrees C)"</span>) <span class="sc">+</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, we’ll consider faceted histograms of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">x =</span> temp_drop, <span class="at">fill =</span> treat, <span class="at">color =</span> treat)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_viridis_d</span>(<span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>, <span class="at">color =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograms of Temperature Drop in Sepsis Patients"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Drop in Temperature (degrees Celsius"</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> treat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/sepsis_temp_drop_by_treat_histograms-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here’s a pair of Normal Q-Q plots. It’s not hard to use a Normal model to approximate the Ibuprofen data, but such a model is probably not a good choice for the Placebo results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">sample =</span> temp_drop)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> treat) <span class="sc">+</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Temperature Drop Values (in degrees C)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We’ll could perhaps also look at a ridgeline plot, with some extra functions and theming from the <code>ggridges</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">x =</span> temp_drop, <span class="at">y =</span> treat, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density_ridges</span>(<span class="at">scale =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Temperature Drop in Sepsis Patients"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Drop in Temperature (degrees Celsius)"</span>, <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_ridges</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 0.182</code></pre>
</div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The center of the ibuprofen distribution is shifted a bit towards the more positive (greater improvement) direction, it seems, than is the distribution for the placebo patients. This conclusion matches what we see in some key numerical summaries, within the treatment groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      treat  min     Q1 median  Q3 max      mean        sd   n missing
1 Ibuprofen -1.5  0.000    0.5 0.9 3.1 0.4640000 0.6877919 150       0
2   Placebo -2.7 -0.175    0.1 0.4 1.9 0.1526667 0.5709637 150       0</code></pre>
</div>
</div>
</section>
<section id="estimating-the-difference-in-population-means" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="estimating-the-difference-in-population-means"><span class="header-section-number">20.6</span> Estimating the Difference in Population Means</h2>
<p>Next, we will build a point estimate and 90% confidence interval for the difference between the mean <code>temp_drop</code> if treated with Ibuprofen and the mean <code>temp_drop</code> if treated with Placebo. We’ll use a regression model with a single predictor (the <code>treat</code> group) to do this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>model_sep <span class="ot">&lt;-</span> <span class="fu">lm</span>(temp_drop <span class="sc">~</span> treat <span class="sc">==</span> <span class="st">"Ibuprofen"</span>, <span class="at">data =</span> sepsis)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_sep, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> std.error </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 0.153 </td>
   <td style="text-align:right;"> 0.052 </td>
   <td style="text-align:right;"> 2.958 </td>
   <td style="text-align:right;"> 0.003 </td>
   <td style="text-align:right;"> 0.068 </td>
   <td style="text-align:right;"> 0.238 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> treat == "Ibuprofen"TRUE </td>
   <td style="text-align:right;"> 0.311 </td>
   <td style="text-align:right;"> 0.073 </td>
   <td style="text-align:right;"> 4.266 </td>
   <td style="text-align:right;"> 0.000 </td>
   <td style="text-align:right;"> 0.191 </td>
   <td style="text-align:right;"> 0.432 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The point estimate for the “Ibuprofen - Placebo” difference in population means is 0.311 degrees C, and the 90% confidence interval is (0.191, 0.432) degrees C.</p>
<p>We could also have run the model like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model_sep2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_sep2, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> std.error </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 0.464 </td>
   <td style="text-align:right;"> 0.052 </td>
   <td style="text-align:right;"> 8.991 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.379 </td>
   <td style="text-align:right;"> 0.549 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> treatPlacebo </td>
   <td style="text-align:right;"> -0.311 </td>
   <td style="text-align:right;"> 0.073 </td>
   <td style="text-align:right;"> -4.266 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> -0.432 </td>
   <td style="text-align:right;"> -0.191 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>and would therefore conclude that the <em>Placebo - Ibuprofen</em> difference was estimated as -0.311, with 90% confidence interval (-0.432, -0.191), which is of course equivalent to our previous estimate.</p>
<p>Fundamentally, this regression model approach is identical to a <strong>two-sample t test, assuming equal population variances</strong>, also called a <strong>pooled t test</strong>. This is just one possible way for us to estimate the difference between population means, as it turns out.</p>
</section>
<section id="t-based-ci-for-population-mean1---mean2-difference" class="level2" data-number="20.7">
<h2 data-number="20.7" class="anchored" data-anchor-id="t-based-ci-for-population-mean1---mean2-difference"><span class="header-section-number">20.7</span> t-based CI for population mean1 - mean2 difference</h2>
<section id="the-pooled-t-procedure" class="level3" data-number="20.7.1">
<h3 data-number="20.7.1" class="anchored" data-anchor-id="the-pooled-t-procedure"><span class="header-section-number">20.7.1</span> The Pooled t procedure</h3>
<p>The most commonly used t-procedure for building a confidence interval assumes not only that each of the two populations being compared follows a Normal distribution, but also that they have the same population variance. This is the pooled t-test, and it is what people usually mean when they describe a two-sample t test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> sepsis,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.90</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">alt =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  temp_drop by treat
t = 4.2656, df = 298, p-value = 2.68e-05
alternative hypothesis: true difference in means between group Ibuprofen and group Placebo is not equal to 0
90 percent confidence interval:
 0.1909066 0.4317600
sample estimates:
mean in group Ibuprofen   mean in group Placebo 
              0.4640000               0.1526667 </code></pre>
</div>
</div>
<p>Or, we can use <code>tidy</code> on this object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tt1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> sepsis, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">conf.level =</span> <span class="fl">0.90</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">alt =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(tt1) <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> estimate1 </th>
   <th style="text-align:right;"> estimate2 </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> parameter </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:left;"> method </th>
   <th style="text-align:left;"> alternative </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 4.27 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 298 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.43 </td>
   <td style="text-align:left;"> Two Sample t-test </td>
   <td style="text-align:left;"> two.sided </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="using-linear-regression-to-obtain-a-pooled-t-confidence-interval" class="level3" data-number="20.7.2">
<h3 data-number="20.7.2" class="anchored" data-anchor-id="using-linear-regression-to-obtain-a-pooled-t-confidence-interval"><span class="header-section-number">20.7.2</span> Using linear regression to obtain a pooled t confidence interval</h3>
<p>As we’ve seen, and will demonstrate again below, a linear regression model, using the same outcome and predictor (group) as the pooled t procedure, produces the same confidence interval, again, under the assumption that the two populations we are comparing follow a Normal distribution with the same (population) variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term         estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)     0.464    0.0516      8.99 2.91e-17    0.379     0.549
2 treatPlacebo   -0.311    0.0730     -4.27 2.68e- 5   -0.432    -0.191</code></pre>
</div>
</div>
<p>We see that our point estimate from the linear regression model is that the difference in <code>temp_drop</code> is -0.3113333, where Ibuprofen subjects have higher <code>temp_drop</code> values than do Placebo subjects, and that the 90% confidence interval for this difference ranges from -0.43176 to -0.1909066.</p>
<p>We can obtain a t-based confidence interval for each of the parameter estimates in a linear model directly using <code>tidy</code> from the <code>broom</code> package. Linear models usually summarize only the estimate and standard error. Remember that a reasonable approximation in large samples to a 95% confidence interval for a regression estimate (slope or intercept) can be obtained from estimate plus or minus two times the standard error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model1, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> std.error </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 0.464 </td>
   <td style="text-align:right;"> 0.052 </td>
   <td style="text-align:right;"> 8.991 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.362 </td>
   <td style="text-align:right;"> 0.566 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> treatPlacebo </td>
   <td style="text-align:right;"> -0.311 </td>
   <td style="text-align:right;"> 0.073 </td>
   <td style="text-align:right;"> -4.266 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> -0.455 </td>
   <td style="text-align:right;"> -0.168 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>So, in the case of the <code>treatPlacebo</code> estimate, we can obtain an approximate 95% confidence interval with (-0.457, -0.165). Compare this to the 95% confidence interval available from the model directly, shown in the tidied output above, or with the <code>confint</code> command below, and you’ll see only a small difference.</p>
<p>Note that we can also use <code>summary</code> and <code>confint</code> to build our estimates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = temp_drop ~ treat, data = sepsis)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.85267 -0.36400 -0.05267  0.34733  2.63600 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.46400    0.05161   8.991  &lt; 2e-16 ***
treatPlacebo -0.31133    0.07299  -4.266 2.68e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6321 on 298 degrees of freedom
Multiple R-squared:  0.05755,   Adjusted R-squared:  0.05438 
F-statistic:  18.2 on 1 and 298 DF,  p-value: 2.68e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)   0.3624351  0.5655649
treatPlacebo -0.4549679 -0.1676988</code></pre>
</div>
</div>
</section>
<section id="the-welch-t-procedure" class="level3" data-number="20.7.3">
<h3 data-number="20.7.3" class="anchored" data-anchor-id="the-welch-t-procedure"><span class="header-section-number">20.7.3</span> The Welch t procedure</h3>
<p>The default confidence interval based on the t test for independent samples in R uses something called the Welch test, in which the two populations being compared are not assumed to have the same variance. Each population is assumed to follow a Normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis, <span class="at">conf.level =</span> <span class="fl">0.90</span>, <span class="at">alt =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  temp_drop by treat
t = 4.2656, df = 288.24, p-value = 2.706e-05
alternative hypothesis: true difference in means between group Ibuprofen and group Placebo is not equal to 0
90 percent confidence interval:
 0.1908939 0.4317728
sample estimates:
mean in group Ibuprofen   mean in group Placebo 
              0.4640000               0.1526667 </code></pre>
</div>
</div>
<p>Tidying works in this situation, too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>tt0 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> sepsis, <span class="at">conf.level =</span> <span class="fl">0.90</span>, <span class="at">alt =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(tt0) <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> estimate1 </th>
   <th style="text-align:right;"> estimate2 </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> parameter </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:left;"> method </th>
   <th style="text-align:left;"> alternative </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 4.27 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 288.24 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.43 </td>
   <td style="text-align:left;"> Welch Two Sample t-test </td>
   <td style="text-align:left;"> two.sided </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>When there is a <em>balanced design</em>, that is, when the same number of observations appear in each of the two samples, then the Welch t test and the Pooled t test produce the same confidence interval. Differences appear if the sample sizes in the two groups being compared are different.</p>
</section>
</section>
<section id="wilcoxon-mann-whitney-rank-sum-ci" class="level2" data-number="20.8">
<h2 data-number="20.8" class="anchored" data-anchor-id="wilcoxon-mann-whitney-rank-sum-ci"><span class="header-section-number">20.8</span> Wilcoxon-Mann-Whitney “Rank Sum” CI</h2>
<p>As in the one-sample case, a rank-based alternative attributed to Wilcoxon (and sometimes to Mann and Whitney) provides a two-sample comparison of the pseudomedians in the two <code>treat</code> groups in terms of <code>temp_drop</code>. This is called a <strong>rank sum</strong> test, rather than the Wilcoxon <strong>signed rank</strong> test that is used for inference about a single sample. Here’s the resulting 90% confidence interval for the difference in pseudomedians.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>wt <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alt =</span> <span class="st">"two.sided"</span>) </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>wt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  temp_drop by treat
W = 14614, p-value = 7.281e-06
alternative hypothesis: true location shift is not equal to 0
90 percent confidence interval:
 0.1999699 0.4000330
sample estimates:
difference in location 
             0.3000368 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(wt) <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> statistic </th>
   <th style="text-align:right;"> p.value </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:left;"> method </th>
   <th style="text-align:left;"> alternative </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 0.3 </td>
   <td style="text-align:right;"> 14614.5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.2 </td>
   <td style="text-align:right;"> 0.4 </td>
   <td style="text-align:left;"> Wilcoxon rank sum test with continuity correction </td>
   <td style="text-align:left;"> two.sided </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="bootstrapping-a-more-robust-approach" class="level2" data-number="20.9">
<h2 data-number="20.9" class="anchored" data-anchor-id="bootstrapping-a-more-robust-approach"><span class="header-section-number">20.9</span> Bootstrapping: A More Robust Approach</h2>
<p>Within a script called <code>Love-boost.R</code>, I have provided the following R code to create a function called <code>bootdif</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>bootdif <span class="ot">&lt;-</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(y, g, <span class="at">conf.level=</span><span class="fl">0.95</span>, <span class="at">B.reps =</span> <span class="dv">2000</span>) {</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    lowq <span class="ot">=</span> (<span class="dv">1</span> <span class="sc">-</span> conf.level)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    g <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(g)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">attr</span>(Hmisc<span class="sc">::</span><span class="fu">smean.cl.boot</span>(y[g<span class="sc">==</span><span class="fu">levels</span>(g)[<span class="dv">1</span>]], <span class="at">B=</span>B.reps, <span class="at">reps=</span><span class="cn">TRUE</span>),<span class="st">'reps'</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">attr</span>(Hmisc<span class="sc">::</span><span class="fu">smean.cl.boot</span>(y[g<span class="sc">==</span><span class="fu">levels</span>(g)[<span class="dv">2</span>]], <span class="at">B=</span>B.reps, <span class="at">reps=</span><span class="cn">TRUE</span>),<span class="st">'reps'</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    meandif <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">tapply</span>(y, g, mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    a.b <span class="ot">&lt;-</span> <span class="fu">quantile</span>(b<span class="sc">-</span>a, <span class="fu">c</span>(lowq,<span class="dv">1</span><span class="sc">-</span>lowq))</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> <span class="fu">c</span>(meandif, a.b)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">names</span>(res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Mean Difference'</span>,lowq, <span class="dv">1</span><span class="sc">-</span>lowq)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    res</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Running this code will place a new function called <code>bootdif</code> in your environment, which will help us calculate an appropriate confidence interval using a bootstrap procedure. The <code>bootdif</code> function contained in the <code>Love-boost.R</code> script is a slightly edited version of the function at http://biostat.mc.vanderbilt.edu/wiki/Main/BootstrapMeansSoftware.</p>
<section id="bootstrap-ci-for-the-sepsis-study" class="level3" data-number="20.9.1">
<h3 data-number="20.9.1" class="anchored" data-anchor-id="bootstrap-ci-for-the-sepsis-study"><span class="header-section-number">20.9.1</span> Bootstrap CI for the Sepsis study</h3>
<p>Note that this approach uses a comma to separate the outcome variable (here, <code>temp_drop</code>) from the variable identifying the exposure groups (here, <code>treat</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">431212</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bootdif</span>(sepsis<span class="sc">$</span>temp_drop, sepsis<span class="sc">$</span>treat, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Difference            0.05            0.95 
     -0.3113333      -0.4313667      -0.1833000 </code></pre>
</div>
</div>
<p>This approach calculates a 90% confidence interval for the difference in means between the two treatment groups. Note that the sign is in the opposite direction from what we’ve seen in our previous work. We can tell from the mean difference (and the summarized means from the data in each group) that this approach is finding a confidence interval using a bootstrap procedure for the Placebo - Ibuprofen difference, specifically (-0.431, -0.183).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      treat  min     Q1 median  Q3 max      mean        sd   n missing
1 Ibuprofen -1.5  0.000    0.5 0.9 3.1 0.4640000 0.6877919 150       0
2   Placebo -2.7 -0.175    0.1 0.4 1.9 0.1526667 0.5709637 150       0</code></pre>
</div>
</div>
<p>To find a confidence interval using this bootstrap approach for the Ibuprofen - Placebo difference, we just need to switch the signs, and conclude that the 90% bootstrap confidence interval for that difference would be (0.183, 0.431).</p>
</section>
</section>
<section id="summary-specifying-a-two-sample-study-design" class="level2" data-number="20.10">
<h2 data-number="20.10" class="anchored" data-anchor-id="summary-specifying-a-two-sample-study-design"><span class="header-section-number">20.10</span> Summary: Specifying A Two-Sample Study Design</h2>
<p>These questions will help specify the details of the study design involved in any comparison of two populations on a quantitative outcome, perhaps with means.</p>
<ol type="1">
<li>What is the outcome under study?</li>
<li>What are the (in this case, two) treatment/exposure groups?</li>
<li>Were the data collected using matched / paired samples or independent samples?</li>
<li>Are the data a random sample from the population(s) of interest? Or is there at least a reasonable argument for generalizing from the sample to the population(s)?</li>
<li>What is the significance level (or, the confidence level) we require here?</li>
<li>Are we doing one-sided or two-sided testing/confidence interval generation?</li>
<li>If we have paired samples, did pairing help reduce nuisance variation?</li>
<li>If we have paired samples, what does the distribution of sample paired differences tell us about which inferential procedure to use?</li>
<li>If we have independent samples, what does the distribution of each individual sample tell us about which inferential procedure to use?</li>
</ol>
</section>
<section id="results-for-the-sepsis-study" class="level2" data-number="20.11">
<h2 data-number="20.11" class="anchored" data-anchor-id="results-for-the-sepsis-study"><span class="header-section-number">20.11</span> Results for the <code>sepsis</code> study</h2>
<ol type="1">
<li>The outcome is <code>temp_drop</code>, the change in body temperature (in <span class="math inline">\(^{\circ}\)</span>C) from baseline to 2 hours later, so that positive numbers indicate drops in temperature (a good outcome.)</li>
<li>The groups are <strong>Ibuprofen</strong> and <strong>Placebo</strong> as contained in the <code>treat</code> variable in the <code>sepsis</code> tibble.</li>
<li>The data were collected using independent samples. The Ibuprofen subjects are not matched or linked to individual Placebo subjects - they are separate groups.</li>
<li>The subjects of the study aren’t drawn from a random sample of the population of interest, but they are randomly assigned to their respective treatments (Ibuprofen and Placebo) which will provide the reasoned basis for our inferences.</li>
<li>We’ll use a 10% significance level (or 90% confidence level) in this setting, as we did in our previous work on these data.</li>
<li>We’ll use a two-sided testing and confidence interval approach.</li>
</ol>
<p>Questions 7 and 8 don’t apply, because these are independent samples of data, rather than paired samples.</p>
<p>To address question 9, we’ll need to look at the data in each sample, as we did previously to allow us to assess the Normality of the distributions of (separately) the <code>temp_drop</code> results in the Ibuprofen and Placebo groups. We’ll repeat those below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">x =</span> treat, <span class="at">y =</span> temp_drop, <span class="at">fill =</span> treat)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, <span class="at">geom =</span> <span class="st">"point"</span>, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_d</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Temperature Drop in Sepsis Patients"</span>,</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Drop in Temperature (degrees C)"</span>) <span class="sc">+</span> </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sepsis, <span class="fu">aes</span>(<span class="at">sample =</span> temp_drop)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> treat) <span class="sc">+</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Temperature Drop Values (in degrees C)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="20-ibuprofen_sepsis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From these plots we conclude that the data in the Ibuprofen sample follow a reasonably Normal distribution, but this isn’t quite as true for the Placebo sample. It’s hard to know whether the apparent Placebo group outliers will affect whether the Normal distribution assumption is reasonable, so we can see if the confidence intervals change much when we <em>don’t</em> assume Normality (for instance, comparing the bootstrap to the t-based approaches), as a way of understanding whether a Normal model has a large impact on our conclusions.</p>
<section id="sepsis-estimation-results" class="level3" data-number="20.11.1">
<h3 data-number="20.11.1" class="anchored" data-anchor-id="sepsis-estimation-results"><span class="header-section-number">20.11.1</span> Sepsis Estimation Results</h3>
<p>Here’s a set of confidence interval estimates (we’ll use 90% confidence here) using the methods discussed in this Chapter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      treat  min     Q1 median  Q3 max      mean        sd   n missing
1 Ibuprofen -1.5  0.000    0.5 0.9 3.1 0.4640000 0.6877919 150       0
2   Placebo -2.7 -0.175    0.1 0.4 1.9 0.1526667 0.5709637 150       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>s_pooled_t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis, <span class="at">conf.level =</span> <span class="fl">0.90</span>, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">alt =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(s_pooled_t_test) <span class="sc">|&gt;</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;
1    0.191     0.432</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>s_welch_t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis, <span class="at">conf.level =</span> <span class="fl">0.90</span>,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">alt =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(s_welch_t_test) <span class="sc">|&gt;</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(estimate, conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  estimate conf.low conf.high
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1    0.311    0.191     0.432</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>s_wilcoxon_test <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(temp_drop <span class="sc">~</span> treat, <span class="at">data =</span> sepsis, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">alt =</span> <span class="st">"two.sided"</span>) </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(s_wilcoxon_test) <span class="sc">|&gt;</span> </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(estimate, conf.low, conf.high)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  estimate conf.low conf.high
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1    0.300    0.200     0.400</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">431212</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>s_bootstrap <span class="ot">&lt;-</span> <span class="fu">bootdif</span>(sepsis<span class="sc">$</span>temp_drop, sepsis<span class="sc">$</span>treat, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>s_bootstrap</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean Difference            0.05            0.95 
     -0.3113333      -0.4313667      -0.1833000 </code></pre>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Procedure</th>
<th style="text-align: right;">Compares…</th>
<th style="text-align: right;">Point Estimate</th>
<th style="text-align: right;">90% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Pooled t</td>
<td style="text-align: right;">Means</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">(0.191, 0.432)</td>
</tr>
<tr class="even">
<td style="text-align: right;">Welch t</td>
<td style="text-align: right;">Means</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">(0.191, 0.432)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Bootstrap</td>
<td style="text-align: right;">Means</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">(0.183, 0.431)</td>
</tr>
<tr class="even">
<td style="text-align: right;">Wilcoxon rank sum</td>
<td style="text-align: right;">Pseudo-Medians</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">(0.2, 0.4)</td>
</tr>
</tbody>
</table>
<p>What conclusions can we draw in this setting?</p>
</section>
</section>
<section id="categorizing-the-outcome-and-comparing-rates" class="level2" data-number="20.12">
<h2 data-number="20.12" class="anchored" data-anchor-id="categorizing-the-outcome-and-comparing-rates"><span class="header-section-number">20.12</span> Categorizing the Outcome and Comparing Rates</h2>
<p>Suppose we were interested in comparing the percentage of patients in each arm of the trial (Ibuprofen vs.&nbsp;Placebo) that showed an improvement in their temperature (<code>temp_drop</code> &gt; 0). To build the cross-tabulation of interest, we could create a new variable, called <code>dropped</code> which indicates whether the subject’s temperature dropped, and then use <code>tabyl</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>sepsis <span class="ot">&lt;-</span> sepsis <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">dropped =</span> <span class="fu">ifelse</span>(temp_drop <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Drop"</span>, <span class="st">"No Drop"</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>sepsis <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(treat, dropped)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     treat Drop No Drop
 Ibuprofen  107      43
   Placebo   80      70</code></pre>
</div>
</div>
<p>Our primary interest is in comparing the percentage of Ibuprofen patients whose temperature dropped to the percentage of Placebo patients whose temperature dropped.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sepsis <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(treat, dropped) <span class="sc">|&gt;</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>() <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_percentages</span>(<span class="at">denom =</span> <span class="st">"row"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_ns</span>(<span class="at">position =</span> <span class="st">"front"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     treat        Drop     No Drop
 Ibuprofen 107 (71.3%)  43 (28.7%)
   Placebo  80 (53.3%)  70 (46.7%)
     Total 187 (62.3%) 113 (37.7%)</code></pre>
</div>
</div>
</section>
<section id="estimating-the-difference-in-proportions" class="level2" data-number="20.13">
<h2 data-number="20.13" class="anchored" data-anchor-id="estimating-the-difference-in-proportions"><span class="header-section-number">20.13</span> Estimating the Difference in Proportions</h2>
<p>In our sample, 71.3% of the Ibuprofen subjects, and 53.3% of the Placebo subjects, experienced a drop in temperature. So our <em>point estimate</em> of the difference in percentages would be 18.0 percentage points, but we will usually set this instead in terms of proportions, so that the difference is 0.180.</p>
<p>Now, we’ll find a confidence interval for that difference, which we can do in several ways, including the <code>twoby2</code> function in the <code>Epi</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(sepsis<span class="sc">$</span>treat, sepsis<span class="sc">$</span>dropped) <span class="sc">|&gt;</span> <span class="fu">twoby2</span>(<span class="at">alpha =</span> <span class="fl">0.10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Drop 
Comparing : Ibuprofen vs. Placebo 

          Drop No Drop    P(Drop) 90% conf. interval
Ibuprofen  107      43     0.7133    0.6490   0.7701
Placebo     80      70     0.5333    0.4661   0.5993

                                   90% conf. interval
             Relative Risk: 1.3375    1.1492   1.5567
         Sample Odds Ratio: 2.1773    1.4583   3.2509
Conditional MLE Odds Ratio: 2.1716    1.4177   3.3437
    Probability difference: 0.1800    0.0881   0.2677

             Exact P-value: 0.0019 
        Asymptotic P-value: 0.0014 
------------------------------------------------------</code></pre>
</div>
</div>
<p>While there is a lot of additional output here, we’ll look for now just at the Probability difference row, where we see the point estimate (0.180) and the 90% confidence interval estimate for the difference in proportions (0.088, 0.268) comparing Ibuprofen vs.&nbsp;Placebo for the outcome of Dropping in Temperature.</p>
<p>More on estimation of the difference in population proportions will be found later.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Bernard1997" class="csl-entry" role="doc-biblioentry">
Bernard, Gordon R., Arthur P. Wheeler, James A. Russell, Roland Schein, Warren R. Summer, Kenneth P. Steinberg, William J. Fulkerson, et al. 1997. <span>“The Effects of Ibuprofen on the Physiology and Survival of Patients with Sepsis.”</span> <em>New England Journal of Medicine</em> 336: 912–18. <a href="http://www.nejm.org/doi/full/10.1056/NEJM199703273361303#t=article">http://www.nejm.org/doi/full/10.1056/NEJM199703273361303#t=article</a>.
</div>
<div id="ref-Dupont" class="csl-entry" role="doc-biblioentry">
Dupont, William D. 2002. <em>Statistical Modeling for Biomedical Researchers</em>. New York: Cambridge University Press.
</div>
</div>
</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1" role="doc-endnote"><p>This was a <em>double-blind</em> study, where neither the patients nor their care providers know, during the execution of the trial, what intervention group was assigned to each patient.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./19-ci_for_mean.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./21-pairedsamples.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>