<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notes for 431 - 25&nbsp; Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./26-mult_reg_intro.html" rel="next">
<link href="./24-contingency_tables.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">NHANES: A First Look</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Structures, Variable Types &amp; Sampling NHANES</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Visualizing NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assessingnormality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-anova.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-regr_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-prediction_wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">25.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#national-youth-fitness-survey" id="toc-national-youth-fitness-survey" class="nav-link" data-scroll-target="#national-youth-fitness-survey"> <span class="header-section-number">25.2</span> National Youth Fitness Survey</a></li>
  <li><a href="#comparing-gross-motor-quotient-scores-by-income-level-3-categories" id="toc-comparing-gross-motor-quotient-scores-by-income-level-3-categories" class="nav-link" data-scroll-target="#comparing-gross-motor-quotient-scores-by-income-level-3-categories"> <span class="header-section-number">25.3</span> Comparing Gross Motor Quotient Scores by Income Level (3 Categories)</a></li>
  <li><a href="#alternative-procedures-for-comparing-more-than-two-means" id="toc-alternative-procedures-for-comparing-more-than-two-means" class="nav-link" data-scroll-target="#alternative-procedures-for-comparing-more-than-two-means"> <span class="header-section-number">25.4</span> Alternative Procedures for Comparing More Than Two Means</a>
  <ul class="collapse">
  <li><a href="#extending-the-welch-test-to-2-independent-samples" id="toc-extending-the-welch-test-to-2-independent-samples" class="nav-link" data-scroll-target="#extending-the-welch-test-to-2-independent-samples"> <span class="header-section-number">25.4.1</span> Extending the Welch Test to &gt; 2 Independent Samples</a></li>
  <li><a href="#extending-the-rank-sum-test-to-2-independent-samples" id="toc-extending-the-rank-sum-test-to-2-independent-samples" class="nav-link" data-scroll-target="#extending-the-rank-sum-test-to-2-independent-samples"> <span class="header-section-number">25.4.2</span> Extending the Rank Sum Test to &gt; 2 Independent Samples</a></li>
  <li><a href="#can-we-use-the-bootstrap-to-compare-more-than-two-means" id="toc-can-we-use-the-bootstrap-to-compare-more-than-two-means" class="nav-link" data-scroll-target="#can-we-use-the-bootstrap-to-compare-more-than-two-means"> <span class="header-section-number">25.4.3</span> Can we use the bootstrap to compare more than two means?</a></li>
  </ul></li>
  <li><a href="#the-analysis-of-variance" id="toc-the-analysis-of-variance" class="nav-link" data-scroll-target="#the-analysis-of-variance"> <span class="header-section-number">25.5</span> The Analysis of Variance</a>
  <ul class="collapse">
  <li><a href="#the-oneway.test-approach" id="toc-the-oneway.test-approach" class="nav-link" data-scroll-target="#the-oneway.test-approach"> <span class="header-section-number">25.5.1</span> The <code>oneway.test</code> approach</a></li>
  <li><a href="#using-the-aov-approach-and-the-summary-function" id="toc-using-the-aov-approach-and-the-summary-function" class="nav-link" data-scroll-target="#using-the-aov-approach-and-the-summary-function"> <span class="header-section-number">25.5.2</span> Using the <code>aov</code> approach and the <code>summary</code> function</a></li>
  <li><a href="#using-the-anova-function-after-fitting-a-linear-model" id="toc-using-the-anova-function-after-fitting-a-linear-model" class="nav-link" data-scroll-target="#using-the-anova-function-after-fitting-a-linear-model"> <span class="header-section-number">25.5.3</span> Using the <code>anova</code> function after fitting a linear model</a></li>
  </ul></li>
  <li><a href="#interpreting-the-anova-table" id="toc-interpreting-the-anova-table" class="nav-link" data-scroll-target="#interpreting-the-anova-table"> <span class="header-section-number">25.6</span> Interpreting the ANOVA Table</a>
  <ul class="collapse">
  <li><a href="#what-are-we-testing" id="toc-what-are-we-testing" class="nav-link" data-scroll-target="#what-are-we-testing"> <span class="header-section-number">25.6.1</span> What are we Testing?</a></li>
  <li><a href="#elements-of-the-anova-table" id="toc-elements-of-the-anova-table" class="nav-link" data-scroll-target="#elements-of-the-anova-table"> <span class="header-section-number">25.6.2</span> Elements of the ANOVA Table</a></li>
  <li><a href="#the-degrees-of-freedom" id="toc-the-degrees-of-freedom" class="nav-link" data-scroll-target="#the-degrees-of-freedom"> <span class="header-section-number">25.6.3</span> The Degrees of Freedom</a></li>
  <li><a href="#the-sums-of-squares" id="toc-the-sums-of-squares" class="nav-link" data-scroll-target="#the-sums-of-squares"> <span class="header-section-number">25.6.4</span> The Sums of Squares</a></li>
  <li><a href="#the-mean-square" id="toc-the-mean-square" class="nav-link" data-scroll-target="#the-mean-square"> <span class="header-section-number">25.6.5</span> The Mean Square</a></li>
  <li><a href="#the-f-test-statistic-and-p-value" id="toc-the-f-test-statistic-and-p-value" class="nav-link" data-scroll-target="#the-f-test-statistic-and-p-value"> <span class="header-section-number">25.6.6</span> The F Test Statistic and <em>p</em> Value</a></li>
  </ul></li>
  <li><a href="#the-residual-standard-error" id="toc-the-residual-standard-error" class="nav-link" data-scroll-target="#the-residual-standard-error"> <span class="header-section-number">25.7</span> The Residual Standard Error</a></li>
  <li><a href="#the-proportion-of-variance-explained-by-the-factor" id="toc-the-proportion-of-variance-explained-by-the-factor" class="nav-link" data-scroll-target="#the-proportion-of-variance-explained-by-the-factor"> <span class="header-section-number">25.8</span> The Proportion of Variance Explained by the Factor</a></li>
  <li><a href="#the-regression-approach-to-compare-population-means-based-on-independent-samples" id="toc-the-regression-approach-to-compare-population-means-based-on-independent-samples" class="nav-link" data-scroll-target="#the-regression-approach-to-compare-population-means-based-on-independent-samples"> <span class="header-section-number">25.9</span> The Regression Approach to Compare Population Means based on Independent Samples</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-regression-output" id="toc-interpreting-the-regression-output" class="nav-link" data-scroll-target="#interpreting-the-regression-output"> <span class="header-section-number">25.9.1</span> Interpreting the Regression Output</a></li>
  <li><a href="#the-full-anova-table" id="toc-the-full-anova-table" class="nav-link" data-scroll-target="#the-full-anova-table"> <span class="header-section-number">25.9.2</span> The Full ANOVA Table</a></li>
  <li><a href="#anova-assumptions" id="toc-anova-assumptions" class="nav-link" data-scroll-target="#anova-assumptions"> <span class="header-section-number">25.9.3</span> ANOVA Assumptions</a></li>
  </ul></li>
  <li><a href="#equivalent-approach-to-get-anova-results" id="toc-equivalent-approach-to-get-anova-results" class="nav-link" data-scroll-target="#equivalent-approach-to-get-anova-results"> <span class="header-section-number">25.10</span> Equivalent approach to get ANOVA Results</a></li>
  <li><a href="#the-problem-of-multiple-comparisons" id="toc-the-problem-of-multiple-comparisons" class="nav-link" data-scroll-target="#the-problem-of-multiple-comparisons"> <span class="header-section-number">25.11</span> The Problem of Multiple Comparisons</a>
  <ul class="collapse">
  <li><a href="#the-bonferroni-solution" id="toc-the-bonferroni-solution" class="nav-link" data-scroll-target="#the-bonferroni-solution"> <span class="header-section-number">25.11.1</span> The Bonferroni solution</a></li>
  <li><a href="#pairwise-comparisons-using-tukeys-hsd-method" id="toc-pairwise-comparisons-using-tukeys-hsd-method" class="nav-link" data-scroll-target="#pairwise-comparisons-using-tukeys-hsd-method"> <span class="header-section-number">25.11.2</span> Pairwise Comparisons using Tukey’s HSD Method</a></li>
  <li><a href="#plotting-the-tukey-hsd-results" id="toc-plotting-the-tukey-hsd-results" class="nav-link" data-scroll-target="#plotting-the-tukey-hsd-results"> <span class="header-section-number">25.11.3</span> Plotting the Tukey HSD results</a></li>
  </ul></li>
  <li><a href="#what-if-we-consider-another-outcome-bmi" id="toc-what-if-we-consider-another-outcome-bmi" class="nav-link" data-scroll-target="#what-if-we-consider-another-outcome-bmi"> <span class="header-section-number">25.12</span> What if we consider another outcome, BMI?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="setup-packages-used-here" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">25.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will also use functions from the <code>ggridges</code> and <code>mosaic</code> packages.</p>
</section>
<section id="national-youth-fitness-survey" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="national-youth-fitness-survey"><span class="header-section-number">25.2</span> National Youth Fitness Survey</h2>
<p>Recall the National Youth Fitness Survey, which we explored a small piece of in some detail earlier in these notes. We’ll look at a different part of the same survey here - specifically the 280 children whose data are captured in the <code>nyfs2</code> file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nyfs2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/nyfs2.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>nyfs2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 280 × 21
   subje…¹ sex   age.e…² race.…³ english incom…⁴ incom…⁵ inc.t…⁶ weigh…⁷ heigh…⁸
     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   73228 Male        4 5 Othe…       1 Low (b… 0 to 4…    0       17     104. 
 2   72393 Male        4 2 Non-…       1 Low (b… 0 to 4…    0       16.4   102. 
 3   73303 Male        3 2 Non-…       1 Low (b… 0 to 4…    0.16    16.4    98.7
 4   72786 Male        5 1 Non-…       1 Low (b… 0 to 4…    0.04    19.1   114. 
 5   73048 Male        3 2 Non-…       1 Low (b… 0 to 4…    0.17    14      93.8
 6   72556 Fema…       4 2 Non-…       1 Low (b… 0 to 4…    0.06    20.8   106. 
 7   72580 Fema…       5 2 Non-…       1 Low (b… 0 to 4…    0.17    18     107. 
 8   72532 Fema…       4 4 Othe…       0 Low (b… 0 to 4…    0.02    16.7   101. 
 9   73012 Male        4 1 Non-…       1 Low (b… 0 to 4…    0.21    19.8   106. 
10   72099 Male        6 1 Non-…       1 Low (b… 0 to 4…    0.2     31.4   121. 
# … with 270 more rows, 11 more variables: bmi &lt;dbl&gt;, bmi.group &lt;dbl&gt;,
#   bmi.cat &lt;chr&gt;, arm.length &lt;dbl&gt;, arm.circ &lt;dbl&gt;, waist.circ &lt;dbl&gt;,
#   calf.circ &lt;dbl&gt;, calf.skinfold &lt;dbl&gt;, triceps.skinfold &lt;dbl&gt;,
#   subscap.skinfold &lt;dbl&gt;, GMQ &lt;dbl&gt;, and abbreviated variable names
#   ¹​subject.id, ²​age.exam, ³​race.eth, ⁴​income.cat3, ⁵​income.detail,
#   ⁶​inc.to.pov, ⁷​weight.kg, ⁸​height.cm
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
</section>
<section id="comparing-gross-motor-quotient-scores-by-income-level-3-categories" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="comparing-gross-motor-quotient-scores-by-income-level-3-categories"><span class="header-section-number">25.3</span> Comparing Gross Motor Quotient Scores by Income Level (3 Categories)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nyfs2a <span class="ot">&lt;-</span> nyfs2 <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(subject.id, income.cat3, GMQ) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(subject.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this first analysis, we’ll compare the population mean on the Gross Motor Quotient evaluation of these kids across three groups defined by income level. Higher values of this GMQ measure indicate improved levels of gross motor development, both in terms of locomotor and object control. See https://wwwn.cdc.gov/Nchs/Nnyfs/Y_GMX.htm for more details.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nyfs2a <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(income.cat3) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="fu">mean</span>(GMQ), <span class="fu">median</span>(GMQ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  income.cat3            n `mean(GMQ)` `median(GMQ)`
  &lt;chr&gt;              &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;
1 High (65K or more)    92        95.7            97
2 Low (below 25K)       98        97.0            97
3 Middle (25 - 64K)     90        95.4            94</code></pre>
</div>
</div>
<p>Uh, oh. We should rearrange those income categories to match a natural order from low to high.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nyfs2a<span class="sc">$</span>income.cat3 <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fct_relevel</span>(nyfs2a<span class="sc">$</span>income.cat3,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Low (below 25K)"</span>, <span class="st">"Middle (25 - 64K)"</span>, <span class="st">"High (65K or more)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When working with three independent samples, I use graphs analogous to those we built for two independent samples.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nyfs2a, <span class="fu">aes</span>(<span class="at">x =</span> income.cat3, <span class="at">y =</span> GMQ, <span class="at">fill =</span> income.cat3)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> income.cat3), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">notch =</span> <span class="cn">TRUE</span>, <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">"none"</span>, <span class="at">col =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"GMQ Scores for 280 Children in NNYFS"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"GMQ Score, in points"</span>, <span class="at">x =</span> <span class="st">"Income Category"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/boxplot_nyfs2a-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In addition to this comparison boxplot, we might consider faceted plots, like these histograms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nyfs2a, <span class="fu">aes</span>(<span class="at">x =</span> GMQ, <span class="at">fill =</span> income.cat3)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">col =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> income.cat3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt; =
"none")` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/histograms_nyfs2a-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Or, if we want to ignore the (modest) sample size differences, we might consider density functions, perhaps through a ridgeline plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nyfs2a, <span class="fu">aes</span>(<span class="at">x =</span> GMQ, <span class="at">y =</span> income.cat3, <span class="at">fill =</span> income.cat3)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    ggridges<span class="sc">::</span><span class="fu">geom_density_ridges</span>(<span class="at">scale =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"GMQ Score (in points) by Income Group"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"GMQ Score"</span>, <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    ggridges<span class="sc">::</span><span class="fu">theme_ridges</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt; =
"none")` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/nyfs2a_ridgelineplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">by</span>(nyfs2a<span class="sc">$</span>GMQ, nyfs2a<span class="sc">$</span>income.cat3, mosaic<span class="sc">::</span>favstats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>nyfs2a$income.cat3: Low (below 25K)
 min Q1 median  Q3 max     mean       sd  n missing
  55 91     97 106 130 97.03061 14.79444 98       0
------------------------------------------------------------ 
nyfs2a$income.cat3: Middle (25 - 64K)
 min Q1 median  Q3 max     mean       sd  n missing
  67 85     94 106 136 95.36667 14.15123 90       0
------------------------------------------------------------ 
nyfs2a$income.cat3: High (65K or more)
 min Q1 median  Q3 max     mean       sd  n missing
  64 85     97 103 145 95.72826 14.49525 92       0</code></pre>
</div>
</div>
</section>
<section id="alternative-procedures-for-comparing-more-than-two-means" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="alternative-procedures-for-comparing-more-than-two-means"><span class="header-section-number">25.4</span> Alternative Procedures for Comparing More Than Two Means</h2>
<p>Now, if we only had two independent samples, we’d be choosing between a pooled t test, a Welch t test, and a non-parametric procedure like the Wilcoxon-Mann-Whitney rank sum test, or even perhaps a bootstrap alternative.</p>
<p>In the case of more than two independent samples, we have methods analogous to the Welch test, and the rank sum test, and even the bootstrap, but we’re going to be far more likely to select the <strong>analysis of variance</strong> (ANOVA) or an equivalent regression-based approach. These are the extensions of the pooled t test. Unless the sample outcome data are very clearly not Normally distributed, and no transformation is available which makes them appear approximately Normal in all of the groups we are comparing, we will stick with ANOVA.</p>
<section id="extending-the-welch-test-to-2-independent-samples" class="level3" data-number="25.4.1">
<h3 data-number="25.4.1" class="anchored" data-anchor-id="extending-the-welch-test-to-2-independent-samples"><span class="header-section-number">25.4.1</span> Extending the Welch Test to &gt; 2 Independent Samples</h3>
<p>It is possible to extend the Welch two-sample t test (not assuming equal population variances) into an analogous one-factor analysis for comparing population means based on independent samples from more than two groups.</p>
<p>If we want to compare the population mean GMQ levels across those three income groups without assuming equal population variances, <code>oneway.test</code> is up to the task. The hypotheses being tested here are:</p>
<ul>
<li>H0: All three means are the same vs.</li>
<li>HA: At least one of the population means is different than the others.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oneway.test</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One-way analysis of means (not assuming equal variances)

data:  GMQ and income.cat3
F = 0.3416, num df = 2.00, denom df = 184.41, p-value = 0.7111</code></pre>
</div>
</div>
<p>We get a p value, but this isn’t much help, though, because we don’t have any measure of effect size, nor do we have any confidence intervals. Like the analogous Welch t test, this approach allows us to forego the assumption of equal population variances in each of the three income groups, but it still requires us to assume that the populations are Normally distributed.</p>
<p>That said, most of the time when we have more than two levels of the factor of interest, we won’t bother worrying about the equal population variance assumption, and will just use the one-factor ANOVA approach (with pooled variances) described below, to make the comparisons of interest.</p>
</section>
<section id="extending-the-rank-sum-test-to-2-independent-samples" class="level3" data-number="25.4.2">
<h3 data-number="25.4.2" class="anchored" data-anchor-id="extending-the-rank-sum-test-to-2-independent-samples"><span class="header-section-number">25.4.2</span> Extending the Rank Sum Test to &gt; 2 Independent Samples</h3>
<p>It is also possible to extend the Wilcoxon-Mann-Whitney two-sample test into an analogous one-factor analysis called the <strong>Kruskal-Wallis test</strong> for comparing population measures of location based on independent samples from more than two groups.</p>
<p>If we want to compare the centers of the distributions of population GMQ score across our three income groups without assuming Normality, we can use <code>kruskal.test</code>.</p>
<p>The hypotheses being tested here are still as before, but for a measure of location other than the population mean</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  GMQ by income.cat3
Kruskal-Wallis chi-squared = 2.3202, df = 2, p-value = 0.3135</code></pre>
</div>
</div>
<p>Again, note that this isn’t much help, though, because we don’t have any measure of effect size, nor do we have any confidence intervals.</p>
<p>That said, most of the time when we have more than two levels of the factor of interest, we won’t bother worrying about potential violations of the Normality assumption unless they are glaring, and will just use the usual one-factor ANOVA approach (with pooled variances) described below, to make the comparisons of interest.</p>
</section>
<section id="can-we-use-the-bootstrap-to-compare-more-than-two-means" class="level3" data-number="25.4.3">
<h3 data-number="25.4.3" class="anchored" data-anchor-id="can-we-use-the-bootstrap-to-compare-more-than-two-means"><span class="header-section-number">25.4.3</span> Can we use the bootstrap to compare more than two means?</h3>
<p>Sure. There are both ANOVA and ANCOVA analogues using the bootstrap, and in fact, there are power calculations based on the bootstrap, too. If you want to see some example code, look at https://sammancuso.com/2017/11/01/model-based-bootstrapped-anova-and-ancova/</p>
</section>
</section>
<section id="the-analysis-of-variance" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="the-analysis-of-variance"><span class="header-section-number">25.5</span> The Analysis of Variance</h2>
<p>Extending the two-sample t test (assuming equal population variances) into a comparison of more than two samples uses the <strong>analysis of variance</strong> or ANOVA.</p>
<p>This is an analysis of a continuous outcome variable on the basis of a single categorical factor, in fact, it’s often called one-factor ANOVA or one-way ANOVA to indicate that the outcome is being split up into the groups defined by a single factor.</p>
<p>The null hypothesis is that the population means are all the same, and the alternative is that this is not the case. When there are just two groups, then this boils down to an F test that is equivalent to the Pooled t test.</p>
<section id="the-oneway.test-approach" class="level3" data-number="25.5.1">
<h3 data-number="25.5.1" class="anchored" data-anchor-id="the-oneway.test-approach"><span class="header-section-number">25.5.1</span> The <code>oneway.test</code> approach</h3>
<p>R will produce some elements of a one-factor ANOVA using the <code>oneway.test</code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oneway.test</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One-way analysis of means

data:  GMQ and income.cat3
F = 0.34687, num df = 2, denom df = 277, p-value = 0.7072</code></pre>
</div>
</div>
<p>This isn’t the full analysis, though, which would require a more complete ANOVA table. There are two equivalent approaches to obtaining the full ANOVA table when comparing a series of 2 or more population means based on independent samples.</p>
</section>
<section id="using-the-aov-approach-and-the-summary-function" class="level3" data-number="25.5.2">
<h3 data-number="25.5.2" class="anchored" data-anchor-id="using-the-aov-approach-and-the-summary-function"><span class="header-section-number">25.5.2</span> Using the <code>aov</code> approach and the <code>summary</code> function</h3>
<p>Here’s one possible ANOVA table, which doesn’t require directly fitting a linear model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146   72.85   0.347  0.707
Residuals   277  58174  210.01               </code></pre>
</div>
</div>
</section>
<section id="using-the-anova-function-after-fitting-a-linear-model" class="level3" data-number="25.5.3">
<h3 data-number="25.5.3" class="anchored" data-anchor-id="using-the-anova-function-after-fitting-a-linear-model"><span class="header-section-number">25.5.3</span> Using the <code>anova</code> function after fitting a linear model</h3>
<p>An equivalent way to get identical results in a slightly different format runs the linear model behind the ANOVA approach directly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
</section>
</section>
<section id="interpreting-the-anova-table" class="level2" data-number="25.6">
<h2 data-number="25.6" class="anchored" data-anchor-id="interpreting-the-anova-table"><span class="header-section-number">25.6</span> Interpreting the ANOVA Table</h2>
<section id="what-are-we-testing" class="level3" data-number="25.6.1">
<h3 data-number="25.6.1" class="anchored" data-anchor-id="what-are-we-testing"><span class="header-section-number">25.6.1</span> What are we Testing?</h3>
<p>The null hypothesis for the ANOVA table is that the population means of the outcome across the various levels of the factor of interest are all the same, against a two-sided alternative hypothesis that the level-specific population means are not all the same.</p>
<p>Specifically, if we have a grouping factor with <em>k</em> levels, then we are testing:</p>
<ul>
<li>H0: All k population means are the same.</li>
<li>HA: At least one of the population means is different from the others.</li>
</ul>
</section>
<section id="elements-of-the-anova-table" class="level3" data-number="25.6.2">
<h3 data-number="25.6.2" class="anchored" data-anchor-id="elements-of-the-anova-table"><span class="header-section-number">25.6.2</span> Elements of the ANOVA Table</h3>
<p>The ANOVA table breaks down the variation in the outcome explained by the k levels of the factor of interest, and the variation in the outcome which remains (the Residual, or Error).</p>
<p>Specifically, the elements of the ANOVA table are:</p>
<ol type="1">
<li>the degrees of freedom (labeled Df) for the factor of interest and for the Residuals</li>
<li>the sums of squares (labeled Sum Sq) for the factor of interest and for the Residuals</li>
<li>the mean square (labeled Mean Sq) for the factor of interest and for the Residuals</li>
<li>the ANOVA F test statistic (labeled F value), which is used to generate</li>
<li>the <em>p</em> value for the comparison assessed by the ANOVA model, labeled Pr(&gt;F)</li>
</ol>
</section>
<section id="the-degrees-of-freedom" class="level3" data-number="25.6.3">
<h3 data-number="25.6.3" class="anchored" data-anchor-id="the-degrees-of-freedom"><span class="header-section-number">25.6.3</span> The Degrees of Freedom</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
<ul>
<li>The <strong>degrees of freedom</strong> attributable to the factor of interest (here, Income category) is the number of levels of the factor minus 1. Here, we have three Income categories (levels), so df(income.cat3) = 2.</li>
<li>The total degrees of freedom are the number of observations (across all levels of the factor) minus 1. We have 280 GMQ scores in the <code>nyfs2a</code> data, so the df(Total) must be 279, although the Total row isn’t shown by R in its output.</li>
<li>The Residual degrees of freedom are the Total df - Factor df. So, here, that’s 279 - 2 = 277.</li>
</ul>
</section>
<section id="the-sums-of-squares" class="level3" data-number="25.6.4">
<h3 data-number="25.6.4" class="anchored" data-anchor-id="the-sums-of-squares"><span class="header-section-number">25.6.4</span> The Sums of Squares</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
<ul>
<li>The sum of squares (often abbreviated SS or Sum Sq) represents variation explained.</li>
<li>The factor SS is the sum across all levels of the factor of the sample size for the level multiplied by the squared difference between the level mean and the overall mean across all levels. Here, SS(<code>income.cat3</code>) = 146</li>
<li>The total SS is the sum across all observations of the square of the difference between the individual values and the overall mean. Here, that is 146 + 58174 = 58320</li>
<li>Residual SS = Total SS - Factor SS.</li>
<li>Also of interest is a calculation called <span class="math inline">\(\eta^2\)</span>, (“eta-squared”), which is equivalent to <span class="math inline">\(R^2\)</span> in a linear model.
<ul>
<li>SS(Factor) / SS(Total) = the proportion of variation in our outcome (here, GMQ) explained by the variation between groups (here, income groups)</li>
<li>In our case, <span class="math inline">\(\eta^2\)</span> = 146 / (146 + 58174) = 146 / 58320 = 0.0025</li>
<li>So, Income Category alone accounts for about 0.25% of the variation in GMQ levels observed in these data.</li>
</ul></li>
</ul>
</section>
<section id="the-mean-square" class="level3" data-number="25.6.5">
<h3 data-number="25.6.5" class="anchored" data-anchor-id="the-mean-square"><span class="header-section-number">25.6.5</span> The Mean Square</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
<ul>
<li>The Mean Square is the Sum of Squares divided by the degrees of freedom, so MS(Factor) = SS(Factor)/df(Factor).</li>
<li>In our case, MS(<code>income.cat3</code>) = SS(<code>income.cat3</code>)/df(<code>income.cat3</code>) = 146 / 2 = 72.848 (notice that R maintains more decimal places than it shows for these calculations) and</li>
<li>MS(Residuals) = SS(Residuals) / df(Residuals) = 58174 / 277 = 210.014.
<ul>
<li>MS(Residuals) or MS(Error) is an estimate of the residual variance which corresponds to <span class="math inline">\(\sigma^2\)</span> in the underlying linear model for the outcome of interest, here <code>GMQ</code>.</li>
</ul></li>
</ul>
</section>
<section id="the-f-test-statistic-and-p-value" class="level3" data-number="25.6.6">
<h3 data-number="25.6.6" class="anchored" data-anchor-id="the-f-test-statistic-and-p-value"><span class="header-section-number">25.6.6</span> The F Test Statistic and <em>p</em> Value</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
<ul>
<li>The ANOVA F test is obtained by calculating MS(Factor) / MS(Residuals). So in our case, F = 72.848 / 210.014 = 0.3469</li>
<li>The F test statistic is then compared to a specific F distribution to obtain a <em>p</em> value, which is shown here to be 0.7072</li>
<li>Specifically, the observed F test statistic is compared to an F distribution with numerator df = Factor df, and denominator df = Residual df to obtain the <em>p</em> value.
<ul>
<li>Here, we have SS(Factor) = 146 (approximately), and df(Factor) = 2, leaving MS(Factor) = 72.848</li>
<li>We have SS(Residual) = 58174, and df(Residual) = 277, leaving MS(Residual) = 210.014</li>
<li>MS(Factor) / MS(Residual) = F value = 0.3469, which, when compared to an F distribution with 2 and 277 degrees of freedom, yields a <em>p</em> value of 0.7072</li>
</ul></li>
</ul>
</section>
</section>
<section id="the-residual-standard-error" class="level2" data-number="25.7">
<h2 data-number="25.7" class="anchored" data-anchor-id="the-residual-standard-error"><span class="header-section-number">25.7</span> The Residual Standard Error</h2>
<p>The residual standard error is simply the square root of the variance estimate MS(Residual). Here, MS(Residual) = 210.014, so the Residual standard error = 14.49 points.</p>
</section>
<section id="the-proportion-of-variance-explained-by-the-factor" class="level2" data-number="25.8">
<h2 data-number="25.8" class="anchored" data-anchor-id="the-proportion-of-variance-explained-by-the-factor"><span class="header-section-number">25.8</span> The Proportion of Variance Explained by the Factor</h2>
<p>We will often summarize the proportion of the variation explained by the factor. The summary statistic is called eta-squared (<span class="math inline">\(\eta^2\)</span>), and is equivalent to the <span class="math inline">\(R^2\)</span> value we have seen previously in linear regression models.</p>
<p>Again, <span class="math inline">\(\eta^2\)</span> = SS(Factor) / SS(Total)</p>
<p>Here, we have - SS(<code>income.cat3</code>) = 146 and SS(Residuals) = 58174, so SS(Total) = 58320 - Thus, <span class="math inline">\(\eta^2\)</span> = SS(Factor)/SS(Total) = 146/58320 = 0.0025</p>
<p>The income category accounts for 0.25% of the variation in GMQ levels: only a tiny fraction.</p>
</section>
<section id="the-regression-approach-to-compare-population-means-based-on-independent-samples" class="level2" data-number="25.9">
<h2 data-number="25.9" class="anchored" data-anchor-id="the-regression-approach-to-compare-population-means-based-on-independent-samples"><span class="header-section-number">25.9</span> The Regression Approach to Compare Population Means based on Independent Samples</h2>
<p>This approach is equivalent to the ANOVA approach, and thus also (when there are just two samples to compare) to the pooled-variance t test. We run a linear regression model to predict the outcome (here, <code>GMQ</code>) on the basis of the categorical factor with three levels (here, <code>income.cat3</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data=</span>nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GMQ ~ income.cat3, data = nyfs2a)

Residuals:
    Min      1Q  Median      3Q     Max 
-42.031  -9.031  -0.031   8.969  49.272 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     97.031      1.464  66.282   &lt;2e-16 ***
income.cat3Middle (25 - 64K)    -1.664      2.116  -0.786    0.432    
income.cat3High (65K or more)   -1.302      2.104  -0.619    0.536    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14.49 on 277 degrees of freedom
Multiple R-squared:  0.002498,  Adjusted R-squared:  -0.004704 
F-statistic: 0.3469 on 2 and 277 DF,  p-value: 0.7072</code></pre>
</div>
</div>
<section id="interpreting-the-regression-output" class="level3" data-number="25.9.1">
<h3 data-number="25.9.1" class="anchored" data-anchor-id="interpreting-the-regression-output"><span class="header-section-number">25.9.1</span> Interpreting the Regression Output</h3>
<p>This output tells us many things, but for now, we’ll focus just on the coefficients output, which tells us that:</p>
<ul>
<li>the point estimate for the population mean GMQ score across “Low” income subjects is 97.03</li>
<li>the point estimate (sample mean difference) for the difference in population mean GMQ level between the “Middle” and “Low” income subjects is -1.66 (in words, the Middle income kids have lower GMQ scores than the Low income kids by 1.66 points on average.)</li>
<li>the point estimate (sample mean difference) for the difference in population mean GMQ level between the “High” and “Low” income subjects is -1.30 (in words, the High income kids have lower GMQ scores than the Low income kids by 1.30 points on average.)</li>
</ul>
<p>Of course, we knew all of this already from a summary of the sample means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>nyfs2a <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(income.cat3) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="fu">mean</span>(GMQ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  income.cat3            n `mean(GMQ)`
  &lt;fct&gt;              &lt;int&gt;       &lt;dbl&gt;
1 Low (below 25K)       98        97.0
2 Middle (25 - 64K)     90        95.4
3 High (65K or more)    92        95.7</code></pre>
</div>
</div>
<p>The model for predicting GMQ is based on two binary (1/0) indicator variables, specifically, we have:</p>
<ul>
<li>Estimated GMQ = 97.03 - 1.66 x [1 if Middle income or 0 if not] - 1.30 x [1 if High income or 0 if not]</li>
</ul>
<p>The coefficients section also provides a standard error and t statistic and two-sided <em>p</em> value for each coefficient.</p>
</section>
<section id="the-full-anova-table" class="level3" data-number="25.9.2">
<h3 data-number="25.9.2" class="anchored" data-anchor-id="the-full-anova-table"><span class="header-section-number">25.9.2</span> The Full ANOVA Table</h3>
<p>To see the full ANOVA table corresponding to any linear regression model, we run…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data=</span>nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: GMQ
             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146  72.848  0.3469 0.7072
Residuals   277  58174 210.014               </code></pre>
</div>
</div>
</section>
<section id="anova-assumptions" class="level3" data-number="25.9.3">
<h3 data-number="25.9.3" class="anchored" data-anchor-id="anova-assumptions"><span class="header-section-number">25.9.3</span> ANOVA Assumptions</h3>
<p>The assumptions behind analysis of variance are the same as those behind a linear model. Of specific interest are:</p>
<ul>
<li>The samples obtained from each group are independent.</li>
<li>Ideally, the samples from each group are a random sample from the population described by that group.</li>
<li>In the population, the variance of the outcome in each group is equal. (This is less of an issue if our study involves a balanced design.)</li>
<li>In the population, we have Normal distributions of the outcome in each group.</li>
</ul>
<p>Happily, the F test is fairly robust to violations of the Normality assumption.</p>
</section>
</section>
<section id="equivalent-approach-to-get-anova-results" class="level2" data-number="25.10">
<h2 data-number="25.10" class="anchored" data-anchor-id="equivalent-approach-to-get-anova-results"><span class="header-section-number">25.10</span> Equivalent approach to get ANOVA Results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
income.cat3   2    146   72.85   0.347  0.707
Residuals   277  58174  210.01               </code></pre>
</div>
</div>
<p>So which of the pairs of means are driving the differences we see?</p>
</section>
<section id="the-problem-of-multiple-comparisons" class="level2" data-number="25.11">
<h2 data-number="25.11" class="anchored" data-anchor-id="the-problem-of-multiple-comparisons"><span class="header-section-number">25.11</span> The Problem of Multiple Comparisons</h2>
<ol type="1">
<li>Suppose we compare High to Low, using a test with <span class="math inline">\(\alpha\)</span> = 0.05</li>
<li>Then we compare Middle to Low on the same outcome, also using <span class="math inline">\(\alpha\)</span> = 0.05</li>
<li>Then we compare High to Middle, also with <span class="math inline">\(\alpha\)</span> = 0.05</li>
</ol>
<p>What is our overall <span class="math inline">\(\alpha\)</span> level across these three comparisons?</p>
<ul>
<li>It could be as bad as 0.05 + 0.05 + 0.05, or 0.15.</li>
<li>Rather than our nominal 95% confidence, we have something as low as 85% confidence across this set of simultaneous comparisons.</li>
</ul>
<section id="the-bonferroni-solution" class="level3" data-number="25.11.1">
<h3 data-number="25.11.1" class="anchored" data-anchor-id="the-bonferroni-solution"><span class="header-section-number">25.11.1</span> The Bonferroni solution</h3>
<ol type="1">
<li>Suppose we compare High to Low, using a test with <span class="math inline">\(\alpha\)</span> = 0.05/3</li>
<li>Then we compare Middle to Low on the same outcome, also using <span class="math inline">\(\alpha\)</span> = 0.05/3</li>
<li>Then we compare High to Middle, also with <span class="math inline">\(\alpha\)</span> = 0.05/3</li>
</ol>
<p>Then across these three comparisons, our overall <span class="math inline">\(\alpha\)</span> can be (at worst)</p>
<ul>
<li>0.05/3 + 0.05/3 + 0.05/3 = 0.05</li>
<li>So by changing our nominal confidence level from 95% to 98.333% in each comparison, we wind up with at least 95% confidence across this set of simultaneous comparisons.</li>
<li>This is a conservative (worst case) approach.</li>
</ul>
<p>Goal: Simultaneous comparisons of White vs AA, AA vs Other and White vs Other</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(nyfs2a<span class="sc">$</span>GMQ, nyfs2a<span class="sc">$</span>income.cat3, <span class="at">p.adjust=</span><span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  nyfs2a$GMQ and nyfs2a$income.cat3 

                   Low (below 25K) Middle (25 - 64K)
Middle (25 - 64K)  1               -                
High (65K or more) 1               1                

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>These <em>p</em> values are very large.</p>
</section>
<section id="pairwise-comparisons-using-tukeys-hsd-method" class="level3" data-number="25.11.2">
<h3 data-number="25.11.2" class="anchored" data-anchor-id="pairwise-comparisons-using-tukeys-hsd-method"><span class="header-section-number">25.11.2</span> Pairwise Comparisons using Tukey’s HSD Method</h3>
<p>Goal: Simultaneous (less conservative) confidence intervals and <em>p</em> values for our three pairwise comparisons (High vs.&nbsp;Low, High vs.&nbsp;Middle, Middle vs.&nbsp;Low)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = GMQ ~ income.cat3, data = nyfs2a)

$income.cat3
                                           diff       lwr      upr     p adj
Middle (25 - 64K)-Low (below 25K)    -1.6639456 -6.649518 3.321627 0.7116745
High (65K or more)-Low (below 25K)   -1.3023514 -6.259595 3.654892 0.8098084
High (65K or more)-Middle (25 - 64K)  0.3615942 -4.701208 5.424396 0.9845073</code></pre>
</div>
</div>
</section>
<section id="plotting-the-tukey-hsd-results" class="level3" data-number="25.11.3">
<h3 data-number="25.11.3" class="anchored" data-anchor-id="plotting-the-tukey-hsd-results"><span class="header-section-number">25.11.3</span> Plotting the Tukey HSD results</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/hsd_plot_nyfs2a-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Note that the default positioning of the y axis in the plot of Tukey HSD results can be problematic. If we have longer names, in particular, for the levels of our factor, R will leave out some of the labels. We can alleviate that problem either by using the <code>fct_recode</code> function in the <code>forcats</code> package to rename the factor levels, or we can use the following code to reconfigure the margins of the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mar.default <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.1</span> <span class="co"># save default plotting margins</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar.default <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">12</span>, <span class="dv">0</span>, <span class="dv">0</span>)) </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(GMQ <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2a)), <span class="at">las =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar.default) <span class="co"># return to normal plotting margins</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="what-if-we-consider-another-outcome-bmi" class="level2" data-number="25.12">
<h2 data-number="25.12" class="anchored" data-anchor-id="what-if-we-consider-another-outcome-bmi"><span class="header-section-number">25.12</span> What if we consider another outcome, BMI?</h2>
<p>We’ll look at the full data set in <code>nyfs2</code> now, so we can look at BMI as a function of income.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>nyfs2<span class="sc">$</span>income.cat3 <span class="ot">&lt;-</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fct_relevel</span>(nyfs2<span class="sc">$</span>income.cat3,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Low (below 25K)"</span>, <span class="st">"Middle (25 - 64K)"</span>, <span class="st">"High (65K or more)"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nyfs2, <span class="fu">aes</span>(<span class="at">x =</span> bmi, <span class="at">y =</span> income.cat3, <span class="at">fill =</span> income.cat3)) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    ggridges<span class="sc">::</span><span class="fu">geom_density_ridges</span>(<span class="at">scale =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body-Mass Index by Income Group"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Body-Mass Index"</span>, <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>    ggridges<span class="sc">::</span><span class="fu">theme_ridges</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt; =
"none")` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nyfs2, <span class="fu">aes</span>(<span class="at">x =</span> income.cat3, <span class="at">y =</span> bmi, <span class="at">fill =</span> income.cat3)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> income.cat3), <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">width =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">notch =</span> <span class="cn">TRUE</span>, <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"BMI for 280 Children in NNYFS"</span>,</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body-Mass Index"</span>, <span class="at">x =</span> <span class="st">"Income Category"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `guides(&lt;scale&gt; = FALSE)` is deprecated. Please use `guides(&lt;scale&gt; =
"none")` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here are the descriptive numerical summaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>mosaic<span class="sc">::</span><span class="fu">favstats</span>(bmi <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         income.cat3  min     Q1 median   Q3  max     mean       sd  n missing
1    Low (below 25K) 13.8 15.500  16.50 17.9 25.2 16.98163 2.194574 98       0
2  Middle (25 - 64K) 13.7 15.225  16.05 16.9 24.1 16.37111 1.898920 90       0
3 High (65K or more) 13.8 15.300  15.85 17.2 21.8 16.27065 1.614395 92       0</code></pre>
</div>
</div>
<p>Here is the ANOVA table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(bmi <span class="sc">~</span> income.cat3, <span class="at">data =</span> nyfs2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: bmi
             Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
income.cat3   2   28.32 14.1583  3.8252 0.02298 *
Residuals   277 1025.26  3.7013                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Let’s consider the Tukey HSD results. First, we’ll create a factor with shorter labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>nyfs2<span class="sc">$</span>inc.new <span class="ot">&lt;-</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fct_recode</span>(nyfs2<span class="sc">$</span>income.cat3, </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Low"</span> <span class="ot">=</span> <span class="st">"Low (below 25K)"</span>, <span class="st">"Middle"</span> <span class="ot">=</span> <span class="st">"Middle (25 - 64K)"</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"High"</span> <span class="ot">=</span> <span class="st">"High (65K or more)"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(bmi <span class="sc">~</span> inc.new, <span class="at">data =</span> nyfs2),</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">conf.level =</span> <span class="fl">0.90</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="25-anova_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It appears that there is a detectable difference between the <code>bmi</code> means of the “Low” group and both the “High” and “Middle” group at the 90% confidence level, but no detectable difference between “Middle” and “High.” Details of those confidence intervals for those pairwise comparisons follow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(bmi <span class="sc">~</span> inc.new, <span class="at">data =</span> nyfs2),</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    90% family-wise confidence level

Fit: aov(formula = bmi ~ inc.new, data = nyfs2)

$inc.new
                  diff        lwr         upr     p adj
Middle-Low  -0.6105215 -1.1893722 -0.03167084 0.0775491
High-Low    -0.7109805 -1.2865420 -0.13541892 0.0306639
High-Middle -0.1004589 -0.6882764  0.48735849 0.9339289</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>

<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./24-contingency_tables.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./26-mult_reg_intro.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>