<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Notes for 431 - 26&nbsp; Comparing Proportions with Two Independent Samples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./27-power_for_rates.html" rel="next">
<link href="./25-one_proportion.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-testing_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size and Power for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-comparing_rates.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partChold.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Part C coming soon.</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">26.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#a-first-example-ibuprofen-and-sepsis-trial" id="toc-a-first-example-ibuprofen-and-sepsis-trial" class="nav-link" data-scroll-target="#a-first-example-ibuprofen-and-sepsis-trial"> <span class="header-section-number">26.2</span> A First Example: Ibuprofen and Sepsis Trial</a></li>
  <li><a href="#relating-a-treatment-to-an-outcome" id="toc-relating-a-treatment-to-an-outcome" class="nav-link" data-scroll-target="#relating-a-treatment-to-an-outcome"> <span class="header-section-number">26.3</span> Relating a Treatment to an Outcome</a></li>
  <li><a href="#definitions-of-probability-and-odds" id="toc-definitions-of-probability-and-odds" class="nav-link" data-scroll-target="#definitions-of-probability-and-odds"> <span class="header-section-number">26.4</span> Definitions of Probability and Odds</a></li>
  <li><a href="#defining-the-relative-risk" id="toc-defining-the-relative-risk" class="nav-link" data-scroll-target="#defining-the-relative-risk"> <span class="header-section-number">26.5</span> Defining the Relative Risk</a></li>
  <li><a href="#defining-the-risk-difference" id="toc-defining-the-risk-difference" class="nav-link" data-scroll-target="#defining-the-risk-difference"> <span class="header-section-number">26.6</span> Defining the Risk Difference</a></li>
  <li><a href="#defining-the-odds-ratio-or-the-cross-product-ratio" id="toc-defining-the-odds-ratio-or-the-cross-product-ratio" class="nav-link" data-scroll-target="#defining-the-odds-ratio-or-the-cross-product-ratio"> <span class="header-section-number">26.7</span> Defining the Odds Ratio, or the Cross-Product Ratio</a></li>
  <li><a href="#comparing-rates-in-a-2x2-table" id="toc-comparing-rates-in-a-2x2-table" class="nav-link" data-scroll-target="#comparing-rates-in-a-2x2-table"> <span class="header-section-number">26.8</span> Comparing Rates in a 2x2 Table</a></li>
  <li><a href="#the-twobytwo-function-in-r" id="toc-the-twobytwo-function-in-r" class="nav-link" data-scroll-target="#the-twobytwo-function-in-r"> <span class="header-section-number">26.9</span> The <code>twobytwo</code> function in R</a>
  <ul class="collapse">
  <li><a href="#standard-epidemiological-format" id="toc-standard-epidemiological-format" class="nav-link" data-scroll-target="#standard-epidemiological-format"> <span class="header-section-number">26.9.1</span> Standard Epidemiological Format</a></li>
  <li><a href="#outcome-probabilities-and-confidence-intervals-within-the-treatment-groups" id="toc-outcome-probabilities-and-confidence-intervals-within-the-treatment-groups" class="nav-link" data-scroll-target="#outcome-probabilities-and-confidence-intervals-within-the-treatment-groups"> <span class="header-section-number">26.9.2</span> Outcome Probabilities and Confidence Intervals Within the Treatment Groups</a></li>
  <li><a href="#relative-risk-odds-ratio-and-risk-difference-with-confidence-intervals" id="toc-relative-risk-odds-ratio-and-risk-difference-with-confidence-intervals" class="nav-link" data-scroll-target="#relative-risk-odds-ratio-and-risk-difference-with-confidence-intervals"> <span class="header-section-number">26.9.3</span> Relative Risk, Odds Ratio and Risk Difference, with Confidence Intervals</a></li>
  </ul></li>
  <li><a href="#estimating-a-rate-more-accurately-use-x-2n-4-rather-than-xn" id="toc-estimating-a-rate-more-accurately-use-x-2n-4-rather-than-xn" class="nav-link" data-scroll-target="#estimating-a-rate-more-accurately-use-x-2n-4-rather-than-xn"> <span class="header-section-number">26.10</span> Estimating a Rate More Accurately: Use (x + 2)/(n + 4) rather than x/n</a></li>
  <li><a href="#a-second-example-ebola-virus-disease-study-again" id="toc-a-second-example-ebola-virus-disease-study-again" class="nav-link" data-scroll-target="#a-second-example-ebola-virus-disease-study-again"> <span class="header-section-number">26.11</span> A Second Example: Ebola Virus Disease Study, again</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Often, when analyzing data from an independent samples design, we are interested in comparing the proportions of subjects that achieve some outcome, across two levels of an exposure, or treatment. In this circumstance, we will first summarize the available data in terms of a 2x2 cross-tabulation, and then apply a series of inferential methods for 2x2 tables to obtain point and interval estimates of interest.</p>
<section id="setup-packages-used-here" class="level2" data-number="26.1">
<h2 data-number="26.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">26.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"data/Love-boost.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="a-first-example-ibuprofen-and-sepsis-trial" class="level2" data-number="26.2">
<h2 data-number="26.2" class="anchored" data-anchor-id="a-first-example-ibuprofen-and-sepsis-trial"><span class="header-section-number">26.2</span> A First Example: Ibuprofen and Sepsis Trial</h2>
<p>As we saw in <a href="20-ibuprofen_sepsis.html">Chapter&nbsp;<span>20</span></a>, we are interested in comparing the percentage of patients in each arm of the trial (Ibuprofen vs.&nbsp;Placebo) that showed an improvement in their temperature (<code>temp_drop</code> &gt; 0). Our primary interest is in comparing the percentage of Ibuprofen patients whose temperature dropped to the percentage of Placebo patients whose temperature dropped.</p>
<ul>
<li>We can summarize the data behind the two proportions we are comparing in a contingency table with two rows which identify the exposure or treatment of interest, and two columns to represent the outcomes of interest.</li>
<li>In this case, we are comparing two groups of subjects based on treatment (<code>treat</code>): those who received Ibuprofen and those who received a placebo. The outcome of interest is whether the subject’s temperature dropped (<code>temp_drop</code> &gt; 0), or not.</li>
<li>In the table, we place the frequency for each combination of a row and a column.</li>
<li>The rows need to be mutually exclusive and collectively exhaustive: each patient must either receive Ibuprofen or Placebo. Similarly, the columns must meet the same standard: every patient’s temperature either drops or does not drop.</li>
</ul>
<p>Here’s the contingency table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sepsis <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/sepsis.csv"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">treat =</span> <span class="fu">factor</span>(treat),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">race =</span> <span class="fu">factor</span>(race))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>sepsis <span class="ot">&lt;-</span> sepsis <span class="sc">|&gt;</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">dropped =</span> <span class="fu">ifelse</span>(temp_drop <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Drop"</span>, <span class="st">"No Drop"</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>sepsis <span class="sc">|&gt;</span> <span class="fu">tabyl</span>(treat, dropped) <span class="sc">|&gt;</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_percentages</span>(<span class="at">denom =</span> <span class="st">"row"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_ns</span>(<span class="at">position =</span> <span class="st">"front"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     treat        Drop     No Drop
 Ibuprofen 107 (71.3%)  43 (28.7%)
   Placebo  80 (53.3%)  70 (46.7%)
     Total 187 (62.3%) 113 (37.7%)</code></pre>
</div>
</div>
<p>In our sample, we observe 71.3% of the 150 Ibuprofen subjects with a positive <code>temp_drop</code> as compared to 53.3% of the 150 Placebo subjects. We want to compare these two probabilities (represented using proportions as 0.713 vs.&nbsp;0.533) to estimate the size of the difference between the proportions with a point estimate and 90% confidence interval.</p>
<p>But there are other comparisons we could make, too. The tricky part is that we have multiple ways to describe the relationship between treatment and outcome. We might compare outcome “risks” directly using the difference in probabilities, or the ratio of the two probabilities, or we might convert the risks to odds, and compare the ratio of those odds. In any case, we’ll get different point estimates and confidence intervals, all of which will help us make conclusions about the evidence available in this trial speaking to differences between Ibuprofen and Placebo.</p>
</section>
<section id="relating-a-treatment-to-an-outcome" class="level2" data-number="26.3">
<h2 data-number="26.3" class="anchored" data-anchor-id="relating-a-treatment-to-an-outcome"><span class="header-section-number">26.3</span> Relating a Treatment to an Outcome</h2>
<p>The question of interest is whether the percentage of subjects whose temperature dropped is different (and probably larger) in the subjects who received Ibuprofen than in those who received the Placebo.</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Treatment Arm</th>
<th style="text-align: right;">Dropped</th>
<th style="text-align: right;">Did Not Drop</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Proportion who dropped</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Ibuprofen</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.713</td>
</tr>
<tr class="even">
<td style="text-align: right;">Placebo</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.533</td>
</tr>
</tbody>
</table>
<p>In other words, what is the relationship between the treatment and the outcome?</p>
</section>
<section id="definitions-of-probability-and-odds" class="level2" data-number="26.4">
<h2 data-number="26.4" class="anchored" data-anchor-id="definitions-of-probability-and-odds"><span class="header-section-number">26.4</span> Definitions of Probability and Odds</h2>
<ul>
<li>Proportion = Probability = Risk of the trait = number with trait / total</li>
<li>Odds of having the trait = (number with the trait / number without the trait) to 1</li>
</ul>
<p>If p is the proportion of subjects with a trait, then the <strong>odds</strong> of having the trait are <span class="math inline">\(\frac{p}{1-p}\)</span> to 1.</p>
<p>So, the probability of a good result (temperature drop) in this case is <span class="math inline">\(\frac{107}{150} = 0.713\)</span> in the Ibuprofen group. The <strong>odds</strong> of a good result are thus <span class="math inline">\(\frac{0.713}{1 - 0.713} = 2.484\)</span> to 1 in the Ibuprofen group.</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Treatment Arm</th>
<th style="text-align: right;">Dropped</th>
<th style="text-align: right;">Did Not Drop</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Pr(dropped)</th>
<th style="text-align: right;">Odds(dropped)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Ibuprofen</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.713</td>
<td style="text-align: right;">2.484</td>
</tr>
<tr class="even">
<td style="text-align: right;">Placebo</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0.533</td>
<td style="text-align: right;">1.141</td>
</tr>
</tbody>
</table>
</section>
<section id="defining-the-relative-risk" class="level2" data-number="26.5">
<h2 data-number="26.5" class="anchored" data-anchor-id="defining-the-relative-risk"><span class="header-section-number">26.5</span> Defining the Relative Risk</h2>
<p>Among the Ibuprofen subjects, the risk of a good outcome (drop in temperature) is 71.3% or, stated as a proportion, 0.713. Among the Placebo subjects, the risk of a good outcome is 53.3% or, stated as a proportion, 0.533.</p>
<p>Our “crude” estimate of the <strong>relative risk</strong> of a good outcome for Ibuprofen subjects as compared to Placebo subjects, is the ratio of these two risks, or 0.713/0.533 = 1.338</p>
<ul>
<li>The fact that this relative risk is greater than 1 indicates that the probability of a good outcome is higher for Ibuprofen subjects than for Placebo subjects.</li>
<li>A relative risk of 1 would indicate that the probability of a good outcome is the same for Ibuprofen subjects and for Placebo subjects.</li>
<li>A relative risk less than 1 would indicate that the probability of a good outcome is lower for Ibuprofen subjects than for Placebo subjects.</li>
</ul>
</section>
<section id="defining-the-risk-difference" class="level2" data-number="26.6">
<h2 data-number="26.6" class="anchored" data-anchor-id="defining-the-risk-difference"><span class="header-section-number">26.6</span> Defining the Risk Difference</h2>
<p>Our “crude” estimate of the <strong>risk difference</strong> of a good outcome for Ibuprofen subjects as compared to Placebo subjects, is 0.713 - 0.533 = 0.180 or 18.0 percentage points.</p>
<ul>
<li>The fact that this risk difference is greater than 0 indicates that the probability of a good outcome is higher for Ibuprofen subjects than for Placebo subjects.</li>
<li>A risk difference of 0 would indicate that the probability of a good outcome is the same for Ibuprofen subjects and for Placebo subjects.</li>
<li>A risk difference less than 0 would indicate that the probability of a good outcome is lower for Ibuprofen subjects than for Placebo subjects.</li>
</ul>
</section>
<section id="defining-the-odds-ratio-or-the-cross-product-ratio" class="level2" data-number="26.7">
<h2 data-number="26.7" class="anchored" data-anchor-id="defining-the-odds-ratio-or-the-cross-product-ratio"><span class="header-section-number">26.7</span> Defining the Odds Ratio, or the Cross-Product Ratio</h2>
<p>Among the Ibuprofen subjects, the odds of a good outcome (temperature drop) are 2.484. Among the placebo subjects, the odds of a good outcome (temperature drop) are 1.141.</p>
<p>So our “crude” estimate of the <strong>odds ratio</strong> of a good outcome for Ibuprofen subjects as compared to placebo subjects, is 2.484 / 1.141 = 2.18</p>
<p>Another way to calculate this odds ratio is to calculate the <strong>cross-product ratio</strong>, which is equal to (a x d) / (b x c), for the 2 by 2 table with counts specified as shown:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">A Generic Table</th>
<th style="text-align: right;">Good Outcome</th>
<th style="text-align: right;">Bad Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Treatment Group 1</td>
<td style="text-align: right;">a</td>
<td style="text-align: right;">b</td>
</tr>
<tr class="even">
<td style="text-align: right;">Treatment Group 2</td>
<td style="text-align: right;">c</td>
<td style="text-align: right;">d</td>
</tr>
</tbody>
</table>
<p>So, for our table, we have a = 107, b = 43, c = 80, and d = 70, so the cross-product ratio is <span class="math inline">\(\frac{107 x 70}{43 x 80} = \frac{7490}{3440} = 2.18\)</span>. As expected, this is the same as the “crude” odds ratio estimate.</p>
<ul>
<li>The fact that this odds ratio risk is greater than 1 indicates that the odds of a good outcome are higher for Ibuprofen subjects than for Placebo subjects.</li>
<li>An odds ratio of 1 would indicate that the odds of a good outcome are the same for Ibuprofen subjects and for Placebo subjects.</li>
<li>An odds ratio less than 1 would indicate that the odds of a good outcome are lower for Ibuprofen subjects than for Placebo subjects.</li>
</ul>
<p>So, we have several different ways to compare the outcomes across the treatments. Are these differences and ratios large enough to rule out chance?</p>
</section>
<section id="comparing-rates-in-a-2x2-table" class="level2" data-number="26.8">
<h2 data-number="26.8" class="anchored" data-anchor-id="comparing-rates-in-a-2x2-table"><span class="header-section-number">26.8</span> Comparing Rates in a 2x2 Table</h2>
<p>What is the relationship between the treatment (Ibuprofen vs.&nbsp;Placebo) and the outcome (drop in temperature) in the following two-by-two table?</p>
</section>
<section id="the-twobytwo-function-in-r" class="level2" data-number="26.9">
<h2 data-number="26.9" class="anchored" data-anchor-id="the-twobytwo-function-in-r"><span class="header-section-number">26.9</span> The <code>twobytwo</code> function in R</h2>
<p>I built the <code>twobytwo</code> function in R (based on existing functions in the <code>Epi</code> library, which you need to have in your installed packages list in order for this to work) to do the work for this problem. All that is required is a single command, and a two-by-two table in standard epidemiological format (with the outcomes in the columns, and the treatments in the rows.)</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Treatment Arm</th>
<th style="text-align: right;">Dropped</th>
<th style="text-align: right;">Did Not Drop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Ibuprofen</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="even">
<td style="text-align: right;">Placebo</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">70</td>
</tr>
</tbody>
</table>
<p>The command just requires you to read off the cells of the table, followed by the labels for the two treatments, then the two outcomes, then a specification of the names of the rows (exposures) and columns (outcomes) from the table, and a specification of the confidence level you desire. We’ll use 90% here.</p>
<p>The resulting output follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twobytwo</span>(<span class="dv">107</span>, <span class="dv">43</span>, <span class="dv">80</span>, <span class="dv">70</span>, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Ibuprofen"</span>, <span class="st">"Placebo"</span>, <span class="st">"Dropped"</span>, <span class="st">"No Drop"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Dropped 
Comparing : Ibuprofen vs. Placebo 

          Dropped No Drop    P(Dropped) 90% conf. interval
Ibuprofen     107      43        0.7133    0.6490   0.7701
Placebo        80      70        0.5333    0.4661   0.5993

                                   90% conf. interval
             Relative Risk: 1.3375    1.1492   1.5567
         Sample Odds Ratio: 2.1773    1.4583   3.2509
Conditional MLE Odds Ratio: 2.1716    1.4177   3.3437
    Probability difference: 0.1800    0.0881   0.2677

             Exact P-value: 0.0019 
        Asymptotic P-value: 0.0014 
------------------------------------------------------</code></pre>
</div>
</div>
<section id="standard-epidemiological-format" class="level3" data-number="26.9.1">
<h3 data-number="26.9.1" class="anchored" data-anchor-id="standard-epidemiological-format"><span class="header-section-number">26.9.1</span> Standard Epidemiological Format</h3>
<p>This table is in <strong>standard epidemiological format</strong>, which means that:</p>
<ul>
<li>The rows of the table describe the “treatment” (which we’ll take here to be <code>treat</code>). The more interesting (sometimes also the more common) “treatment” is placed in the top row. That’s Ibuprofen here.</li>
<li>The columns of the table describe the “outcome” (which we’ll take here to be whether the subject’s temperature dropped.) Typically, the more common “outcome” is placed to the left.</li>
</ul>
</section>
<section id="outcome-probabilities-and-confidence-intervals-within-the-treatment-groups" class="level3" data-number="26.9.2">
<h3 data-number="26.9.2" class="anchored" data-anchor-id="outcome-probabilities-and-confidence-intervals-within-the-treatment-groups"><span class="header-section-number">26.9.2</span> Outcome Probabilities and Confidence Intervals Within the Treatment Groups</h3>
<p>The <code>twobytwo</code> output starts with estimates of the probability (risk) of a “Dropped” outcome among subjects who fall into the two treatment groups (Ibuprofen or Placebo), along with 90% confidence intervals for each of these probabilities.</p>
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Dropped 
Comparing : Ibuprofen vs. Placebo 

          Dropped No Drop    P(Dropped) 90% conf. interval
Ibuprofen     107      43        0.7133    0.6490   0.7701
Placebo        80      70        0.5333    0.4661   0.5993</code></pre>
<p>The conditional probability of a temperature drop given that the subject is in the Ibuprofen group, is symbolized as Pr(Dropped | Ibuprofen) = 0.7133, and the 90% confidence interval around that proportion is (0.6490, 0.7701).</p>
<ul>
<li>Note that these two confidence intervals fail to overlap, and so we expect to see a fairly large difference in the estimated probability of a temperature drop when we compare Ibuprofen to Placebo.</li>
</ul>
</section>
<section id="relative-risk-odds-ratio-and-risk-difference-with-confidence-intervals" class="level3" data-number="26.9.3">
<h3 data-number="26.9.3" class="anchored" data-anchor-id="relative-risk-odds-ratio-and-risk-difference-with-confidence-intervals"><span class="header-section-number">26.9.3</span> Relative Risk, Odds Ratio and Risk Difference, with Confidence Intervals</h3>
<p>These elements are followed by estimates of the relative risk, odds ratio, and risk difference, each with associated 90% confidence intervals.</p>
<pre><code>                                   90% conf. interval
             Relative Risk: 1.3375    1.1492   1.5567
         Sample Odds Ratio: 2.1773    1.4583   3.2509
Conditional MLE Odds Ratio: 2.1716    1.4177   3.3437
    Probability difference: 0.1800    0.0881   0.2677</code></pre>
<ul>
<li>The <strong>relative risk</strong>, or the ratio of P(Temperature Drop | Ibuprofen) to P(Temperature Drop | Placebo), is shown first. Note that the 90% confidence interval is entirely greater than 1.</li>
<li>The <strong>odds ratio</strong> is presented using two different definitions (the sample odds ratio is the cross-product ratio we mentioned earlier). Note that the 90% confidence interval using either approach is entirely greater than 1.</li>
<li>The <strong>probability</strong> (or risk) <strong>difference</strong> [P(Temperature Drop | Ibuprofen) - P(Temperature Drop | Placebo)] is presented last. Note that the 90% confidence interval is entirely greater than 0.</li>
<li>Note carefully that if there had been no difference between Ibuprofen and Placebo, the relative risk and odds ratios would be 1, but the probability difference would be zero.</li>
</ul>
</section>
</section>
<section id="estimating-a-rate-more-accurately-use-x-2n-4-rather-than-xn" class="level2" data-number="26.10">
<h2 data-number="26.10" class="anchored" data-anchor-id="estimating-a-rate-more-accurately-use-x-2n-4-rather-than-xn"><span class="header-section-number">26.10</span> Estimating a Rate More Accurately: Use (x + 2)/(n + 4) rather than x/n</h2>
<p>Suppose you have some data involving n independent tries, with x successes. A natural estimate of the “success rate” in the data is x / n.&nbsp;</p>
<p>But, strangely enough, it turns out this isn’t an entirely satisfying estimator. Alan Agresti provides substantial motivation for the (x + 2)/(n + 4) estimate as an alternative. This is sometimes called a <em>Bayesian augmentation</em>.</p>
<ul>
<li>The big problem with x / n is that it estimates p = 0 or p = 1 when x = 0 or x = n.&nbsp;</li>
<li>It’s also tricky to compute confidence intervals at these extremes, since the usual standard error for a proportion, <span class="math inline">\(\sqrt{n p (1-p)}\)</span>, gives zero, which isn’t quite right.</li>
<li>(x + 2)/(n + 4) is much cleaner, especially when you build a confidence interval for the rate.</li>
<li>The only place where (x + 2)/(n + 4) will go wrong is if n is small and the true probability is very close to 0 or 1.</li>
</ul>
<p>For example, if n = 10, and p is 1 in a million, then x will almost certainly be zero, and an estimate of 1/12 is much worse than the simple 0/10. However, how big a deal is this? If p might be 1 in a million, you’re not going to estimate it with a n = 10 experiment.</p>
<p>Applying this method to our Ibuprofen and Sepsis Trial data, we would simply add two to each frequency in the main four cells in our 2x2 table.</p>
<p>So instead of using</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twobytwo</span>(<span class="dv">107</span>, <span class="dv">43</span>, <span class="dv">80</span>, <span class="dv">70</span>, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Ibuprofen"</span>, <span class="st">"Placebo"</span>, <span class="st">"Dropped"</span>, <span class="st">"No Drop"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>the Bayesian augmentation would encourage us to look at</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twobytwo</span>(<span class="dv">109</span>, <span class="dv">45</span>, <span class="dv">82</span>, <span class="dv">72</span>, </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Ibuprofen"</span>, <span class="st">"Placebo"</span>, <span class="st">"Dropped"</span>, <span class="st">"No Drop"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Dropped 
Comparing : Ibuprofen vs. Placebo 

          Dropped No Drop    P(Dropped) 90% conf. interval
Ibuprofen     109      45        0.7078    0.6441   0.7643
Placebo        82      72        0.5325    0.4662   0.5977

                                   90% conf. interval
             Relative Risk: 1.3293    1.1434   1.5453
         Sample Odds Ratio: 2.1268    1.4337   3.1550
Conditional MLE Odds Ratio: 2.1215    1.3950   3.2421
    Probability difference: 0.1753    0.0845   0.2622

             Exact P-value: 0.0022 
        Asymptotic P-value: 0.0016 
------------------------------------------------------</code></pre>
</div>
</div>
<p>As you can see, the odds ratio and relative risk estimates are (a little) closer to 1, and the probability difference is also a little closer to 0. The Bayesian augmentation provides a slightly more conservative set of estimates of the impact of Ibuprofen as compared to Placebo.</p>
<p>It is likely that the augmented version is a more accurate estimate here, but the two estimates will be comparable, generally, so long as either (a) the sample size in each exposure group is more than, say, 30 subjects, and/or (b) the sample probability of the outcome is between 10% and 90% in each exposure group.</p>
</section>
<section id="a-second-example-ebola-virus-disease-study-again" class="level2" data-number="26.11">
<h2 data-number="26.11" class="anchored" data-anchor-id="a-second-example-ebola-virus-disease-study-again"><span class="header-section-number">26.11</span> A Second Example: Ebola Virus Disease Study, again</h2>
<p>For instance, recall the Ebola Virus Disease study from the <em>New England Journal of Medicine</em> that we described in <a href="25-one_proportion.html#sec-ebola"><span>Section&nbsp;25.4</span></a>. Suppose we want to compare the proportion of deaths among cases that had a definitive outcome who were hospitalized to the proportion of deaths among cases that had a definitive outcome who were not hospitalized.</p>
<p>The article suggests that of the 1,737 cases with a definitive outcome, there were 1,153 hospitalized cases. Across those 1,153 hospitalized cases, 741 people (64.3%) died, which means that across the remaining 584 non-hospitalized cases, 488 people (83.6%) died.</p>
<p>Here is the initial contingency table, using only the numbers from the previous paragraph.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Initial Ebola Table</th>
<th style="text-align: right;">Deceased</th>
<th style="text-align: right;">Alive</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Hospitalized</td>
<td style="text-align: right;">741</td>
<td style="text-align: right;">–</td>
<td style="text-align: right;">1153</td>
</tr>
<tr class="even">
<td style="text-align: right;">Not Hospitalized</td>
<td style="text-align: right;">488</td>
<td style="text-align: right;">–</td>
<td style="text-align: right;">584</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Total</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1737</td>
</tr>
</tbody>
</table>
<p>Now, we can use arithmetic to complete the table, since the rows and the columns are each mutually exclusive and collectively exhaustive.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Ebola 2x2 Table</th>
<th style="text-align: right;">Deceased</th>
<th style="text-align: right;">Alive</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Hospitalized</td>
<td style="text-align: right;">741</td>
<td style="text-align: right;">412</td>
<td style="text-align: right;">1153</td>
</tr>
<tr class="even">
<td style="text-align: right;">Not Hospitalized</td>
<td style="text-align: right;">488</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">584</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Total</td>
<td style="text-align: right;">1229</td>
<td style="text-align: right;">508</td>
<td style="text-align: right;">1737</td>
</tr>
</tbody>
</table>
<p>We want to compare the fatality risk (probability of being in the deceased column) for the population of people in the hospitalized row to the population of people in the not hospitalized row.</p>
<p>We can run these data through R, using the Bayesian augmentation (adding a death and a survival to the hospitalized and also to the not hospitalized groups.) We’ll use a 95% confidence level this time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twobytwo</span>(<span class="dv">741</span><span class="sc">+</span><span class="dv">2</span>, <span class="dv">412</span><span class="sc">+</span><span class="dv">2</span>, <span class="dv">488</span><span class="sc">+</span><span class="dv">2</span>, <span class="dv">96</span><span class="sc">+</span><span class="dv">2</span>, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Hospitalized"</span>, <span class="st">"Not Hospitalized"</span>, <span class="st">"Deceased"</span>, <span class="st">"Alive"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Deceased 
Comparing : Hospitalized vs. Not Hospitalized 

                 Deceased Alive    P(Deceased) 95% conf. interval
Hospitalized          743   414         0.6422    0.6141   0.6693
Not Hospitalized      490    98         0.8333    0.8010   0.8613

                                    95% conf. interval
             Relative Risk:  0.7706    0.7285   0.8151
         Sample Odds Ratio:  0.3589    0.2801   0.4599
Conditional MLE Odds Ratio:  0.3591    0.2772   0.4624
    Probability difference: -0.1912   -0.2307  -0.1490

             Exact P-value: 0.0000 
        Asymptotic P-value: 0.0000 
------------------------------------------------------</code></pre>
</div>
</div>
<p>I’ll leave it as an exercise for you to interpret these results and draw some conclusions.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./25-one_proportion.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./27-power_for_rates.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>