<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Notes for 431 - 28&nbsp; Larger Contingency Tables</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./29-mult_reg_intro.html" rel="next">
<link href="./27-power_for_rates.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-testing_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size and Power for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-contingency_tables.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-regr_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-prediction_wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partChold.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Rest of Part C coming soon.</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">28.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#a-2x3-table-comparing-response-to-active-vs.-placebo" id="toc-a-2x3-table-comparing-response-to-active-vs.-placebo" class="nav-link" data-scroll-target="#a-2x3-table-comparing-response-to-active-vs.-placebo"> <span class="header-section-number">28.2</span> A 2x3 Table: Comparing Response to Active vs.&nbsp;Placebo</a>
  <ul class="collapse">
  <li><a href="#getting-the-table-into-r" id="toc-getting-the-table-into-r" class="nav-link" data-scroll-target="#getting-the-table-into-r"> <span class="header-section-number">28.2.1</span> Getting the Table into R</a></li>
  <li><a href="#manipulating-the-tables-presentation" id="toc-manipulating-the-tables-presentation" class="nav-link" data-scroll-target="#manipulating-the-tables-presentation"> <span class="header-section-number">28.2.2</span> Manipulating the Table’s presentation</a></li>
  </ul></li>
  <li><a href="#accuracy-of-death-certificates-a-6x3-table" id="toc-accuracy-of-death-certificates-a-6x3-table" class="nav-link" data-scroll-target="#accuracy-of-death-certificates-a-6x3-table"> <span class="header-section-number">28.3</span> Accuracy of Death Certificates (A 6x3 Table)</a></li>
  <li><a href="#the-pearson-chi-square-test-of-independence" id="toc-the-pearson-chi-square-test-of-independence" class="nav-link" data-scroll-target="#the-pearson-chi-square-test-of-independence"> <span class="header-section-number">28.4</span> The Pearson Chi-Square Test of Independence</a></li>
  <li><a href="#three-way-tables-a-2x2xk-table-and-a-mantel-haenszel-analysis" id="toc-three-way-tables-a-2x2xk-table-and-a-mantel-haenszel-analysis" class="nav-link" data-scroll-target="#three-way-tables-a-2x2xk-table-and-a-mantel-haenszel-analysis"> <span class="header-section-number">28.5</span> Three-Way Tables: A 2x2xK Table and a Mantel-Haenszel Analysis</a>
  <ul class="collapse">
  <li><a href="#smoking-and-mortality-in-the-uk" id="toc-smoking-and-mortality-in-the-uk" class="nav-link" data-scroll-target="#smoking-and-mortality-in-the-uk"> <span class="header-section-number">28.5.1</span> Smoking and Mortality in the UK</a></li>
  <li><a href="#the-whickham-data-with-age-too" id="toc-the-whickham-data-with-age-too" class="nav-link" data-scroll-target="#the-whickham-data-with-age-too"> <span class="header-section-number">28.5.2</span> The <code>whickham</code> data with age, too</a></li>
  <li><a href="#checking-assumptions-the-woolf-test" id="toc-checking-assumptions-the-woolf-test" class="nav-link" data-scroll-target="#checking-assumptions-the-woolf-test"> <span class="header-section-number">28.5.3</span> Checking Assumptions: The Woolf test</a></li>
  <li><a href="#the-cochran-mantel-haenszel-test" id="toc-the-cochran-mantel-haenszel-test" class="nav-link" data-scroll-target="#the-cochran-mantel-haenszel-test"> <span class="header-section-number">28.5.4</span> The Cochran-Mantel-Haenszel Test</a></li>
  <li><a href="#without-the-continuity-correction" id="toc-without-the-continuity-correction" class="nav-link" data-scroll-target="#without-the-continuity-correction"> <span class="header-section-number">28.5.5</span> Without the Continuity Correction</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>What will we do with tables describing data from more than two categories at a time, returning to the notion of independent (rather than paired or matched) samples? The chi-square tests we have already seen in our <code>twobytwo</code> table output will extend nicely to this scenario, especially the Pearson <span class="math inline">\(\chi^2\)</span> (asymptotic) test.</p>
<section id="setup-packages-used-here" class="level2" data-number="28.1">
<h2 data-number="28.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">28.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"data/Love-boost.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Epi)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="a-2x3-table-comparing-response-to-active-vs.-placebo" class="level2" data-number="28.2">
<h2 data-number="28.2" class="anchored" data-anchor-id="a-2x3-table-comparing-response-to-active-vs.-placebo"><span class="header-section-number">28.2</span> A 2x3 Table: Comparing Response to Active vs.&nbsp;Placebo</h2>
<p>The table below, containing 2 rows and 3 columns of data (ignoring the marginal totals) specifies the number of patients who show <em>complete</em>, <em>partial</em>, or <em>no response</em> after treatment with either <strong>active</strong> medication or a <strong>placebo</strong>.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Group</th>
<th style="text-align: center;">None</th>
<th style="text-align: center;">Partial</th>
<th style="text-align: center;">Complete</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Active</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="even">
<td style="text-align: right;">Placebo</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">18</td>
</tr>
</tbody>
</table>
<p>Is there a statistically significant association here? That is to say, is there a statistically significant difference between the treatment groups in the distribution of responses?</p>
<section id="getting-the-table-into-r" class="level3" data-number="28.2.1">
<h3 data-number="28.2.1" class="anchored" data-anchor-id="getting-the-table-into-r"><span class="header-section-number">28.2.1</span> Getting the Table into R</h3>
<p>To answer this, we’ll have to get the data from this contingency table into a matrix in R. Here’s one approach…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>T1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">16</span>,<span class="dv">26</span>,<span class="dv">29</span>,<span class="dv">24</span>,<span class="dv">26</span>,<span class="dv">18</span>), <span class="at">ncol=</span><span class="dv">3</span>, <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(T1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Active"</span>, <span class="st">"Placebo"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(T1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"Partial"</span>, <span class="st">"Complete"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>T1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        None Partial Complete
Active    16      26       29
Placebo   24      26       18</code></pre>
</div>
</div>
</section>
<section id="manipulating-the-tables-presentation" class="level3" data-number="28.2.2">
<h3 data-number="28.2.2" class="anchored" data-anchor-id="manipulating-the-tables-presentation"><span class="header-section-number">28.2.2</span> Manipulating the Table’s presentation</h3>
<p>We can add margins to the matrix to get a table including row and column totals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(T1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        None Partial Complete Sum
Active    16      26       29  71
Placebo   24      26       18  68
Sum       40      52       47 139</code></pre>
</div>
</div>
<p>Instead of the counts, we can tabulate the proportion of all patients within each cell.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(T1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             None   Partial  Complete
Active  0.1151079 0.1870504 0.2086331
Placebo 0.1726619 0.1870504 0.1294964</code></pre>
</div>
</div>
<p>Now, to actually obtain a <em>p</em> value and perform the significance test with <span class="math inline">\(H_0\)</span>: rows and columns are independent vs.&nbsp;<span class="math inline">\(H_A\)</span>: rows and columns are associated, we simply run a Pearson chi-square test on T1 …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(T1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  T1
X-squared = 4.1116, df = 2, p-value = 0.128</code></pre>
</div>
</div>
<p>Thanks to a p-value of about 0.13 (using the Pearson chi-square test) our conclusion would be to retain the null hypothesis of independence in this setting.</p>
<p>We could have run a Fisher’s exact test, too, if we needed it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(T1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  T1
p-value = 0.1346
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>The Fisher exact test <em>p</em> value is also 0.13. Either way, there is insufficient evidence to conclude that there is a (true) difference in the distributions of responses.</p>
</section>
</section>
<section id="accuracy-of-death-certificates-a-6x3-table" class="level2" data-number="28.3">
<h2 data-number="28.3" class="anchored" data-anchor-id="accuracy-of-death-certificates-a-6x3-table"><span class="header-section-number">28.3</span> Accuracy of Death Certificates (A 6x3 Table)</h2>
<p>The table below compiles data from six studies designed to investigate the accuracy of death certificates. The original citation is Kircher T, Nelson J, Burdo H (1985) The autopsy as a measure of accuracy of the death certificate. <em>NEJM</em>, 313, 1263-1269. 5373 autopsies were compared to the causes of death listed on the certificates. Of those, 3726 were confirmed to be accurate, 783 either lacked information or contained inaccuracies but did not require recoding of the underlying cause of death, and 864 were incorrect and required recoding. Do the results across studies appear consistent?</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 27%">
<col style="width: 25%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Date of Study</th>
<th style="text-align: center;">[Confirmed] Accurate</th>
<th style="text-align: center;">[Inaccurate] No Change</th>
<th style="text-align: center;">[Incorrect] Recoding</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1955-1965</td>
<td style="text-align: center;">2040</td>
<td style="text-align: center;">367</td>
<td style="text-align: center;">327</td>
<td style="text-align: center;">2734</td>
</tr>
<tr class="even">
<td style="text-align: center;">1970</td>
<td style="text-align: center;">149</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">257</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1970-1971</td>
<td style="text-align: center;">288</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">383</td>
</tr>
<tr class="even">
<td style="text-align: center;">1975-1977</td>
<td style="text-align: center;">703</td>
<td style="text-align: center;">197</td>
<td style="text-align: center;">252</td>
<td style="text-align: center;">1152</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1977-1978</td>
<td style="text-align: center;">425</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">575</td>
</tr>
<tr class="even">
<td style="text-align: center;">1980</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">79</td>
<td style="text-align: center;">272</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">3726</td>
<td style="text-align: center;">783</td>
<td style="text-align: center;">864</td>
<td style="text-align: center;">5373</td>
</tr>
</tbody>
</table>
</section>
<section id="the-pearson-chi-square-test-of-independence" class="level2" data-number="28.4">
<h2 data-number="28.4" class="anchored" data-anchor-id="the-pearson-chi-square-test-of-independence"><span class="header-section-number">28.4</span> The Pearson Chi-Square Test of Independence</h2>
<p>We can assess the homogeneity of the confirmation results (columns) we observe in the table using a Pearson chi-squared test of independence.</p>
<ul>
<li>The null hypothesis is that the rows and columns are independent.</li>
<li>The alternative hypothesis is that there is an association between the rows and the columns.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>death_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2040</span>,<span class="dv">367</span>,<span class="dv">327</span>,<span class="dv">149</span>,<span class="dv">60</span>,<span class="dv">48</span>,<span class="dv">288</span>,<span class="dv">25</span>,<span class="dv">70</span>,<span class="dv">703</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                      <span class="dv">197</span>,<span class="dv">252</span>,<span class="dv">425</span>,<span class="dv">62</span>,<span class="dv">88</span>,<span class="dv">121</span>,<span class="dv">72</span>,<span class="dv">79</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>, <span class="at">nrow=</span><span class="dv">6</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(death_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"1955-65"</span>, <span class="st">"1970"</span>, <span class="st">"1970-71"</span>, <span class="st">"1975-77"</span>, <span class="st">"1977-78"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"1980"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(death_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Confirmed"</span>, <span class="st">"Inaccurate"</span>, <span class="st">"Incorrect"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(death_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Confirmed Inaccurate Incorrect  Sum
1955-65      2040        367       327 2734
1970          149         60        48  257
1970-71       288         25        70  383
1975-77       703        197       252 1152
1977-78       425         62        88  575
1980          121         72        79  272
Sum          3726        783       864 5373</code></pre>
</div>
</div>
<p>To see the potential heterogeneity across rows in these data, we should perhaps also look at the proportions of autopsies in each of the three accuracy categories for each study.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(<span class="fu">round_half_up</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(death_table,<span class="dv">1</span>),<span class="dv">1</span>),<span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Confirmed Inaccurate Incorrect Sum
1955-65      74.6       13.4      12.0 100
1970         58.0       23.3      18.7 100
1970-71      75.2        6.5      18.3 100
1975-77      61.0       17.1      21.9 100
1977-78      73.9       10.8      15.3 100
1980         44.5       26.5      29.0 100</code></pre>
</div>
</div>
<p>In three of the studies, approximately 3/4 of the results were confirmed. In the other three, 45%, 58% and 61% were confirmed. It looks like there’s a fair amount of variation in results across studies. To see if this is true, formally, we run Pearson’s chi-square test of independence, where the null hypothesis is that the rows and columns are independent, and the alternative hypothesis is that there is an association between the rows and the columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(death_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  death_table
X-squared = 209.09, df = 10, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The chi-square test statistic is 200 on 10 degrees of freedom, yielding p &lt; 0.0001.</p>
<p>Autopsies are not performed at random; in fact, many are done because the cause of death listed on the certificate is uncertain. What problems may arise if you attempt to use the results of these studies to make inference about the population as a whole?</p>
</section>
<section id="three-way-tables-a-2x2xk-table-and-a-mantel-haenszel-analysis" class="level2" data-number="28.5">
<h2 data-number="28.5" class="anchored" data-anchor-id="three-way-tables-a-2x2xk-table-and-a-mantel-haenszel-analysis"><span class="header-section-number">28.5</span> Three-Way Tables: A 2x2xK Table and a Mantel-Haenszel Analysis</h2>
<p>The material I discuss in this section is attributable to Jeff Simonoff and his book <em>Analyzing Categorical Data</em>. The example is taken from Section 8.1 of that book.</p>
<p>A three-dimensional or three-way table of counts often reflects a situation where the rows and columns refer to variables whose association is of primary interest to us, and the third factor (a layer, or strata) describes a control variable, whose effect on our primary association is something we are <em>controlling</em> for in the analysis.</p>
<section id="smoking-and-mortality-in-the-uk" class="level3" data-number="28.5.1">
<h3 data-number="28.5.1" class="anchored" data-anchor-id="smoking-and-mortality-in-the-uk"><span class="header-section-number">28.5.1</span> Smoking and Mortality in the UK</h3>
<p>In the early 1970s and then again 20 years later, in Whickham, United Kingdom, surveys yielded the following relationship between whether a person was a smoker at the time of the original survey and whether they were still alive 20 years later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>whickham1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">502</span>, <span class="dv">230</span>, <span class="dv">443</span>, <span class="dv">139</span>), <span class="at">byrow=</span><span class="cn">TRUE</span>, <span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(whickham1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Non-Smoker"</span>, <span class="st">"Smoker"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(whickham1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Alive"</span>, <span class="st">"Dead"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(whickham1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Alive Dead  Sum
Non-Smoker   502  230  732
Smoker       443  139  582
Sum          945  369 1314</code></pre>
</div>
</div>
<p>Here’s the two-by-two table analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">twoby2</span>(whickham1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 by 2 table analysis: 
------------------------------------------------------ 
Outcome   : Alive 
Comparing : Non-Smoker vs. Smoker 

           Alive Dead    P(Alive) 95% conf. interval
Non-Smoker   502  230      0.6858    0.6512   0.7184
Smoker       443  139      0.7612    0.7248   0.7941

                                    95% conf. interval
             Relative Risk:  0.9010    0.8427   0.9633
         Sample Odds Ratio:  0.6848    0.5353   0.8761
Conditional MLE Odds Ratio:  0.6850    0.5307   0.8822
    Probability difference: -0.0754   -0.1230  -0.0266

             Exact P-value: 0.0030 
        Asymptotic P-value: 0.0026 
------------------------------------------------------</code></pre>
</div>
</div>
<p>There is a detectable association between smoking and mortality, but it isn’t the one you might expect.</p>
<ul>
<li>The odds ratio is 0.68, implying that the odds of having lived were only 68% as large for non-smokers as for smokers.</li>
<li>Does that mean that smoking is <em>good</em> for you?</li>
</ul>
<p>Not likely. There is a key “lurking” variable here - a variable that is related to both smoking and mortality that is obscuring the actual relationship - namely, age.</p>
</section>
<section id="the-whickham-data-with-age-too" class="level3" data-number="28.5.2">
<h3 data-number="28.5.2" class="anchored" data-anchor-id="the-whickham-data-with-age-too"><span class="header-section-number">28.5.2</span> The <code>whickham</code> data with age, too</h3>
<p>The table below gives the mortality experience separated into subtables by initial age group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"18-24"</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="st">"25-34"</span>, <span class="dv">4</span>), </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">rep</span>(<span class="st">"35-44"</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="st">"45-54"</span>, <span class="dv">4</span>), </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">rep</span>(<span class="st">"55-64"</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="st">"65-74"</span>, <span class="dv">4</span>), </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">rep</span>(<span class="st">"75+"</span>, <span class="dv">4</span>))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>smoking <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Smoker"</span>, <span class="st">"Smoker"</span>, <span class="st">"Non-Smoker"</span>, <span class="st">"Non-Smoker"</span>), <span class="dv">7</span>))</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>status <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Alive"</span>, <span class="st">"Dead"</span>), <span class="dv">14</span>))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">53</span>, <span class="dv">2</span>, <span class="dv">61</span>, <span class="dv">1</span>, <span class="dv">121</span>, <span class="dv">3</span>, <span class="dv">152</span>, <span class="dv">5</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>            <span class="dv">95</span>, <span class="dv">14</span>, <span class="dv">114</span>, <span class="dv">7</span>, <span class="dv">103</span>, <span class="dv">27</span>, <span class="dv">66</span>, <span class="dv">12</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>            <span class="dv">64</span>, <span class="dv">51</span>, <span class="dv">81</span>, <span class="dv">40</span>, <span class="dv">7</span>, <span class="dv">29</span>, <span class="dv">28</span>, <span class="dv">101</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span>, <span class="dv">13</span>, <span class="dv">0</span>, <span class="dv">64</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>whickham2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(smoking, status, age, counts) <span class="sc">|&gt;</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">smoking =</span> <span class="fu">factor</span>(smoking),</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">status =</span> <span class="fu">factor</span>(status),</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">age =</span> <span class="fu">factor</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>whickham2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28 × 4
   smoking    status age   counts
   &lt;fct&gt;      &lt;fct&gt;  &lt;fct&gt;  &lt;dbl&gt;
 1 Smoker     Alive  18-24     53
 2 Smoker     Dead   18-24      2
 3 Non-Smoker Alive  18-24     61
 4 Non-Smoker Dead   18-24      1
 5 Smoker     Alive  25-34    121
 6 Smoker     Dead   25-34      3
 7 Non-Smoker Alive  25-34    152
 8 Non-Smoker Dead   25-34      5
 9 Smoker     Alive  35-44     95
10 Smoker     Dead   35-44     14
# … with 18 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>whick_t2 <span class="ot">&lt;-</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xtabs</span>(counts <span class="sc">~</span> smoking <span class="sc">+</span> status <span class="sc">+</span> age, <span class="at">data =</span> whickham2)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>whick_t2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , age = 18-24

            status
smoking      Alive Dead
  Non-Smoker    61    1
  Smoker        53    2

, , age = 25-34

            status
smoking      Alive Dead
  Non-Smoker   152    5
  Smoker       121    3

, , age = 35-44

            status
smoking      Alive Dead
  Non-Smoker   114    7
  Smoker        95   14

, , age = 45-54

            status
smoking      Alive Dead
  Non-Smoker    66   12
  Smoker       103   27

, , age = 55-64

            status
smoking      Alive Dead
  Non-Smoker    81   40
  Smoker        64   51

, , age = 65-74

            status
smoking      Alive Dead
  Non-Smoker    28  101
  Smoker         7   29

, , age = 75+

            status
smoking      Alive Dead
  Non-Smoker     0   64
  Smoker         0   13</code></pre>
</div>
</div>
<p>The sample odds ratios for remaining Alive comparing Non-Smokers to Smokers for each of these subtables (except the last one, where the odds ratio is undefined because of the zero cells) are calculated using the usual cross-product ratio approach, which yields the following results.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Age Group</th>
<th style="text-align: right;">Odds Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">18-24</td>
<td style="text-align: right;">2.30</td>
</tr>
<tr class="even">
<td style="text-align: right;">25-34</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: right;">35-44</td>
<td style="text-align: right;">2.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">45-54</td>
<td style="text-align: right;">1.44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55-64</td>
<td style="text-align: right;">1.61</td>
</tr>
<tr class="even">
<td style="text-align: right;">65-74</td>
<td style="text-align: right;">1.15</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75+</td>
<td style="text-align: right;">Undefined</td>
</tr>
</tbody>
</table>
<p>Thus, for all age groups except 25-34 year olds, not smoking appears to be associated with higher odds of remaining alive.</p>
<p>Why? Not surprisingly, there is a strong association between age and mortality, with mortality rates being very low for young people (2.5% for 18-24 year olds) and increasing to 100% for 75+ year olds.</p>
<p>There is also an association between age and smoking, with smoking rates peaking in the 45-54 year old range and then falling off rapidly. In particular, respondents who were 65 and older at the time of the first survey had very low smoking rates (25.4%) but very high mortality rates (85.5%). Smoking was hardly the cause, however, since even among the 65-74 year olds mortality was higher among smokers (80.6%) than it was among non-smokers (78.3%). A flat version of the table (<code>ftable</code> in R) can help us with these calculations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(whick_t2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  age 18-24 25-34 35-44 45-54 55-64 65-74 75+
smoking    status                                            
Non-Smoker Alive         61   152   114    66    81    28   0
           Dead           1     5     7    12    40   101  64
Smoker     Alive         53   121    95   103    64     7   0
           Dead           2     3    14    27    51    29  13</code></pre>
</div>
</div>
</section>
<section id="checking-assumptions-the-woolf-test" class="level3" data-number="28.5.3">
<h3 data-number="28.5.3" class="anchored" data-anchor-id="checking-assumptions-the-woolf-test"><span class="header-section-number">28.5.3</span> Checking Assumptions: The Woolf test</h3>
<p>We can also obtain a test (using the <code>woolf_test</code> function, in the <code>vcd</code> library) to see if the common odds ratio estimated in the Mantel-Haenszel procedure is reasonable for all age groups. In other words, the Woolf test is a test of the assumption of homogeneous odds ratios across the six age groups.</p>
<p>If the Woolf test is significant, it suggests that the Cochran-Mantel-Haenszel test is not appropriate, since the odds ratios for smoking and mortality vary too much in the sub-tables by age group. Here, we have the following log odds ratios (estimated using conditional maximum likelihood, rather than cross-product ratios) and the associated Woolf test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Next two results use the vcd package</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(whick_t2, <span class="at">log =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>log odds ratios for smoking and status by age 

      18-24       25-34       35-44       45-54       55-64       65-74 
 0.65018114 -0.22473479  0.84069420  0.34608770  0.47421763  0.09933253 
        75+ 
-1.56397554 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">woolf_test</span>(whick_t2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Woolf-test on Homogeneity of Odds Ratios (no 3-Way assoc.)

data:  whick_t2
X-squared = 3.2061, df = 6, p-value = 0.7826</code></pre>
</div>
</div>
<p>As you can see, the Woolf test is not close to our usual standards for statistically detectable results, implying the common odds ratio is at least potentially reasonable for all age groups (or at least the ones under ages 75, where some data are available.)</p>
</section>
<section id="the-cochran-mantel-haenszel-test" class="level3" data-number="28.5.4">
<h3 data-number="28.5.4" class="anchored" data-anchor-id="the-cochran-mantel-haenszel-test"><span class="header-section-number">28.5.4</span> The Cochran-Mantel-Haenszel Test</h3>
<p>So, the marginal table looking at smoking and mortality combining all age groups isn’t the most meaningful summary of the relationship between smoking and mortality. Instead, we need to look at the <em>conditional</em> association of smoking and mortality, <strong>given age</strong>, to address our interests.</p>
<p>The null hypothesis would be that, in the population, smoking and mortality are independent within strata formed by age group. In other words, <span class="math inline">\(H_0\)</span> requires that smoking be of no value in predicting mortality once age has been accounted for.</p>
<p>The alternative hypothesis would be that, in the population, smoking and mortality are associated within the strata formed by age group. In other words, <span class="math inline">\(H_A\)</span> requires that smoking be of at least some value in predicting mortality even after age has been accounted for.</p>
<p>We can consider the evidence that helps us choose between these two hypotheses with a Cochran-Mantel-Haenszel test, which is obtained in R through the <code>mantelhaen.test</code> function. This test requires us to assume that, in the population and within each age group, the smoking-mortality odds ratio is the same. Essentially, this means that the association of smoking with mortality is the same for older and younger people.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mantelhaen.test</span>(whick_t2, <span class="at">conf.level  =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Mantel-Haenszel chi-squared test with continuity correction

data:  whick_t2
Mantel-Haenszel X-squared = 5.435, df = 1, p-value = 0.01974
alternative hypothesis: true common odds ratio is not equal to 1
90 percent confidence interval:
 1.143198 2.041872
sample estimates:
common odds ratio 
          1.52783 </code></pre>
</div>
</div>
<ul>
<li>The Cochran-Mantel-Haenszel test statistic is a bit larger than 5 (after a continuity correction) leading to a <em>p</em> value of 0.02, indicating strong rejection of the null hypothesis of conditional independence of smoking and survival given age.</li>
<li>The estimated common conditional odds ratio is 1.53. This implies that (adjusting for age) being a non-smoker is associated with 53% higher odds of being alive 20 years later than being a smoker.</li>
<li>A 90% confidence interval for that common odds ratio is (1.14, 2.04), reinforcing rejection of the null hypothesis of conditional independence (where the odds ratio would be 1).</li>
</ul>
</section>
<section id="without-the-continuity-correction" class="level3" data-number="28.5.5">
<h3 data-number="28.5.5" class="anchored" data-anchor-id="without-the-continuity-correction"><span class="header-section-number">28.5.5</span> Without the Continuity Correction</h3>
<p>By default, R presents the Mantel-Haenszel test with a continuity correction, when used for a 2x2xK table. In virtually all cases, go ahead and do this, but as you can see below, the difference it makes in this case is modest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mantelhaen.test</span>(whick_t2, <span class="at">correct=</span><span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Mantel-Haenszel chi-squared test without continuity correction

data:  whick_t2
Mantel-Haenszel X-squared = 5.8443, df = 1, p-value = 0.01563
alternative hypothesis: true common odds ratio is not equal to 1
90 percent confidence interval:
 1.143198 2.041872
sample estimates:
common odds ratio 
          1.52783 </code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./27-power_for_rates.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./29-mult_reg_intro.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>