<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Notes for 431 - 31&nbsp; Building Prediction Models for wcgs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./32-galapagos.html" rel="next">
<link href="./30-regr_diagnostics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Notes for 431</a> 
        <div class="sidebar-tools-main">
    <a href="./431-notes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Working with These Notes</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./int_r_setup.html" class="sidebar-item-text sidebar-link">Setting Up R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-datascience.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science and 431</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Part A. Exploring Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-penguins1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Palmer Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-penguins2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarizing Penguins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nhanes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NHANES Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data_types.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-nhanes_cc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More NHANES Summaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-summarizing_quantities.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing Quantities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-summarizing_categories.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Summarizing Categories</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-missing_data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Missing Data and Single Imputation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-nnyfs_foundations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">National Youth Fitness Survey</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-normality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Assessing Normality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-straightlinemodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Straight Line Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-linear_trans.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linearizing Transformations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-crabs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Studying Crab Claws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-hydrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dehydration Recovery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-wcgs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The WCGS</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Part B. Comparing Summaries</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-testing_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hypothesis Testing: What is it good for?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-ci_for_mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Confidence Intervals for a Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ibuprofen_sepsis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ibuprofen in Sepsis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-pairedsamples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Comparing Means with Paired Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-samplesize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sample Size and Power for Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-examples_2means.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Two Examples Comparing Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-one_proportion.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Estimating a Population Proportion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-comparing_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Comparing Proportions with Two Independent Samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-power_for_rates.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Power and Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-contingency_tables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Larger Contingency Tables</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Part C. Building Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-mult_reg_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Multiple Regression: Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-regr_diagnostics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-prediction_wcgs.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-galapagos.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Species Found on the Galapagos Islands</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-nonlinearity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Introduction to Non-linear Terms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-olsfits.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Using <code>ols</code> to fit linear models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35-emp_bmi.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">BMI and Employment Study</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98_gettingdataintoR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting Data Into R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_sessioninfo.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Session Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup-packages-used-here" id="toc-setup-packages-used-here" class="nav-link active" data-scroll-target="#setup-packages-used-here"> <span class="header-section-number">31.1</span> Setup: Packages Used Here</a></li>
  <li><a href="#predicting-cholesterol-level-in-wcgs-again" id="toc-predicting-cholesterol-level-in-wcgs-again" class="nav-link" data-scroll-target="#predicting-cholesterol-level-in-wcgs-again"> <span class="header-section-number">31.2</span> Predicting Cholesterol Level in WCGS, Again</a></li>
  <li><a href="#checking-for-missing-or-problematic-values" id="toc-checking-for-missing-or-problematic-values" class="nav-link" data-scroll-target="#checking-for-missing-or-problematic-values"> <span class="header-section-number">31.3</span> Checking for Missing or Problematic Values</a></li>
  <li><a href="#partitioning-the-wcgs_ms-sample" id="toc-partitioning-the-wcgs_ms-sample" class="nav-link" data-scroll-target="#partitioning-the-wcgs_ms-sample"> <span class="header-section-number">31.4</span> Partitioning the <code>wcgs_ms</code> sample</a></li>
  <li><a href="#should-we-transform-our-outcome" id="toc-should-we-transform-our-outcome" class="nav-link" data-scroll-target="#should-we-transform-our-outcome"> <span class="header-section-number">31.5</span> Should we transform our outcome?</a></li>
  <li><a href="#scatterplot-matrix-and-assessment-of-collinearity" id="toc-scatterplot-matrix-and-assessment-of-collinearity" class="nav-link" data-scroll-target="#scatterplot-matrix-and-assessment-of-collinearity"> <span class="header-section-number">31.6</span> Scatterplot Matrix and Assessment of Collinearity</a></li>
  <li><a href="#fit-our-three-candidate-models" id="toc-fit-our-three-candidate-models" class="nav-link" data-scroll-target="#fit-our-three-candidate-models"> <span class="header-section-number">31.7</span> Fit our Three Candidate Models</a>
  <ul class="collapse">
  <li><a href="#three-candidate-models" id="toc-three-candidate-models" class="nav-link" data-scroll-target="#three-candidate-models"> <span class="header-section-number">31.7.1</span> Three Candidate Models</a></li>
  <li><a href="#could-we-have-fit-other-models" id="toc-could-we-have-fit-other-models" class="nav-link" data-scroll-target="#could-we-have-fit-other-models"> <span class="header-section-number">31.7.2</span> Could we have fit other models?</a></li>
  <li><a href="#coefficients-of-our-3-models-with-tidy" id="toc-coefficients-of-our-3-models-with-tidy" class="nav-link" data-scroll-target="#coefficients-of-our-3-models-with-tidy"> <span class="header-section-number">31.7.3</span> Coefficients of our 3 models with <code>tidy</code></a></li>
  <li><a href="#anova-comparison-of-the-3-models" id="toc-anova-comparison-of-the-3-models" class="nav-link" data-scroll-target="#anova-comparison-of-the-3-models"> <span class="header-section-number">31.7.4</span> ANOVA comparison of the 3 models</a></li>
  <li><a href="#assessing-fit-quality-of-our-3-models-with-glance" id="toc-assessing-fit-quality-of-our-3-models-with-glance" class="nav-link" data-scroll-target="#assessing-fit-quality-of-our-3-models-with-glance"> <span class="header-section-number">31.7.5</span> Assessing Fit Quality of our 3 models with <code>glance</code></a></li>
  </ul></li>
  <li><a href="#develop-residual-plots" id="toc-develop-residual-plots" class="nav-link" data-scroll-target="#develop-residual-plots"> <span class="header-section-number">31.8</span> Develop Residual Plots</a>
  <ul class="collapse">
  <li><a href="#first-set-of-residual-diagnostics-3-models" id="toc-first-set-of-residual-diagnostics-3-models" class="nav-link" data-scroll-target="#first-set-of-residual-diagnostics-3-models"> <span class="header-section-number">31.8.1</span> First Set of Residual Diagnostics (3 models)</a></li>
  <li><a href="#second-set-of-residual-diagnostics-3-models" id="toc-second-set-of-residual-diagnostics-3-models" class="nav-link" data-scroll-target="#second-set-of-residual-diagnostics-3-models"> <span class="header-section-number">31.8.2</span> Second Set of Residual Diagnostics (3 models)</a></li>
  <li><a href="#numerical-summaries-of-these-measures-all-3-models" id="toc-numerical-summaries-of-these-measures-all-3-models" class="nav-link" data-scroll-target="#numerical-summaries-of-these-measures-all-3-models"> <span class="header-section-number">31.8.3</span> Numerical Summaries of these measures (all 3 models)</a></li>
  </ul></li>
  <li><a href="#test-sample-comparisons-for-our-3-models" id="toc-test-sample-comparisons-for-our-3-models" class="nav-link" data-scroll-target="#test-sample-comparisons-for-our-3-models"> <span class="header-section-number">31.9</span> Test Sample Comparisons for our 3 Models</a></li>
  <li><a href="#putting-it-together---which-model-do-we-like-best" id="toc-putting-it-together---which-model-do-we-like-best" class="nav-link" data-scroll-target="#putting-it-together---which-model-do-we-like-best"> <span class="header-section-number">31.10</span> Putting it Together - which model do we like best?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Building Prediction Models for <code>wcgs</code></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Sometimes, we use a regression model for description of a multivariate relationship which requires only that we provide an adequate fit to the data at hand. Should we want to use the model for prediction, then a more appropriate standard which requires us to fit a model that does each of the following three things:</p>
<ol type="1">
<li>[fits well] Provides an adequate fit to the data at hand</li>
<li>[parsimonious] Includes only those predictors which actually have detectable predictive value</li>
<li>[predicts well out of sample] Does a better job predicting our outcome in new data than other alternative models</li>
</ol>
<p>For now, we’ll focus on a pair of issues:</p>
<ol type="a">
<li>Given a set of predictors, how should we let the computer help us understand which subsets of those predictors are most worthy of our additional attention?</li>
<li>Given a pair of models to compare, what tools should we use to determine which one better predicts new data?</li>
</ol>
<section id="setup-packages-used-here" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="setup-packages-used-here"><span class="header-section-number">31.1</span> Setup: Packages Used Here</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">comment =</span> <span class="cn">NA</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_bw</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll also use some functions from the <code>Hmisc</code> and <code>rms</code> packages.</p>
</section>
<section id="predicting-cholesterol-level-in-wcgs-again" class="level2" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="predicting-cholesterol-level-in-wcgs-again"><span class="header-section-number">31.2</span> Predicting Cholesterol Level in WCGS, Again</h2>
<p>To address these issues, I’ll again look at the <code>wcgs</code> data (Western Collaborative Group Study), described in <a href="17-wcgs.html">Chapter&nbsp;<span>17</span></a>, then again in <a href="30-regr_diagnostics.html">Chapter&nbsp;<span>30</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wcgs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/wcgs.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This time, we’ll try to predict the variable <code>chol</code> on the basis of some subset of the following six predictors: <code>age</code>, <code>bmi</code>, <code>sbp</code>, <code>dbp</code>, <code>smoke</code> and <code>dibpat</code>.</p>
<p>The steps we’ll take are as follows.</p>
<ol type="1">
<li>Check the <code>wcgs</code> data for missing or out-of-range values in the variables under study, so we don’t regret it later. Make a decision about how to handle issues here.</li>
<li>Partition the <code>wcgs</code> data into a training (development) sample of 2000 observations, and a test (holdout) sample of the remaining observations.</li>
<li>Using only the model development sample, fit three candidate models.
<ul>
<li>Model A will predict <code>chol</code> using all six predictors.</li>
<li>Model B will predict <code>chol</code> using five predictors, specifically <code>age</code>, <code>bmi</code>, <code>dbp</code>, <code>dibpat</code> and <code>smoke</code>.</li>
<li>Model C will predict <code>chol</code> using only three predictors, specifically <code>age</code>, <code>dbp</code> and <code>smoke</code></li>
</ul></li>
<li>Compare the fit quality of these models in the development sample to see if any of them is superior in terms of in-sample predictive quality.</li>
<li>Assess regression assumptions in each of these models in the development sample.</li>
<li>Finally moving to the holdout sample, compare the quality of predictions made by the models in terms of several criteria to see if any of the models (A, B or C) is clearly superior in terms of out-of-sample prediction.</li>
</ol>
</section>
<section id="checking-for-missing-or-problematic-values" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="checking-for-missing-or-problematic-values"><span class="header-section-number">31.3</span> Checking for Missing or Problematic Values</h2>
<p>Suppose that after consulting with clinical experts, we want to ensure that:</p>
<ul>
<li>all <code>age</code> values are between 39 and 59 years</li>
<li>all <code>bmi</code> are between 15 and 50</li>
<li>all <code>sbp</code> are between 80 and 250 mm Hg</li>
<li>all <code>dbp</code> are between 50 and 200 mm Hg</li>
<li>all values of <code>sbp-dbp</code> are at least 10 and no more than 90 mm Hg</li>
<li>all values of <code>chol</code> are between 100 and 400 mg/dl</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(wcgs <span class="sc">|&gt;</span> <span class="fu">select</span>(age, bmi, sbp, dbp, smoke, dibpat, chol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>select(wcgs, age, bmi, sbp, dbp, smoke, dibpat, chol) 

 7  Variables      3154  Observations
--------------------------------------------------------------------------------
age 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
    3154        0       21    0.996    46.28    6.256       39       40 
     .25      .50      .75      .90      .95 
      42       45       50       55       57 

lowest : 39 40 41 42 43, highest: 55 56 57 58 59
--------------------------------------------------------------------------------
bmi 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
    3154        0      679        1    24.52    2.803    20.59    21.52 
     .25      .50      .75      .90      .95 
   22.96    24.39    25.84    27.45    28.73 

lowest : 11.19061 15.66050 16.87200 17.21633 17.22242
highest: 36.04248 37.22973 37.24805 37.65281 38.94737
--------------------------------------------------------------------------------
sbp 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
    3154        0       62    0.996    128.6    16.25      110      112 
     .25      .50      .75      .90      .95 
     120      126      136      148      156 

lowest :  98 100 102 104 106, highest: 200 208 210 212 230
--------------------------------------------------------------------------------
dbp 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
    3154        0       42    0.992    82.02    10.51       68       70 
     .25      .50      .75      .90      .95 
      76       80       86       94      100 

lowest :  58  60  62  64  66, highest: 125 129 130 136 150
--------------------------------------------------------------------------------
smoke 
       n  missing distinct 
    3154        0        2 
                      
Value         No   Yes
Frequency   1652  1502
Proportion 0.524 0.476
--------------------------------------------------------------------------------
dibpat 
       n  missing distinct 
    3154        0        2 
                        
Value      Type A Type B
Frequency    1589   1565
Proportion  0.504  0.496
--------------------------------------------------------------------------------
chol 
       n  missing distinct     Info     Mean      Gmd      .05      .10 
    3142       12      237        1    226.4    47.99    161.1    175.0 
     .25      .50      .75      .90      .95 
   197.2    223.0    253.0    280.0    302.0 

lowest : 103 110 111 112 113, highest: 386 390 400 414 645
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Here are the issues I see:</p>
<ul>
<li>The (<code>chol</code>) total cholesterol levels include 12 missing values (so we need to decide what to do about them) and values of 414 and 645 that I don’t think are plausible. Since <code>chol</code> is our outcome, I’m inclined to delete those 14 subjects from our analyses.</li>
<li>The <code>bmi</code> value of 11.9 is much smaller than all other values, and seems implausible, so I’m inclined to delete that subject, as well.</li>
<li>All of the <code>age</code> values are between 39 and 59, as they should be.</li>
<li>The <code>dibpat</code> and <code>smoke</code> binary variables each appear to be reasonable given the timing of the data collection (the early 1960s).</li>
<li>The blood pressures, individually, for <code>sbp</code> and <code>dbp</code> appear reasonable in terms of their ranges and have no missing data. It’s worth it to check to see that everyone has a <code>sbp</code> meaningfully larger than their <code>dbp</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wcgs <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">bp_diff =</span> sbp <span class="sc">-</span> dbp) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(id, sbp, dbp, bp_diff) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice_min</span>(bp_diff, <span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
     id   sbp   dbp bp_diff
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1  3822   120   100      20
2 11406   104    80      24
3 10204   110    86      24</code></pre>
</div>
</div>
<p>This looks fine. Are any combinations out of line in the other direction, with a difference of 90 or more?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>wcgs <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">bp_diff =</span> sbp <span class="sc">-</span> dbp) <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(id, sbp, dbp, bp_diff) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(bp_diff <span class="sc">&gt;=</span> <span class="dv">90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
     id   sbp   dbp bp_diff
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1  2172   208   102     106
2 12453   196    86     110
3 12280   190    98      92
4 13268   170    80      90
5  3546   188    90      98
6  2078   188    86     102
7 19078   230   118     112
8 22025   210   108     102</code></pre>
</div>
</div>
<p>This <code>sbp - dbp</code> value is called the pulse pressure. Given that these men did not (at enrollment) have heart disease, it is surprising to see so many values separated by more than what would be typical (about 40-60 mm Hg.)</p>
<p>I’ll be a little aggressive in my cleaning and also drop these 8 subjects with <code>sbp - dbp</code> of 90 or more mm Hg. So, we need to deal with the missingness in <code>chol</code>, the strange <code>bmi</code> value and the strange <code>chol</code> value in addition to dropping subjects with <code>sbp - dbp</code> to get to a “clean” data set here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>wcgs_ms <span class="ot">&lt;-</span> wcgs <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(id, age, bmi, sbp, dbp, smoke, dibpat, chol) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">complete.cases</span>(id, age, bmi, sbp, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                          dbp, smoke, dibpat, chol)) <span class="sc">|&gt;</span> <span class="co"># drops 12 subjects</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(bmi <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">|&gt;</span> <span class="co"># drops 1 subject</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(sbp <span class="sc">-</span> dbp <span class="sc">&lt;</span> <span class="dv">90</span>) <span class="sc">|&gt;</span> <span class="co"># drops 7 more subjects</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(chol <span class="sc">&lt;=</span> <span class="dv">400</span>) <span class="co"># drops 2 more subjects</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(wcgs); <span class="fu">nrow</span>(wcgs_ms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3154</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3132</code></pre>
</div>
</div>
<p>So we have dropped a total of 22 subjects from the data set. We could certainly consider imputing missing values of <code>chol</code>, but I am uncomfortable doing that for an outcome.</p>
</section>
<section id="partitioning-the-wcgs_ms-sample" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="partitioning-the-wcgs_ms-sample"><span class="header-section-number">31.4</span> Partitioning the <code>wcgs_ms</code> sample</h2>
<ol start="2" type="1">
<li>Partition the <code>wcgs_ms</code> tibble into a training (development) sample of 2000 observations, and a test (holdout) sample of the remaining observations.</li>
</ol>
<p>Before we partition, it’s always a good idea to ensure that each of the subject identifiers (here, <code>id</code>) are unique.</p>
<p>We could simply count the number of rows in the data set and make sure it matches the number of distinct <code>id</code> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(wcgs_ms), <span class="fu">n_distinct</span>(wcgs_ms <span class="sc">|&gt;</span> <span class="fu">select</span>(id)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3132 3132</code></pre>
</div>
</div>
<p>Looks good. If you prefer, check directly with the <code>identical()</code> function, which should return TRUE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">identical</span>(<span class="fu">nrow</span>(wcgs_ms), <span class="fu">n_distinct</span>(wcgs_ms <span class="sc">|&gt;</span> <span class="fu">select</span>(id)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Remember to set a seed so that you can replicate the selection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">431</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>wcgs_ms_train <span class="ot">&lt;-</span> <span class="fu">slice_sample</span>(wcgs_ms, <span class="at">n =</span> <span class="dv">2000</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>wcgs_ms_test <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(wcgs_ms, wcgs_ms_train, <span class="at">by =</span> <span class="st">"id"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(wcgs_ms), <span class="fu">nrow</span>(wcgs_ms_train), <span class="fu">nrow</span>(wcgs_ms_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3132 2000 1132</code></pre>
</div>
</div>
<p>OK. This looks good. We have 2000 observations in the training sample, and the rest in the test sample.</p>
<p>Given a large sample size (at least 500 observations in the full data set) I would usually think about holding out somewhere between 20% and 30% of the data in this manner, but it’s OK to stray a bit from those bounds, as we have here, with 1132/3132 = 36% held out for the test sample.</p>
</section>
<section id="should-we-transform-our-outcome" class="level2" data-number="31.5">
<h2 data-number="31.5" class="anchored" data-anchor-id="should-we-transform-our-outcome"><span class="header-section-number">31.5</span> Should we transform our outcome?</h2>
<p>Consider the Box-Cox approach, which we’ll check in our complete (model C) model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxCox</span>(<span class="fu">lm</span>(chol <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="31-prediction_wcgs_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It looks like we might want to consider using the square root of the cholesterol level as our outcome. We’ll try that.</p>
</section>
<section id="scatterplot-matrix-and-assessment-of-collinearity" class="level2" data-number="31.6">
<h2 data-number="31.6" class="anchored" data-anchor-id="scatterplot-matrix-and-assessment-of-collinearity"><span class="header-section-number">31.6</span> Scatterplot Matrix and Assessment of Collinearity</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>wcgs_ms_train <span class="ot">&lt;-</span> wcgs_ms_train <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sqrtchol =</span> <span class="fu">sqrt</span>(chol))</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(wcgs_ms_train <span class="sc">|&gt;</span> <span class="fu">select</span>(age, bmi, sbp, dbp, smoke, dibpat, sqrtchol),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">combo =</span> <span class="fu">wrap</span>(<span class="st">"facethist"</span>, <span class="at">binwidth =</span> <span class="fl">0.5</span>)), </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"2000 subjects in `wcgs_ms_train`"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="31-prediction_wcgs_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With so many observations and more than just a few predictors, it’s not always easy to parse this plot. We might have considered splitting it into two parts.</p>
<p>Let’s check for collinearity. Unsurprisingly, <code>sbp</code> and <code>dbp</code> are highly correlated with each other. Does this give us problems with variance inflation? Again, we’ll consider the largest model we’ll fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(<span class="fu">lm</span>(chol <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      bmi      sbp      dbp    smoke   dibpat 
1.038393 1.157091 2.536938 2.578828 1.035868 1.016123 </code></pre>
</div>
</div>
<p>The VIF is largest for <code>sbp</code> and <code>dbp</code>, suggesting that perhaps we won’t need them both.</p>
<p>There is also a <code>vif</code> function within the <code>rms</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>rms<span class="sc">::</span><span class="fu">vif</span>(<span class="fu">lm</span>(chol <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         age          bmi          sbp          dbp     smokeYes dibpatType B 
    1.038393     1.157091     2.536938     2.578828     1.035868     1.016123 </code></pre>
</div>
</div>
<p>Since we have candidate models using only <code>dbp</code>, let’s see how they fare.</p>
</section>
<section id="fit-our-three-candidate-models" class="level2" data-number="31.7">
<h2 data-number="31.7" class="anchored" data-anchor-id="fit-our-three-candidate-models"><span class="header-section-number">31.7</span> Fit our Three Candidate Models</h2>
<p>Due to our choice to transform our outcome, we will now fit the following candidate models:</p>
<ul>
<li>Model A will predict <code>sqrt(chol)</code> using all six predictors.</li>
<li>Model B will predict <code>sqrt(chol)</code> using five predictors, specifically <code>age</code>, <code>bmi</code>, <code>dbp</code>, <code>dibpat</code> and <code>smoke</code>.</li>
<li>Model C will predict <code>sqrt(chol)</code> using only two predictors, specifically <code>dbp</code> and <code>smoke</code></li>
</ul>
<section id="three-candidate-models" class="level3" data-number="31.7.1">
<h3 data-number="31.7.1" class="anchored" data-anchor-id="three-candidate-models"><span class="header-section-number">31.7.1</span> Three Candidate Models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>modelA <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(chol) <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>modelB <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(chol) <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>modelC <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(chol) <span class="sc">~</span> age <span class="sc">+</span> dbp <span class="sc">+</span> smoke, </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="could-we-have-fit-other-models" class="level3" data-number="31.7.2">
<h3 data-number="31.7.2" class="anchored" data-anchor-id="could-we-have-fit-other-models"><span class="header-section-number">31.7.2</span> Could we have fit other models?</h3>
<p>Sure. One approach would have been to consider an automated variable selection tool, even though they’re all pretty terrible. Stepwise regression is a common, if poor, choice for this task. The problem is that there’s no good tool for this task, essentially, as we’ll discuss further in 432.</p>
<ul>
<li>A stepwise regression applied to <code>modelA</code> in the training sample with backwards elimination suggests our <code>modelB</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(modelA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=1357.64
sqrt(chol) ~ age + bmi + sbp + dbp + smoke + dibpat

         Df Sum of Sq    RSS    AIC
- sbp     1     0.359 3916.0 1355.8
&lt;none&gt;                3915.6 1357.6
- bmi     1     5.044 3920.6 1358.2
- dibpat  1    10.321 3925.9 1360.9
- age     1    22.217 3937.8 1367.0
- dbp     1    28.014 3943.6 1369.9
- smoke   1    46.322 3961.9 1379.2

Step:  AIC=1355.82
sqrt(chol) ~ age + bmi + dbp + smoke + dibpat

         Df Sum of Sq    RSS    AIC
&lt;none&gt;                3916.0 1355.8
- bmi     1     4.858 3920.8 1356.3
- dibpat  1    10.204 3926.2 1359.0
- age     1    21.913 3937.9 1365.0
- smoke   1    46.021 3962.0 1377.2
- dbp     1    52.228 3968.2 1380.3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sqrt(chol) ~ age + bmi + dbp + smoke + dibpat, data = wcgs_ms_train)

Coefficients:
 (Intercept)           age           bmi           dbp      smokeYes  
    12.03138       0.01930       0.02074       0.01835       0.30687  
dibpatType B  
    -0.14393  </code></pre>
</div>
</div>
<ul>
<li>A stepwise regression with forward selection from the intercept only model moving towards <code>modelA</code> in the training sample also suggests <code>modelB</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>min_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">sqrt</span>(chol) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> wcgs_ms_train)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>biggest <span class="ot">&lt;-</span> <span class="fu">formula</span>(<span class="fu">lm</span>(<span class="fu">sqrt</span>(chol) <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> smoke <span class="sc">+</span> dibpat, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> wcgs_ms_train))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>fwd_step <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">step</span>(min_model, <span class="at">direction =</span> <span class="st">'forward'</span>, <span class="at">scope =</span> biggest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=1430.36
sqrt(chol) ~ 1

         Df Sum of Sq    RSS    AIC
+ dbp     1    83.336 4001.7 1391.1
+ sbp     1    57.718 4027.3 1403.9
+ smoke   1    39.557 4045.5 1412.9
+ age     1    39.060 4046.0 1413.1
+ dibpat  1    20.740 4064.3 1422.2
+ bmi     1    19.788 4065.2 1422.7
&lt;none&gt;                4085.0 1430.4

Step:  AIC=1391.13
sqrt(chol) ~ dbp

         Df Sum of Sq    RSS    AIC
+ smoke   1    45.953 3955.7 1370.0
+ age     1    24.171 3977.5 1381.0
+ dibpat  1    16.675 3985.0 1384.8
&lt;none&gt;                4001.7 1391.1
+ bmi     1     1.964 3999.7 1392.2
+ sbp     1     0.766 4000.9 1392.8

Step:  AIC=1370.04
sqrt(chol) ~ dbp + smoke

         Df Sum of Sq    RSS    AIC
+ age     1   24.3512 3931.4 1359.7
+ dibpat  1   13.4535 3942.3 1365.2
+ bmi     1    4.7652 3951.0 1369.6
&lt;none&gt;                3955.7 1370.0
+ sbp     1    0.0080 3955.7 1372.0

Step:  AIC=1359.69
sqrt(chol) ~ dbp + smoke + age

         Df Sum of Sq    RSS    AIC
+ dibpat  1   10.5635 3920.8 1356.3
+ bmi     1    5.2180 3926.2 1359.0
&lt;none&gt;                3931.4 1359.7
+ sbp     1    0.0906 3931.3 1361.6

Step:  AIC=1356.3
sqrt(chol) ~ dbp + smoke + age + dibpat

       Df Sum of Sq    RSS    AIC
+ bmi   1    4.8581 3916.0 1355.8
&lt;none&gt;              3920.8 1356.3
+ sbp   1    0.1735 3920.6 1358.2

Step:  AIC=1355.82
sqrt(chol) ~ dbp + smoke + age + dibpat + bmi

       Df Sum of Sq    RSS    AIC
&lt;none&gt;              3916.0 1355.8
+ sbp   1   0.35901 3915.6 1357.6</code></pre>
</div>
</div>
<p>It is tempting to conclude that <code>modelB</code> is somehow a good model, since both forwards and stepwise regression like <code>modelB</code> in our training sample given the predictors we fed to the algorithm. Resist that temptation. As you’ll see, even with the pretty simple validation strategy we’re going to use here, we won’t wind up selecting model B.</p>
</section>
<section id="coefficients-of-our-3-models-with-tidy" class="level3" data-number="31.7.3">
<h3 data-number="31.7.3" class="anchored" data-anchor-id="coefficients-of-our-3-models-with-tidy"><span class="header-section-number">31.7.3</span> Coefficients of our 3 models with <code>tidy</code></h3>
<p>Given the large sample size, let’s look at some 99% confidence intervals for our model coefficients. We’ll use <code>tidy</code> from the <code>broom</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(modelA, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, conf.low, conf.high, p.value) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:right;"> p.value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 12.058 </td>
   <td style="text-align:right;"> 10.933 </td>
   <td style="text-align:right;"> 13.183 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> age </td>
   <td style="text-align:right;"> 0.019 </td>
   <td style="text-align:right;"> 0.005 </td>
   <td style="text-align:right;"> 0.034 </td>
   <td style="text-align:right;"> 0.001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> bmi </td>
   <td style="text-align:right;"> 0.021 </td>
   <td style="text-align:right;"> -0.013 </td>
   <td style="text-align:right;"> 0.055 </td>
   <td style="text-align:right;"> 0.109 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sbp </td>
   <td style="text-align:right;"> -0.001 </td>
   <td style="text-align:right;"> -0.010 </td>
   <td style="text-align:right;"> 0.007 </td>
   <td style="text-align:right;"> 0.669 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dbp </td>
   <td style="text-align:right;"> 0.020 </td>
   <td style="text-align:right;"> 0.006 </td>
   <td style="text-align:right;"> 0.034 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> smokeYes </td>
   <td style="text-align:right;"> 0.310 </td>
   <td style="text-align:right;"> 0.146 </td>
   <td style="text-align:right;"> 0.475 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dibpatType B </td>
   <td style="text-align:right;"> -0.145 </td>
   <td style="text-align:right;"> -0.308 </td>
   <td style="text-align:right;"> 0.018 </td>
   <td style="text-align:right;"> 0.022 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(modelB, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, conf.low, conf.high, p.value) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:right;"> p.value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 12.031 </td>
   <td style="text-align:right;"> 10.918 </td>
   <td style="text-align:right;"> 13.145 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> age </td>
   <td style="text-align:right;"> 0.019 </td>
   <td style="text-align:right;"> 0.004 </td>
   <td style="text-align:right;"> 0.034 </td>
   <td style="text-align:right;"> 0.001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> bmi </td>
   <td style="text-align:right;"> 0.021 </td>
   <td style="text-align:right;"> -0.013 </td>
   <td style="text-align:right;"> 0.055 </td>
   <td style="text-align:right;"> 0.116 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dbp </td>
   <td style="text-align:right;"> 0.018 </td>
   <td style="text-align:right;"> 0.009 </td>
   <td style="text-align:right;"> 0.028 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> smokeYes </td>
   <td style="text-align:right;"> 0.307 </td>
   <td style="text-align:right;"> 0.143 </td>
   <td style="text-align:right;"> 0.470 </td>
   <td style="text-align:right;"> 0.000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dibpatType B </td>
   <td style="text-align:right;"> -0.144 </td>
   <td style="text-align:right;"> -0.307 </td>
   <td style="text-align:right;"> 0.019 </td>
   <td style="text-align:right;"> 0.023 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(modelC, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(term, estimate, conf.low, conf.high, p.value) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">kable_classic</span>(<span class="at">full_width =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class=" lightable-classic" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> term </th>
   <th style="text-align:right;"> estimate </th>
   <th style="text-align:right;"> conf.low </th>
   <th style="text-align:right;"> conf.high </th>
   <th style="text-align:right;"> p.value </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:right;"> 12.243 </td>
   <td style="text-align:right;"> 11.325 </td>
   <td style="text-align:right;"> 13.160 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> age </td>
   <td style="text-align:right;"> 0.020 </td>
   <td style="text-align:right;"> 0.005 </td>
   <td style="text-align:right;"> 0.035 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dbp </td>
   <td style="text-align:right;"> 0.021 </td>
   <td style="text-align:right;"> 0.012 </td>
   <td style="text-align:right;"> 0.029 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> smokeYes </td>
   <td style="text-align:right;"> 0.305 </td>
   <td style="text-align:right;"> 0.142 </td>
   <td style="text-align:right;"> 0.467 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</section>
<section id="anova-comparison-of-the-3-models" class="level3" data-number="31.7.4">
<h3 data-number="31.7.4" class="anchored" data-anchor-id="anova-comparison-of-the-3-models"><span class="header-section-number">31.7.4</span> ANOVA comparison of the 3 models</h3>
<p>Since model C is a subset of model B which is a subset of model A, we can compare these models with ANOVA tests.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelC, modelB, modelA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sqrt(chol) ~ age + dbp + smoke
Model 2: sqrt(chol) ~ age + bmi + dbp + smoke + dibpat
Model 3: sqrt(chol) ~ age + bmi + sbp + dbp + smoke + dibpat
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)  
1   1996 3931.4                             
2   1994 3916.0  2    15.422 3.9247 0.0199 *
3   1993 3915.6  1     0.359 0.1827 0.6691  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>There appears to be a detectable improvement (using <span class="math inline">\(\alpha = 0.05\)</span>) for model B as compared to model C, but not if we use <span class="math inline">\(\alpha = 0.01\)</span>.</li>
<li>The improvement from model B to model A doesn’t appear to meet the standard for a statistically detectable impact based on this ANOVA comparison.</li>
</ul>
</section>
<section id="assessing-fit-quality-of-our-3-models-with-glance" class="level3" data-number="31.7.5">
<h3 data-number="31.7.5" class="anchored" data-anchor-id="assessing-fit-quality-of-our-3-models-with-glance"><span class="header-section-number">31.7.5</span> Assessing Fit Quality of our 3 models with <code>glance</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>repA <span class="ot">&lt;-</span> <span class="fu">glance</span>(modelA) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">name =</span> <span class="st">"modelA"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>repB <span class="ot">&lt;-</span> <span class="fu">glance</span>(modelB) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">name =</span> <span class="st">"modelB"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>repC <span class="ot">&lt;-</span> <span class="fu">glance</span>(modelC) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">name =</span> <span class="st">"modelC"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>fit_report <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(repA, repB, repC)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>fit_report <span class="sc">|&gt;</span> </span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(name, <span class="at">r2 =</span> r.squared, <span class="at">adjr2 =</span> adj.r.squared, sigma, </span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>           AIC, BIC, nobs, df, <span class="at">df.res =</span> df.residual) <span class="sc">|&gt;</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">kbl</span>(<span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">|&gt;</span> <span class="fu">kable_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> name </th>
   <th style="text-align:right;"> r2 </th>
   <th style="text-align:right;"> adjr2 </th>
   <th style="text-align:right;"> sigma </th>
   <th style="text-align:right;"> AIC </th>
   <th style="text-align:right;"> BIC </th>
   <th style="text-align:right;"> nobs </th>
   <th style="text-align:right;"> df </th>
   <th style="text-align:right;"> df.res </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> modelA </td>
   <td style="text-align:right;"> 0.0415 </td>
   <td style="text-align:right;"> 0.0386 </td>
   <td style="text-align:right;"> 1.402 </td>
   <td style="text-align:right;"> 7035 </td>
   <td style="text-align:right;"> 7080 </td>
   <td style="text-align:right;"> 2000 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 1993 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> modelB </td>
   <td style="text-align:right;"> 0.0414 </td>
   <td style="text-align:right;"> 0.0390 </td>
   <td style="text-align:right;"> 1.401 </td>
   <td style="text-align:right;"> 7034 </td>
   <td style="text-align:right;"> 7073 </td>
   <td style="text-align:right;"> 2000 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 1994 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> modelC </td>
   <td style="text-align:right;"> 0.0376 </td>
   <td style="text-align:right;"> 0.0362 </td>
   <td style="text-align:right;"> 1.403 </td>
   <td style="text-align:right;"> 7037 </td>
   <td style="text-align:right;"> 7065 </td>
   <td style="text-align:right;"> 2000 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 1996 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Our conclusions are:</p>
<ul>
<li>Model A has the strongest <span class="math inline">\(R^2\)</span> value, as it must because it contains the predictors in the other models, and <span class="math inline">\(R^2\)</span> is greedy.</li>
<li>Model B has a slightly stronger adjusted <span class="math inline">\(R^2\)</span> and <span class="math inline">\(\sigma\)</span> than the other models, and also has the best performance according to AIC.</li>
<li>Model C (the smallest of these models) shows the best in-sample BIC result.</li>
<li>None of the differences we observe between these models are particularly large, and none of the models are especially effective, as judged by <span class="math inline">\(R^2\)</span>.</li>
</ul>
</section>
</section>
<section id="develop-residual-plots" class="level2" data-number="31.8">
<h2 data-number="31.8" class="anchored" data-anchor-id="develop-residual-plots"><span class="header-section-number">31.8</span> Develop Residual Plots</h2>
<p>We’ll use <code>augment</code> from the <code>broom</code> package to calculate our summaries of the quality of fit at the level of the individual observations, and the fact that our fitted values refer to the square root of cholesterol level is fine for assessing assumptions in-sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>aug_A <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelA, <span class="at">data =</span> wcgs_ms_train)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>aug_B <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelB, <span class="at">data =</span> wcgs_ms_train)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>aug_C <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelC, <span class="at">data =</span> wcgs_ms_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="first-set-of-residual-diagnostics-3-models" class="level3" data-number="31.8.1">
<h3 data-number="31.8.1" class="anchored" data-anchor-id="first-set-of-residual-diagnostics-3-models"><span class="header-section-number">31.8.1</span> First Set of Residual Diagnostics (3 models)</h3>
<p>For each model, we’ll start with the pair of plots that show us:</p>
<ul>
<li>the residuals vs.&nbsp;the fitted values, to check for non-linearity and non-constant variance, as well as<br>
</li>
<li>Normal Q-Q plots of the standardized residuals to check for important non-Normality.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>p1a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_A, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> aug_A <span class="sc">|&gt;</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_A <span class="sc">|&gt;</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model A"</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>) </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>p1b <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_B, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> aug_B <span class="sc">|&gt;</span> </span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_B <span class="sc">|&gt;</span> </span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model B"</span>,</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>)</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>p1c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_C, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> aug_C <span class="sc">|&gt;</span> </span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_C <span class="sc">|&gt;</span> </span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">slice_max</span>(<span class="fu">abs</span>(.resid), <span class="at">n =</span> <span class="dv">5</span>),</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model C"</span>,</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>         <span class="at">caption =</span> <span class="st">"In each plot, 5 largest |residuals| highlighted in red."</span>,</span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, <span class="at">y =</span> <span class="st">"Residual"</span>)</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>p2a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_A, <span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb37-42"><a href="#cb37-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model A: Normal Q-Q Plot"</span>,</span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Model A Standardized Residual"</span>, </span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Standard Normal Quantiles"</span>)</span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a>p2b <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_B, <span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model B: Normal Q-Q Plot"</span>,</span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Model B Standardized Residual"</span>, </span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Standard Normal Quantiles"</span>)</span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a>p2c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_C, <span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq</span>() <span class="sc">+</span> </span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_qq_line</span>(<span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model C: Normal Q-Q Plot"</span>,</span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Model C Standardized Residual"</span>, </span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Standard Normal Quantiles"</span>)</span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a>(p1a <span class="sc">+</span> p2a) <span class="sc">/</span> (p1b <span class="sc">+</span> p2b) <span class="sc">/</span> (p1c <span class="sc">+</span> p2c) <span class="sc">+</span></span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot_annotation</span>(</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Residual Diagnostics: Set 1 for Models A, B, C"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="31-prediction_wcgs_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In each of these plots, I see no clear signs of substantial non-linearity or any substantial problems with the assumptions of constant variance or Normality. No standardized residuals are especially unusual, and there’s no sign of a substantial curve or fan shape in the plots of residuals vs.&nbsp;fitted values.</p>
</section>
<section id="second-set-of-residual-diagnostics-3-models" class="level3" data-number="31.8.2">
<h3 data-number="31.8.2" class="anchored" data-anchor-id="second-set-of-residual-diagnostics-3-models"><span class="header-section-number">31.8.2</span> Second Set of Residual Diagnostics (3 models)</h3>
<p>As a second check on the assumption of non-constant variance, we’ll draw scale-location plots. As a second check on the potential for poorly fit or highly leveraged points to influence our results, we’ll also run the residuals vs.&nbsp;leverage plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>p3a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_A, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.std.resid)))) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model A Scale-Location Plot"</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Square Root of |Standardized Residual|"</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>p3b <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_B, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.std.resid)))) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model B Scale-Location Plot"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, </span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Square Root of |Standardized Residual|"</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>p3c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_C, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> <span class="fu">sqrt</span>(<span class="fu">abs</span>(.std.resid)))) <span class="sc">+</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model C Scale-Location Plot"</span>,</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fitted sqrt(cholesterol)"</span>, </span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Square Root of |Standardized Residual|"</span>)</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>p4a <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_A, <span class="fu">aes</span>(<span class="at">x =</span> .hat, <span class="at">y =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> aug_A <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_A <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">mean</span>(.hat)), <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model A Residuals vs. Leverage"</span>,</span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Red points indicate Cook's d at least 0.5"</span>,</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Leverage"</span>, <span class="at">y =</span> <span class="st">"Standardized Residual"</span>)</span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a>p4b <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_B, <span class="fu">aes</span>(<span class="at">x =</span> .hat, <span class="at">y =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> aug_B <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_B <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">mean</span>(.hat)), <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model B Residuals vs. Leverage"</span>,</span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Red points indicate Cook's d at least 0.5"</span>,</span>
<span id="cb38-45"><a href="#cb38-45" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Leverage"</span>, <span class="at">y =</span> <span class="st">"Standardized Residual"</span>)</span>
<span id="cb38-46"><a href="#cb38-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-47"><a href="#cb38-47" aria-hidden="true" tabindex="-1"></a>p4c <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(aug_C, <span class="fu">aes</span>(<span class="at">x =</span> .hat, <span class="at">y =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb38-48"><a href="#cb38-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-49"><a href="#cb38-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> aug_C <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-50"><a href="#cb38-50" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb38-51"><a href="#cb38-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data =</span> aug_C <span class="sc">|&gt;</span> <span class="fu">filter</span>(.cooksd <span class="sc">&gt;=</span> <span class="fl">0.5</span>),</span>
<span id="cb38-52"><a href="#cb38-52" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">label =</span> id), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-53"><a href="#cb38-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">span =</span> <span class="dv">2</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb38-54"><a href="#cb38-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">mean</span>(.hat)), <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb38-55"><a href="#cb38-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Model C Residuals vs. Leverage"</span>,</span>
<span id="cb38-56"><a href="#cb38-56" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Red points indicate Cook's d at least 0.5"</span>,</span>
<span id="cb38-57"><a href="#cb38-57" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Leverage"</span>, <span class="at">y =</span> <span class="st">"Standardized Residual"</span>)</span>
<span id="cb38-58"><a href="#cb38-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-59"><a href="#cb38-59" aria-hidden="true" tabindex="-1"></a>(p3a <span class="sc">+</span> p4a) <span class="sc">/</span> (p3b <span class="sc">+</span> p4b) <span class="sc">/</span> (p3c <span class="sc">+</span> p4c) <span class="sc">+</span></span>
<span id="cb38-60"><a href="#cb38-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot_annotation</span>(</span>
<span id="cb38-61"><a href="#cb38-61" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Residual Diagnostics: Set 2 for Models A, B, C"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="31-prediction_wcgs_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Again, I don’t see any signs of powerful trends in the scale-location plot for any of the three models, so there’s no clear sign of non-constant variance.</p>
<p>For each of the three models, the residuals vs.&nbsp;leverage plot shows no points highlighted in red (which would indicate substantial influence - a Cook’s distance value above 5.) So I don’t see anything to worry about.</p>
</section>
<section id="numerical-summaries-of-these-measures-all-3-models" class="level3" data-number="31.8.3">
<h3 data-number="31.8.3" class="anchored" data-anchor-id="numerical-summaries-of-these-measures-all-3-models"><span class="header-section-number">31.8.3</span> Numerical Summaries of these measures (all 3 models)</h3>
<p>We could summarize the largest standardized residual and the largest Cook’s distance, for instance, for each model, with something like this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>aug_A <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(<span class="fu">abs</span>(.std.resid), <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(id, sqrtchol, .fitted, .resid, .std.resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
     id sqrtchol .fitted .resid .std.resid
  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 10340     19.7    14.7   5.08       3.63</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>aug_A <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(.cooksd, <span class="at">n =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(id, sqrtchol, .fitted, .resid, .hat, .cooksd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
     id sqrtchol .fitted .resid    .hat .cooksd
  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 10072     10.6    15.5  -4.90 0.00938  0.0167</code></pre>
</div>
</div>
</section>
</section>
<section id="test-sample-comparisons-for-our-3-models" class="level2" data-number="31.9">
<h2 data-number="31.9" class="anchored" data-anchor-id="test-sample-comparisons-for-our-3-models"><span class="header-section-number">31.9</span> Test Sample Comparisons for our 3 Models</h2>
<p>Finally, we’ll use our three candidate models (A, B and C) to predict the results in our holdout sample of 1132 observations not used to fit these models to see which model performs better in these new data.</p>
<p>Once again, we’ll be using <code>augment</code> to do this work. To start, this is straightforward - we just need to specify the new data we want to predict with <code>newdata</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>test_A <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelA, <span class="at">newdata =</span> wcgs_ms_test) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">mod_n =</span> <span class="st">"Model A"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>test_B <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelB, <span class="at">newdata =</span> wcgs_ms_test) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">mod_n =</span> <span class="st">"Model B"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>test_C <span class="ot">&lt;-</span> <span class="fu">augment</span>(modelC, <span class="at">newdata =</span> wcgs_ms_test) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">mod_n =</span> <span class="st">"Model C"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at the first two results using Model A.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>test_A <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">sqrtchol =</span> <span class="fu">sqrt</span>(chol)) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(chol, sqrtchol, .fitted, .resid) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
   chol sqrtchol .fitted .resid
  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1   194     13.9    15.2 -1.28 
2   258     16.1    15.5  0.592</code></pre>
</div>
</div>
<p>As we can see, the <code>.fitted</code> value is trying to predict the square root of <code>chol</code> and not <code>chol</code>. When we are doing validation in our test sample, it is more helpful to get back to the scale of our original outcome. So here, we’d square the <code>.fitted</code> value (to back out of our square root transformation) and get the actual prediction our model makes for <code>chol</code>. Then we can take the observed <code>chol</code> value and subtract the prediction of <code>chol</code> to get a new residual on the scale of our original <code>chol</code> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>test_res <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(test_A, test_B, test_C) <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fit_chol =</span> .fitted<span class="sc">^</span><span class="dv">2</span>, <span class="at">res_chol =</span> chol <span class="sc">-</span> fit_chol) <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(mod_n, id, chol, fit_chol, res_chol, <span class="fu">everything</span>()) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(id, mod_n)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>test_res <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 13
  mod_n    id  chol fit_c…¹ res_c…²   age   bmi   sbp   dbp smoke dibpat .fitted
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
1 Mode…  2003   181    214.   -33.2    42  23.6   110    78 No    Type B    14.6
2 Mode…  2003   181    214.   -32.7    42  23.6   110    78 No    Type B    14.6
3 Mode…  2003   181    216.   -35.0    42  23.6   110    78 No    Type B    14.7
4 Mode…  2004   132    222.   -89.9    41  23.1   124    78 Yes   Type B    14.9
5 Mode…  2004   132    222.   -89.9    41  23.1   124    78 Yes   Type B    14.9
6 Mode…  2004   132    224.   -92.5    41  23.1   124    78 Yes   Type B    15.0
# … with 1 more variable: .resid &lt;dbl&gt;, and abbreviated variable names
#   ¹​fit_chol, ²​res_chol</code></pre>
</div>
</div>
<p>Now, we can summarize the quality of the predictions across each of the models with four summary statistics calculated across the 1132 observations in the test sample.</p>
<ul>
<li>the mean absolute prediction error, or MAPE</li>
<li>the <em>median</em> absolute prediction error, or medAPE</li>
<li>the maximum absolute prediction error, or maxAPE</li>
<li>the square root of the mean <em>squared</em> prediction error, or RMSPE</li>
</ul>
<p>No one of these dominates the other, but we might be interested in which model gives us the best (smallest) result for each of these summaries. Let’s run them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>test_res <span class="sc">|&gt;</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(mod_n) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">MAPE =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(res_chol)),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">medAPE =</span> <span class="fu">median</span>(<span class="fu">abs</span>(res_chol)),</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">maxAPE =</span> <span class="fu">max</span>(<span class="fu">abs</span>(res_chol)),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">RMSPE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res_chol<span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  mod_n    MAPE medAPE maxAPE RMSPE
  &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 Model A  32.2   27.1   151.  40.8
2 Model B  32.2   27.1   150.  40.8
3 Model C  32.1   26.5   147.  40.8</code></pre>
</div>
</div>
<p>Which model has the best performance in the testing sample?</p>
<ul>
<li>Model C has the smallest (best) MAPE, median APE, maximum APE and RMSPE.</li>
<li>There are no enormous differences between the models on most of these summaries, but Model C (the smallest model) appears a bit better.</li>
</ul>
</section>
<section id="putting-it-together---which-model-do-we-like-best" class="level2" data-number="31.10">
<h2 data-number="31.10" class="anchored" data-anchor-id="putting-it-together---which-model-do-we-like-best"><span class="header-section-number">31.10</span> Putting it Together - which model do we like best?</h2>
<p>It’s worth remembering that none of the three models was particularly strong. Even Model A (with the full set of predictors) had an <span class="math inline">\(R^2\)</span> of only about 4.15%.</p>
<ol type="1">
<li>All 3 models had reasonable residual plots, so we don’t have much to choose from there.</li>
<li>Within the development sample, Model B had slightly better adjusted <span class="math inline">\(R^2\)</span>, <span class="math inline">\(\sigma\)</span> and AIC results than the other models, while Model C had the best BIC.</li>
<li>Model C had the best results in the test sample, across all four summaries we examined.</li>
</ol>
<p>In this case, I’d pick Model C from among these options, based mainly on the stronger test sample results and the fact that it’s a smaller model (with fewer predictors) and if none of the models are going to do very well in terms of predicting <code>chol</code>, there’s not much to choose from anyway.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./30-regr_diagnostics.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regression Diagnostics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./32-galapagos.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Species Found on the Galapagos Islands</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>